\hypertarget{BentShapeRebar_8py_source}{}\section{Bent\+Shape\+Rebar.\+py}

\begin{DoxyCode}
\hypertarget{BentShapeRebar_8py_source.tex_l00001}{}\hyperlink{namespaceBentShapeRebar}{00001} \textcolor{comment}{# -*- coding: utf-8 -*-}
00002 \textcolor{comment}{# ***************************************************************************}
00003 \textcolor{comment}{# *                                                                         *}
00004 \textcolor{comment}{# *   Copyright (c) 2017 - Amritpal Singh <amrit3701@gmail.com>             *}
00005 \textcolor{comment}{# *                                                                         *}
00006 \textcolor{comment}{# *   This program is free software; you can redistribute it and/or modify  *}
00007 \textcolor{comment}{# *   it under the terms of the GNU Lesser General Public License (LGPL)    *}
00008 \textcolor{comment}{# *   as published by the Free Software Foundation; either version 2 of     *}
00009 \textcolor{comment}{# *   the License, or (at your option) any later version.                   *}
00010 \textcolor{comment}{# *   for detail see the LICENCE text file.                                 *}
00011 \textcolor{comment}{# *                                                                         *}
00012 \textcolor{comment}{# *   This program is distributed in the hope that it will be useful,       *}
00013 \textcolor{comment}{# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *}
00014 \textcolor{comment}{# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *}
00015 \textcolor{comment}{# *   GNU Library General Public License for more details.                  *}
00016 \textcolor{comment}{# *                                                                         *}
00017 \textcolor{comment}{# *   You should have received a copy of the GNU Library General Public     *}
00018 \textcolor{comment}{# *   License along with this program; if not, write to the Free Software   *}
00019 \textcolor{comment}{# *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *}
00020 \textcolor{comment}{# *   USA                                                                   *}
00021 \textcolor{comment}{# *                                                                         *}
00022 \textcolor{comment}{# ***************************************************************************}
00023 
\hypertarget{BentShapeRebar_8py_source.tex_l00024}{}\hyperlink{namespaceBentShapeRebar_a38b223debc1826fd2855773a02749bb4}{00024} \_\_title\_\_ = \textcolor{stringliteral}{"BentShapeRebar"}
\hypertarget{BentShapeRebar_8py_source.tex_l00025}{}\hyperlink{namespaceBentShapeRebar_ad79a2dbf88601c24aae561033cb48d34}{00025} \_\_author\_\_ = \textcolor{stringliteral}{"Amritpal Singh"}
\hypertarget{BentShapeRebar_8py_source.tex_l00026}{}\hyperlink{namespaceBentShapeRebar_aec768ca6a259d1cc738ea11c79a124e2}{00026} \_\_url\_\_ = \textcolor{stringliteral}{"https://www.freecadweb.org"}
00027 
00028 \textcolor{keyword}{from} PySide \textcolor{keyword}{import} QtCore, QtGui
00029 \textcolor{keyword}{from} Rebarfunc \textcolor{keyword}{import} *
00030 \textcolor{keyword}{from} PySide.QtCore \textcolor{keyword}{import} QT\_TRANSLATE\_NOOP
00031 \textcolor{keyword}{from} RebarDistribution \textcolor{keyword}{import} runRebarDistribution, removeRebarDistribution
00032 \textcolor{keyword}{from} PopUpImage \textcolor{keyword}{import} showPopUpImageDialog
00033 \textcolor{keyword}{import} FreeCAD
00034 \textcolor{keyword}{import} FreeCADGui
00035 \textcolor{keyword}{import} ArchCommands
00036 \textcolor{keyword}{import} os
00037 \textcolor{keyword}{import} sys
00038 \textcolor{keyword}{import} math
00039 
\hypertarget{BentShapeRebar_8py_source.tex_l00040}{}\hyperlink{namespaceBentShapeRebar_a33951a8ab21a73bae42af9f81d7c43c3}{00040} \textcolor{keyword}{def }\hyperlink{namespaceBentShapeRebar_a33951a8ab21a73bae42af9f81d7c43c3}{getpointsOfBentShapeRebar}(FacePRM, l\_cover, r\_cover, b\_cover, t\_cover, 
      bentLength, bentAngle, orientation):
00041     \textcolor{stringliteral}{""" getpointsOfBentShapeRebar(FacePRM, LeftCover, RightCover, BottomCover, TopCover, BentLength,
       BentAngle, Orientation):}
00042 \textcolor{stringliteral}{    Return points of the LShape rebar in the form of array for sketch.}
00043 \textcolor{stringliteral}{    It takes four different orientations input i.e. 'Bottom', 'Top', 'Left', 'Right'.}
00044 \textcolor{stringliteral}{    """}
00045     \textcolor{keywordflow}{if} orientation == \textcolor{stringliteral}{"Bottom"}:
00046         x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00047         y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00048         x2 = x1 + bentLength
00049         y2 = y1
00050         dis = (FacePRM[0][1] - t\_cover - b\_cover) * math.tan(math.radians(bentAngle - 90))
00051         x3 = x2 + dis
00052         y3 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover
00053         x4 = FacePRM[1][0] + FacePRM[0][0] / 2 - r\_cover - bentLength - dis
00054         y4 = y3
00055         x5 = x4 + dis
00056         y5 = y2
00057         x6 = x5 + bentLength
00058         y6 = y5
00059     \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Top"}:
00060         x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00061         y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover
00062         x2 = x1 + bentLength
00063         y2 = y1
00064         dis = (FacePRM[0][1] - t\_cover - b\_cover) * math.tan(math.radians(bentAngle - 90))
00065         x3 = x2 + dis
00066         y3 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00067         x4 = FacePRM[1][0] + FacePRM[0][0] / 2 - r\_cover - bentLength - dis
00068         y4 = y3
00069         x5 = x4 + dis
00070         y5 = y2
00071         x6 = x5 + bentLength
00072         y6 = y5
00073     \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Left"}:
00074         x1 = FacePRM[1][0] + FacePRM[0][0] / 2 - r\_cover
00075         y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00076         x2 = x1
00077         y2 = y1 - bentLength
00078         dis = (FacePRM[0][0] - r\_cover - l\_cover) * math.tan(math.radians(bentAngle - 90))
00079         x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00080         y3 = y2 - dis
00081         x4 = x3
00082         y4 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover + bentLength + dis
00083         x5 = x2
00084         y5 = y4 - dis
00085         x6 = x5
00086         y6 = y5 - bentLength
00087     \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Right"}:
00088         x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00089         y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00090         x2 = x1
00091         y2 = y1 - bentLength
00092         dis = (FacePRM[0][0] - r\_cover - l\_cover) * math.tan(math.radians(bentAngle - 90))
00093         x3 = FacePRM[1][0] + FacePRM[0][0] / 2 - r\_cover
00094         y3 = y2 - dis
00095         x4 = x3
00096         y4 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover + bentLength + dis
00097         x5 = x2
00098         y5 = y4 - dis
00099         x6 = x5
00100         y6 = y5 - bentLength
00101     \textcolor{keywordflow}{return} [FreeCAD.Vector(x1, y1, 0), FreeCAD.Vector(x2, y2, 0),\(\backslash\)
00102            FreeCAD.Vector(x3, y3, 0), FreeCAD.Vector(x4, y4, 0),\(\backslash\)
00103            FreeCAD.Vector(x5, y5, 0), FreeCAD.Vector(x6, y6, 0)]
00104 
\hypertarget{BentShapeRebar_8py_source.tex_l00105}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel}{00105} \textcolor{keyword}{class }\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel}{\_BentShapeRebarTaskPanel}:
\hypertarget{BentShapeRebar_8py_source.tex_l00106}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a0f978d5a751619f8ae7dfe178fb0473e}{00106}     \textcolor{keyword}{def }\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a0f978d5a751619f8ae7dfe178fb0473e}{\_\_init\_\_}(self, Rebar = None):
00107         \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} Rebar:
00108             selected\_obj = FreeCADGui.Selection.getSelectionEx()[0]
\hypertarget{BentShapeRebar_8py_source.tex_l00109}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a24d363ab6c058ce4436a2b29e9c0b279}{00109}             self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a24d363ab6c058ce4436a2b29e9c0b279}{SelectedObj} = selected\_obj.Object
\hypertarget{BentShapeRebar_8py_source.tex_l00110}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a499514a87885d4c9462e3c6dc314ec9c}{00110}             self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a499514a87885d4c9462e3c6dc314ec9c}{FaceName} = selected\_obj.SubElementNames[0]
00111         \textcolor{keywordflow}{else}:
00112             self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a499514a87885d4c9462e3c6dc314ec9c}{FaceName} = Rebar.Base.Support[0][1][0]
00113             self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a24d363ab6c058ce4436a2b29e9c0b279}{SelectedObj} = Rebar.Base.Support[0][0]
\hypertarget{BentShapeRebar_8py_source.tex_l00114}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_acbe07c5ace61552cc4e4899b668d93e5}{00114}         self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_acbe07c5ace61552cc4e4899b668d93e5}{form} = FreeCADGui.PySideUic.loadUi(os.path.splitext(\_\_file\_\_)[0] + \textcolor{stringliteral}{".ui"})
00115         self.form.setWindowTitle(QtGui.QApplication.translate(\textcolor{stringliteral}{"RebarAddon"}, \textcolor{stringliteral}{"Bent Shape Rebar"}, \textcolor{keywordtype}{None}))
00116         self.form.orientation.addItems([\textcolor{stringliteral}{"Bottom"}, \textcolor{stringliteral}{"Top"}, \textcolor{stringliteral}{"Right"}, \textcolor{stringliteral}{"Left"}])
00117         self.form.amount\_radio.clicked.connect(self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ad99f80f17842220db5920e1926ff45a2}{amount\_radio\_clicked})
00118         self.form.spacing\_radio.clicked.connect(self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a7fb1b14fac066c36380036c6d3f3ab4a}{spacing\_radio\_clicked})
00119         self.form.customSpacing.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespaceRebarDistribution_aa547df5cb10d2e64eaa0b51c445fa30b}{runRebarDistribution}(self))
00120         self.form.removeCustomSpacing.clicked.connect(\textcolor{keyword}{lambda}: 
      \hyperlink{namespaceRebarDistribution_a85270a1b6e8c782a9e0ba54add518f2a}{removeRebarDistribution}(self))
00121         self.form.PickSelectedFace.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespaceRebarfunc_a8c003df49ac5f249bd9ea4acfb7d2f8d}{getSelectedFace}(self))
00122         self.form.orientation.currentIndexChanged.connect(self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ab33579342d5fa4d4bf0bc8c9b9dfa526}{getOrientation})
00123         self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/BentShapeRebar.svg"}))
00124         self.form.toolButton.setIcon(self.form.toolButton.style().standardIcon(
      QtGui.QStyle.SP\_DialogHelpButton))
00125         self.form.toolButton.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespacePopUpImage_a8c565620d7de9b4882a44eacb870ad05}{showPopUpImageDialog}(os.path.split
      (os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"/icons/BentShapeRebarDetailed.svg"}))
\hypertarget{BentShapeRebar_8py_source.tex_l00126}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_aae8fd4e66d675c566d0afcee0af2341f}{00126}         self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_aae8fd4e66d675c566d0afcee0af2341f}{Rebar} = Rebar
00127 
\hypertarget{BentShapeRebar_8py_source.tex_l00128}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ab33579342d5fa4d4bf0bc8c9b9dfa526}{00128}     \textcolor{keyword}{def }\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ab33579342d5fa4d4bf0bc8c9b9dfa526}{getOrientation}(self):
00129         orientation = self.form.orientation.currentText()
00130         \textcolor{comment}{#if orientation == "Bottom":}
00131         \textcolor{comment}{#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] +
       "/icons/LShapeRebarBR.svg"))}
00132         \textcolor{comment}{#elif orientation == "Top":}
00133         \textcolor{comment}{#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] +
       "/icons/LShapeRebarBL.svg"))}
00134         \textcolor{comment}{#elif orientation == "Right":}
00135         \textcolor{comment}{#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] +
       "/icons/LShapeRebarTR.svg"))}
00136         \textcolor{comment}{#else:}
00137         \textcolor{comment}{#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] +
       "/icons/LShapeRebarTL.svg"))}
00138 
\hypertarget{BentShapeRebar_8py_source.tex_l00139}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_af363d8287c33547f2b7fc6f6f326d47a}{00139}     \textcolor{keyword}{def }\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_af363d8287c33547f2b7fc6f6f326d47a}{getStandardButtons}(self):
00140         \textcolor{keywordflow}{return} int(QtGui.QDialogButtonBox.Ok) | int(QtGui.QDialogButtonBox.Apply) | int(
      QtGui.QDialogButtonBox.Cancel)
00141 
\hypertarget{BentShapeRebar_8py_source.tex_l00142}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ae92dd6ab03c4b967b064fac00fa0d906}{00142}     \textcolor{keyword}{def }\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ae92dd6ab03c4b967b064fac00fa0d906}{clicked}(self, button):
00143         \textcolor{keywordflow}{if} button == int(QtGui.QDialogButtonBox.Apply):
00144             self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918}{accept}(button)
00145 
\hypertarget{BentShapeRebar_8py_source.tex_l00146}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918}{00146}     \textcolor{keyword}{def }\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918}{accept}(self, signal = None):
00147         f\_cover = self.form.frontCover.text()
00148         f\_cover = FreeCAD.Units.Quantity(f\_cover).Value
00149         b\_cover = self.form.bottomCover.text()
00150         b\_cover = FreeCAD.Units.Quantity(b\_cover).Value
00151         l\_cover = self.form.l\_sideCover.text()
00152         l\_cover = FreeCAD.Units.Quantity(l\_cover).Value
00153         r\_cover = self.form.r\_sideCover.text()
00154         r\_cover = FreeCAD.Units.Quantity(r\_cover).Value
00155         t\_cover = self.form.topCover.text()
00156         t\_cover = FreeCAD.Units.Quantity(t\_cover).Value
00157         bentLength = self.form.bentLength.text()
00158         bentLength = FreeCAD.Units.Quantity(bentLength).Value
00159         bentAngle = self.form.bentAngle.value()
00160         diameter = self.form.diameter.text()
00161         diameter = FreeCAD.Units.Quantity(diameter).Value
00162         rounding = self.form.rounding.value()
00163         orientation = self.form.orientation.currentText()
00164         amount\_check = self.form.amount\_radio.isChecked()
00165         spacing\_check = self.form.spacing\_radio.isChecked()
00166         \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_aae8fd4e66d675c566d0afcee0af2341f}{Rebar}:
00167             \textcolor{keywordflow}{if} amount\_check:
00168                 amount = self.form.amount.value()
00169                 rebar = \hyperlink{namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476}{makeBentShapeRebar}(f\_cover, b\_cover, l\_cover, r\_cover, diameter, 
      t\_cover, bentLength, bentAngle, rounding, \textcolor{keyword}{True}, amount, orientation, self.
      \hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a24d363ab6c058ce4436a2b29e9c0b279}{SelectedObj}, self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a499514a87885d4c9462e3c6dc314ec9c}{FaceName})
00170             \textcolor{keywordflow}{elif} spacing\_check:
00171                 spacing = self.form.spacing.text()
00172                 spacing = FreeCAD.Units.Quantity(spacing).Value
00173                 rebar = \hyperlink{namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476}{makeBentShapeRebar}(f\_cover, b\_cover, l\_cover, r\_cover, diameter, 
      t\_cover, bentLength, bentAngle, rounding, \textcolor{keyword}{False}, spacing, orientation, self.
      \hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a24d363ab6c058ce4436a2b29e9c0b279}{SelectedObj}, self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a499514a87885d4c9462e3c6dc314ec9c}{FaceName})
00174         \textcolor{keywordflow}{else}:
00175             \textcolor{keywordflow}{if} amount\_check:
00176                 amount = self.form.amount.value()
00177                 rebar = \hyperlink{namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171}{editBentShapeRebar}(self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_aae8fd4e66d675c566d0afcee0af2341f}{Rebar}, f\_cover, b\_cover, l\_cover, 
      r\_cover, diameter, t\_cover, bentLength, bentAngle, rounding, \textcolor{keyword}{True}, amount, orientation, self.
      \hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a24d363ab6c058ce4436a2b29e9c0b279}{SelectedObj}, self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a499514a87885d4c9462e3c6dc314ec9c}{FaceName})
00178             \textcolor{keywordflow}{elif} spacing\_check:
00179                 spacing = self.form.spacing.text()
00180                 spacing = FreeCAD.Units.Quantity(spacing).Value
00181                 rebar = \hyperlink{namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171}{editBentShapeRebar}(self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_aae8fd4e66d675c566d0afcee0af2341f}{Rebar}, f\_cover, b\_cover, l\_cover, 
      r\_cover, diameter, t\_cover, bentLength, bentAngle, rounding, \textcolor{keyword}{False}, spacing, orientation, self.
      \hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a24d363ab6c058ce4436a2b29e9c0b279}{SelectedObj}, self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a499514a87885d4c9462e3c6dc314ec9c}{FaceName})
00182         \textcolor{keywordflow}{if} self.CustomSpacing:
00183             rebar.CustomSpacing = self.CustomSpacing
00184             FreeCAD.ActiveDocument.recompute()
00185         self.\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_aae8fd4e66d675c566d0afcee0af2341f}{Rebar} = rebar
00186         \textcolor{keywordflow}{if} signal == int(QtGui.QDialogButtonBox.Apply):
00187             \textcolor{keywordflow}{pass}
00188         \textcolor{keywordflow}{else}:
00189             FreeCADGui.Control.closeDialog(self)
00190 
\hypertarget{BentShapeRebar_8py_source.tex_l00191}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ad99f80f17842220db5920e1926ff45a2}{00191}     \textcolor{keyword}{def }\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ad99f80f17842220db5920e1926ff45a2}{amount\_radio\_clicked}(self):
00192         self.form.spacing.setEnabled(\textcolor{keyword}{False})
00193         self.form.amount.setEnabled(\textcolor{keyword}{True})
00194 
\hypertarget{BentShapeRebar_8py_source.tex_l00195}{}\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a7fb1b14fac066c36380036c6d3f3ab4a}{00195}     \textcolor{keyword}{def }\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel_a7fb1b14fac066c36380036c6d3f3ab4a}{spacing\_radio\_clicked}(self):
00196         self.form.amount.setEnabled(\textcolor{keyword}{False})
00197         self.form.spacing.setEnabled(\textcolor{keyword}{True})
00198 
00199 
\hypertarget{BentShapeRebar_8py_source.tex_l00200}{}\hyperlink{namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476}{00200} \textcolor{keyword}{def }\hyperlink{namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476}{makeBentShapeRebar}(f\_cover, b\_cover, l\_cover, r\_cover, diameter, t\_cover, bentLength,
       bentAngle, rounding, amount\_spacing\_check, amount\_spacing\_value, orientation = "Bottom Left", structure = 
      None, facename = None):
00201     \textcolor{stringliteral}{""" makeBentShapeRebar(FrontCover, BottomCover, LeftCover, RightCover, Diameter, TopCover, BentLength,
       BentAngle, Rounding,}
00202 \textcolor{stringliteral}{    AmountSpacingCheck, AmountSpacingValue, Orientation, Structure, Facename): Adds the Bent-Shape
       reinforcement bar to the}
00203 \textcolor{stringliteral}{    selected structural object.}
00204 \textcolor{stringliteral}{    It takes four different orientations input i.e. 'Bottom', 'Top', 'Left', 'Right'.}
00205 \textcolor{stringliteral}{    """}
00206     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} structure \textcolor{keywordflow}{and} \textcolor{keywordflow}{not} facename:
00207         selected\_obj = FreeCADGui.Selection.getSelectionEx()[0]
00208         structure = selected\_obj.Object
00209         facename = selected\_obj.SubElementNames[0]
00210     face = structure.Shape.Faces[\hyperlink{namespaceRebarfunc_a3885b3b63e3a41508ac79bc7550cf301}{getFaceNumber}(facename) - 1]
00211     \textcolor{comment}{#StructurePRM = getTrueParametersOfStructure(structure)}
00212     FacePRM = \hyperlink{namespaceRebarfunc_a92122b3d7cedd3d47bb63380a5ac4d08}{getParametersOfFace}(structure, facename)
00213     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} FacePRM:
00214         FreeCAD.Console.PrintError(\textcolor{stringliteral}{"Cannot identified shape or from which base object sturctural element is
       derived\(\backslash\)n"})
00215         \textcolor{keywordflow}{return}
00216     \textcolor{comment}{# Get points of L-Shape rebar}
00217     points = \hyperlink{namespaceBentShapeRebar_a33951a8ab21a73bae42af9f81d7c43c3}{getpointsOfBentShapeRebar}(FacePRM, l\_cover, r\_cover, b\_cover, t\_cover
      , bentLength, bentAngle, orientation)
00218     \textcolor{keyword}{import} Part
00219     \textcolor{keyword}{import} Arch
00220     sketch = FreeCAD.activeDocument().addObject(\textcolor{stringliteral}{'Sketcher::SketchObject'}, \textcolor{stringliteral}{'Sketch'})
00221     sketch.MapMode = \textcolor{stringliteral}{"FlatFace"}
00222     sketch.Support = [(structure, facename)]
00223     FreeCAD.ActiveDocument.recompute()
00224     sketch.addGeometry(Part.LineSegment(points[0], points[1]), \textcolor{keyword}{False})
00225     sketch.addGeometry(Part.LineSegment(points[1], points[2]), \textcolor{keyword}{False})
00226     sketch.addGeometry(Part.LineSegment(points[2], points[3]), \textcolor{keyword}{False})
00227     sketch.addGeometry(Part.LineSegment(points[3], points[4]), \textcolor{keyword}{False})
00228     sketch.addGeometry(Part.LineSegment(points[4], points[5]), \textcolor{keyword}{False})
00229     \textcolor{keyword}{import} Sketcher
00230     \textcolor{keywordflow}{if} amount\_spacing\_check:
00231         rebar = Arch.makeRebar(structure, sketch, diameter, amount\_spacing\_value, f\_cover)
00232         FreeCAD.ActiveDocument.recompute()
00233     \textcolor{keywordflow}{else}:
00234         size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length
00235         rebar = Arch.makeRebar(structure, sketch, diameter, int((size - diameter) / amount\_spacing\_value), 
      f\_cover)
00236     rebar.Rounding = rounding
00237     \textcolor{comment}{# Adds properties to the rebar object}
00238     rebar.ViewObject.addProperty(\textcolor{stringliteral}{"App::PropertyString"}, \textcolor{stringliteral}{"RebarShape"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Shape of rebar"})).RebarShape = \textcolor{stringliteral}{"BentShapeRebar"}
00239     rebar.ViewObject.setEditorMode(\textcolor{stringliteral}{"RebarShape"}, 2)
00240     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"FrontCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Front cover of rebar"})).FrontCover = f\_cover
00241     rebar.setEditorMode(\textcolor{stringliteral}{"FrontCover"}, 2)
00242     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"LeftCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property
      "}, \textcolor{stringliteral}{"Left Side cover of rebar"})).LeftCover = l\_cover
00243     rebar.setEditorMode(\textcolor{stringliteral}{"LeftCover"}, 2)
00244     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"RightCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Right Side cover of rebar"})).RightCover = r\_cover
00245     rebar.setEditorMode(\textcolor{stringliteral}{"RightCover"}, 2)
00246     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"BottomCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Bottom cover of rebar"})).BottomCover = b\_cover
00247     rebar.setEditorMode(\textcolor{stringliteral}{"BottomCover"}, 2)
00248     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyBool"}, \textcolor{stringliteral}{"AmountCheck"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property"},
       \textcolor{stringliteral}{"Amount radio button is checked"})).AmountCheck
00249     rebar.setEditorMode(\textcolor{stringliteral}{"AmountCheck"}, 2)
00250     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"TopCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property"}
      , \textcolor{stringliteral}{"Top cover of rebar"})).TopCover = t\_cover
00251     rebar.setEditorMode(\textcolor{stringliteral}{"TopCover"}, 2)
00252     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"TrueSpacing"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Spacing between of rebars"})).TrueSpacing = amount\_spacing\_value
00253     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyString"}, \textcolor{stringliteral}{"Orientation"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property
      "}, \textcolor{stringliteral}{"Shape of rebar"})).Orientation = orientation
00254     rebar.setEditorMode(\textcolor{stringliteral}{"Orientation"}, 2)
00255     rebar.setEditorMode(\textcolor{stringliteral}{"TrueSpacing"}, 2)
00256     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"BentLength"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"BentLength cover of rebar"})).BentLength = bentLength
00257     rebar.setEditorMode(\textcolor{stringliteral}{"BentLength"}, 2)
00258     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"BentAngle"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property
      "}, \textcolor{stringliteral}{"Bent Angle of rebar"})).BentAngle = bentAngle
00259     rebar.setEditorMode(\textcolor{stringliteral}{"BentAngle"}, 2)
00260 
00261     \textcolor{keywordflow}{if} amount\_spacing\_check:
00262         rebar.AmountCheck = \textcolor{keyword}{True}
00263     \textcolor{keywordflow}{else}:
00264         rebar.AmountCheck = \textcolor{keyword}{False}
00265         rebar.TrueSpacing = amount\_spacing\_value
00266     rebar.Label = \textcolor{stringliteral}{"BentShapeRebar"}
00267     FreeCAD.ActiveDocument.recompute()
00268     \textcolor{keywordflow}{return} rebar
00269 
\hypertarget{BentShapeRebar_8py_source.tex_l00270}{}\hyperlink{namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171}{00270} \textcolor{keyword}{def }\hyperlink{namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171}{editBentShapeRebar}(Rebar, f\_cover, b\_cover, l\_cover, r\_cover, diameter, t\_cover, 
      bentLength, bentAngle, rounding, amount\_spacing\_check, amount\_spacing\_value, orientation, structure = None, 
      facename = None):
00271     sketch = Rebar.Base
00272     \textcolor{keywordflow}{if} structure \textcolor{keywordflow}{and} facename:
00273         sketch.Support = [(structure, facename)]
00274     \textcolor{comment}{# Check if sketch support is empty.}
00275     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} sketch.Support:
00276         \hyperlink{namespaceRebarfunc_a2278a0602d46a62953af1fcf2e574a94}{showWarning}(\textcolor{stringliteral}{"You have checked remove external geometry of base sketchs when needed.\(\backslash\)nTo
       unchecked Edit->Preferences->Arch."})
00277         \textcolor{keywordflow}{return}
00278     \textcolor{comment}{# Assigned values}
00279     facename = sketch.Support[0][1][0]
00280     structure = sketch.Support[0][0]
00281     face = structure.Shape.Faces[\hyperlink{namespaceRebarfunc_a3885b3b63e3a41508ac79bc7550cf301}{getFaceNumber}(facename) - 1]
00282     \textcolor{comment}{#StructurePRM = getTrueParametersOfStructure(structure)}
00283     \textcolor{comment}{# Get parameters of the face where sketch of rebar is drawn}
00284     FacePRM = \hyperlink{namespaceRebarfunc_a92122b3d7cedd3d47bb63380a5ac4d08}{getParametersOfFace}(structure, facename)
00285     \textcolor{comment}{# Get points of L-Shape rebar}
00286     points = \hyperlink{namespaceBentShapeRebar_a33951a8ab21a73bae42af9f81d7c43c3}{getpointsOfBentShapeRebar}(FacePRM, l\_cover, r\_cover, b\_cover, t\_cover
      , bentLength, bentAngle, orientation)
00287     sketch.movePoint(0, 1, points[0], 0)
00288     FreeCAD.ActiveDocument.recompute()
00289     sketch.movePoint(0, 2, points[1], 0)
00290     FreeCAD.ActiveDocument.recompute()
00291     sketch.movePoint(1, 1, points[1], 0)
00292     FreeCAD.ActiveDocument.recompute()
00293     sketch.movePoint(1, 2, points[2], 0)
00294     FreeCAD.ActiveDocument.recompute()
00295 
00296     sketch.movePoint(2, 1, points[2], 0)
00297     FreeCAD.ActiveDocument.recompute()
00298     sketch.movePoint(2, 2, points[3], 0)
00299     FreeCAD.ActiveDocument.recompute()
00300     sketch.movePoint(3, 1, points[3], 0)
00301     FreeCAD.ActiveDocument.recompute()
00302     sketch.movePoint(3, 2, points[4], 0)
00303     FreeCAD.ActiveDocument.recompute()
00304 
00305     sketch.movePoint(4, 1, points[4], 0)
00306     FreeCAD.ActiveDocument.recompute()
00307     sketch.movePoint(4, 2, points[5], 0)
00308     FreeCAD.ActiveDocument.recompute()
00309 
00310     Rebar.OffsetStart = f\_cover
00311     Rebar.OffsetEnd = f\_cover
00312     \textcolor{keywordflow}{if} amount\_spacing\_check:
00313         Rebar.Amount = amount\_spacing\_value
00314         FreeCAD.ActiveDocument.recompute()
00315         Rebar.AmountCheck = \textcolor{keyword}{True}
00316     \textcolor{keywordflow}{else}:
00317         size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length
00318         Rebar.Amount = int((size - diameter) / amount\_spacing\_value)
00319         FreeCAD.ActiveDocument.recompute()
00320         Rebar.AmountCheck = \textcolor{keyword}{False}
00321     Rebar.Diameter = diameter
00322     Rebar.FrontCover = f\_cover
00323     Rebar.LeftCover = l\_cover
00324     Rebar.RightCover = r\_cover
00325     Rebar.BottomCover = b\_cover
00326     Rebar.TopCover = t\_cover
00327     Rebar.BentLength = bentLength
00328     Rebar.BentAngle = bentAngle
00329     Rebar.Rounding = rounding
00330     Rebar.TrueSpacing = amount\_spacing\_value
00331     Rebar.Orientation = orientation
00332     FreeCAD.ActiveDocument.recompute()
00333     \textcolor{keywordflow}{return} Rebar
00334 
\hypertarget{BentShapeRebar_8py_source.tex_l00335}{}\hyperlink{namespaceBentShapeRebar_ae5db82a49148a0a8f6fa567fa72d93b2}{00335} \textcolor{keyword}{def }\hyperlink{namespaceBentShapeRebar_ae5db82a49148a0a8f6fa567fa72d93b2}{editDialog}(vobj):
00336     FreeCADGui.Control.closeDialog()
00337     obj = \hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel}{\_BentShapeRebarTaskPanel}(vobj.Object)
00338     obj.form.frontCover.setText(str(vobj.Object.FrontCover))
00339     obj.form.l\_sideCover.setText(str(vobj.Object.LeftCover))
00340     obj.form.r\_sideCover.setText(str(vobj.Object.RightCover))
00341     obj.form.bottomCover.setText(str(vobj.Object.BottomCover))
00342     obj.form.diameter.setText(str(vobj.Object.Diameter))
00343     obj.form.topCover.setText(str(vobj.Object.TopCover))
00344     obj.form.bentLength.setText(str(vobj.Object.BentLength))
00345     obj.form.bentAngle.setValue(vobj.Object.BentAngle)
00346     obj.form.rounding.setValue(vobj.Object.Rounding)
00347     obj.form.orientation.setCurrentIndex(obj.form.orientation.findText(str(vobj.Object.Orientation)))
00348     \textcolor{keywordflow}{if} vobj.Object.AmountCheck:
00349         obj.form.amount.setValue(vobj.Object.Amount)
00350     \textcolor{keywordflow}{else}:
00351         obj.form.amount\_radio.setChecked(\textcolor{keyword}{False})
00352         obj.form.spacing\_radio.setChecked(\textcolor{keyword}{True})
00353         obj.form.amount.setDisabled(\textcolor{keyword}{True})
00354         obj.form.spacing.setEnabled(\textcolor{keyword}{True})
00355         obj.form.spacing.setText(str(vobj.Object.TrueSpacing))
00356     \textcolor{comment}{#obj.form.PickSelectedFace.setVisible(False)}
00357     FreeCADGui.Control.showDialog(obj)
00358 
\hypertarget{BentShapeRebar_8py_source.tex_l00359}{}\hyperlink{namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37}{00359} \textcolor{keyword}{def }\hyperlink{namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37}{CommandBentShapeRebar}():
00360     selected\_obj = \hyperlink{namespaceRebarfunc_adae2713855a7e1b4bda04081ae671542}{check\_selected\_face}()
00361     \textcolor{keywordflow}{if} selected\_obj:
00362         FreeCADGui.Control.showDialog(\hyperlink{classBentShapeRebar_1_1__BentShapeRebarTaskPanel}{\_BentShapeRebarTaskPanel}())
\end{DoxyCode}
