\hypertarget{LShapeRebar_8py_source}{}\section{L\+Shape\+Rebar.\+py}

\begin{DoxyCode}
\hypertarget{LShapeRebar_8py_source.tex_l00001}{}\hyperlink{namespaceLShapeRebar}{00001} \textcolor{comment}{# -*- coding: utf-8 -*-}
00002 \textcolor{comment}{# ***************************************************************************}
00003 \textcolor{comment}{# *                                                                         *}
00004 \textcolor{comment}{# *   Copyright (c) 2017 - Amritpal Singh <amrit3701@gmail.com>             *}
00005 \textcolor{comment}{# *                                                                         *}
00006 \textcolor{comment}{# *   This program is free software; you can redistribute it and/or modify  *}
00007 \textcolor{comment}{# *   it under the terms of the GNU Lesser General Public License (LGPL)    *}
00008 \textcolor{comment}{# *   as published by the Free Software Foundation; either version 2 of     *}
00009 \textcolor{comment}{# *   the License, or (at your option) any later version.                   *}
00010 \textcolor{comment}{# *   for detail see the LICENCE text file.                                 *}
00011 \textcolor{comment}{# *                                                                         *}
00012 \textcolor{comment}{# *   This program is distributed in the hope that it will be useful,       *}
00013 \textcolor{comment}{# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *}
00014 \textcolor{comment}{# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *}
00015 \textcolor{comment}{# *   GNU Library General Public License for more details.                  *}
00016 \textcolor{comment}{# *                                                                         *}
00017 \textcolor{comment}{# *   You should have received a copy of the GNU Library General Public     *}
00018 \textcolor{comment}{# *   License along with this program; if not, write to the Free Software   *}
00019 \textcolor{comment}{# *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *}
00020 \textcolor{comment}{# *   USA                                                                   *}
00021 \textcolor{comment}{# *                                                                         *}
00022 \textcolor{comment}{# ***************************************************************************}
00023 
\hypertarget{LShapeRebar_8py_source.tex_l00024}{}\hyperlink{namespaceLShapeRebar_a0ac8e9cb97e560c6ce362c1ac5144c31}{00024} \_\_title\_\_ = \textcolor{stringliteral}{"LShapeRebar"}
\hypertarget{LShapeRebar_8py_source.tex_l00025}{}\hyperlink{namespaceLShapeRebar_ad398517c2df8a455dfd0b670e54285ea}{00025} \_\_author\_\_ = \textcolor{stringliteral}{"Amritpal Singh"}
\hypertarget{LShapeRebar_8py_source.tex_l00026}{}\hyperlink{namespaceLShapeRebar_a7bca929f0dda68928d1f3978b4e877f8}{00026} \_\_url\_\_ = \textcolor{stringliteral}{"https://www.freecadweb.org"}
00027 
00028 \textcolor{keyword}{from} PySide \textcolor{keyword}{import} QtCore, QtGui
00029 \textcolor{keyword}{from} Rebarfunc \textcolor{keyword}{import} *
00030 \textcolor{keyword}{from} PySide.QtCore \textcolor{keyword}{import} QT\_TRANSLATE\_NOOP
00031 \textcolor{keyword}{from} RebarDistribution \textcolor{keyword}{import} runRebarDistribution, removeRebarDistribution
00032 \textcolor{keyword}{from} PopUpImage \textcolor{keyword}{import} showPopUpImageDialog
00033 \textcolor{keyword}{import} FreeCAD
00034 \textcolor{keyword}{import} FreeCADGui
00035 \textcolor{keyword}{import} ArchCommands
00036 \textcolor{keyword}{import} os
00037 \textcolor{keyword}{import} sys
00038 \textcolor{keyword}{import} math
00039 
\hypertarget{LShapeRebar_8py_source.tex_l00040}{}\hyperlink{namespaceLShapeRebar_a3019960c6f6476cb70df9ee06f330dfb}{00040} \textcolor{keyword}{def }\hyperlink{namespaceLShapeRebar_a3019960c6f6476cb70df9ee06f330dfb}{getpointsOfLShapeRebar}(FacePRM, l\_cover, r\_cover, b\_cover, t\_cover, orientation):
00041     \textcolor{stringliteral}{""" getpointsOfLShapeRebar(FacePRM, LeftCover, RightCover, BottomCover, TopCover, Orientation):}
00042 \textcolor{stringliteral}{    Return points of the LShape rebar in the form of array for sketch.}
00043 \textcolor{stringliteral}{    It takes four different orientations input i.e. 'Bottom Left', 'Bottom Right ', 'Top Left', 'Top Right'
      .}
00044 \textcolor{stringliteral}{    """}
00045     \textcolor{keywordflow}{if} orientation == \textcolor{stringliteral}{"Bottom Left"}:
00046         x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00047         y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00048         x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00049         y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover
00050         x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r\_cover
00051         y3 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover
00052     \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Bottom Right"}:
00053         x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r\_cover
00054         y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00055         x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r\_cover
00056         y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover
00057         x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00058         y3 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover
00059     \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Top Left"}:
00060         x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00061         y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover
00062         x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00063         y2 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00064         x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r\_cover
00065         y3 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00066     \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Top Right"}:
00067         x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r\_cover
00068         y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + b\_cover
00069         x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r\_cover
00070         y2 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00071         x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + l\_cover
00072         y3 = FacePRM[1][1] + FacePRM[0][1] / 2 - t\_cover
00073     \textcolor{keywordflow}{return} [FreeCAD.Vector(x1, y1, 0), FreeCAD.Vector(x2, y2, 0),\(\backslash\)
00074            FreeCAD.Vector(x3, y3, 0)]
00075 
\hypertarget{LShapeRebar_8py_source.tex_l00076}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel}{00076} \textcolor{keyword}{class }\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel}{\_LShapeRebarTaskPanel}:
\hypertarget{LShapeRebar_8py_source.tex_l00077}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_af6a5f985af6f167b2817f873aa983cbf}{00077}     \textcolor{keyword}{def }\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_af6a5f985af6f167b2817f873aa983cbf}{\_\_init\_\_}(self, Rebar = None):
\hypertarget{LShapeRebar_8py_source.tex_l00078}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_abfd2b9b6897806fd5d69316ca7f2d687}{00078}         self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_abfd2b9b6897806fd5d69316ca7f2d687}{CustomSpacing} = \textcolor{keywordtype}{None}
00079         \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} Rebar:
00080             selected\_obj = FreeCADGui.Selection.getSelectionEx()[0]
\hypertarget{LShapeRebar_8py_source.tex_l00081}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a71f1ee825528164c18315a0234f6da5d}{00081}             self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a71f1ee825528164c18315a0234f6da5d}{SelectedObj} = selected\_obj.Object
\hypertarget{LShapeRebar_8py_source.tex_l00082}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f624818baf68844984b3368f27dc421}{00082}             self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f624818baf68844984b3368f27dc421}{FaceName} = selected\_obj.SubElementNames[0]
00083         \textcolor{keywordflow}{else}:
00084             self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f624818baf68844984b3368f27dc421}{FaceName} = Rebar.Base.Support[0][1][0]
00085             self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a71f1ee825528164c18315a0234f6da5d}{SelectedObj} = Rebar.Base.Support[0][0]
\hypertarget{LShapeRebar_8py_source.tex_l00086}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_af6e6f9deafab993e53dabc404d832bef}{00086}         self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_af6e6f9deafab993e53dabc404d832bef}{form} = FreeCADGui.PySideUic.loadUi(os.path.splitext(\_\_file\_\_)[0] + \textcolor{stringliteral}{".ui"})
00087         self.form.setWindowTitle(QtGui.QApplication.translate(\textcolor{stringliteral}{"RebarAddon"}, \textcolor{stringliteral}{"L-Shape Rebar"}, \textcolor{keywordtype}{None}))
00088         self.form.orientation.addItems([\textcolor{stringliteral}{"Bottom Right"}, \textcolor{stringliteral}{"Bottom Left"}, \textcolor{stringliteral}{"Top Right"}, \textcolor{stringliteral}{"Top Left"}])
00089         self.form.amount\_radio.clicked.connect(self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a81791eac05be58c6df27977089106a0f}{amount\_radio\_clicked})
00090         self.form.spacing\_radio.clicked.connect(self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a96a085e4b791b00a372b66ea558c440e}{spacing\_radio\_clicked})
00091         self.form.customSpacing.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespaceRebarDistribution_aa547df5cb10d2e64eaa0b51c445fa30b}{runRebarDistribution}(self))
00092         self.form.removeCustomSpacing.clicked.connect(\textcolor{keyword}{lambda}: 
      \hyperlink{namespaceRebarDistribution_a85270a1b6e8c782a9e0ba54add518f2a}{removeRebarDistribution}(self))
00093         self.form.PickSelectedFace.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespaceRebarfunc_a8c003df49ac5f249bd9ea4acfb7d2f8d}{getSelectedFace}(self))
00094         self.form.orientation.currentIndexChanged.connect(self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a1e13b2224b0ea68b9519c094004087ae}{getOrientation})
00095         self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/LShapeRebarBR.svg"}))
00096         self.form.toolButton.setIcon(self.form.toolButton.style().standardIcon(
      QtGui.QStyle.SP\_DialogHelpButton))
00097         self.form.toolButton.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespacePopUpImage_a8c565620d7de9b4882a44eacb870ad05}{showPopUpImageDialog}(os.path.split
      (os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"/icons/LShapeRebarDetailed.svg"}))
\hypertarget{LShapeRebar_8py_source.tex_l00098}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4a64ebfb73de83fd42f3a349272e69c7}{00098}         self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4a64ebfb73de83fd42f3a349272e69c7}{Rebar} = Rebar
00099 
\hypertarget{LShapeRebar_8py_source.tex_l00100}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a1e13b2224b0ea68b9519c094004087ae}{00100}     \textcolor{keyword}{def }\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a1e13b2224b0ea68b9519c094004087ae}{getOrientation}(self):
00101         orientation = self.form.orientation.currentText()
00102         \textcolor{keywordflow}{if} orientation == \textcolor{stringliteral}{"Bottom Right"}:
00103             self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/LShapeRebarBR.svg"}))
00104         \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Bottom Left"}:
00105             self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/LShapeRebarBL.svg"}))
00106         \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Top Right"}:
00107             self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/LShapeRebarTR.svg"}))
00108         \textcolor{keywordflow}{else}:
00109             self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/LShapeRebarTL.svg"}))
00110 
\hypertarget{LShapeRebar_8py_source.tex_l00111}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f2f249515b279322dfeeab94cd4395b}{00111}     \textcolor{keyword}{def }\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f2f249515b279322dfeeab94cd4395b}{getStandardButtons}(self):
00112         \textcolor{keywordflow}{return} int(QtGui.QDialogButtonBox.Ok) | int(QtGui.QDialogButtonBox.Apply) | int(
      QtGui.QDialogButtonBox.Cancel)
00113 
\hypertarget{LShapeRebar_8py_source.tex_l00114}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_ac477e2a29da1e0ac71bf2d3aa1e50c4f}{00114}     \textcolor{keyword}{def }\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_ac477e2a29da1e0ac71bf2d3aa1e50c4f}{clicked}(self, button):
00115         \textcolor{keywordflow}{if} button == int(QtGui.QDialogButtonBox.Apply):
00116             self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4d62ad224c06875ec721ba9acbdea774}{accept}(button)
00117 
\hypertarget{LShapeRebar_8py_source.tex_l00118}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4d62ad224c06875ec721ba9acbdea774}{00118}     \textcolor{keyword}{def }\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4d62ad224c06875ec721ba9acbdea774}{accept}(self, signal = None):
00119         f\_cover = self.form.frontCover.text()
00120         f\_cover = FreeCAD.Units.Quantity(f\_cover).Value
00121         b\_cover = self.form.bottomCover.text()
00122         b\_cover = FreeCAD.Units.Quantity(b\_cover).Value
00123         l\_cover = self.form.l\_sideCover.text()
00124         l\_cover = FreeCAD.Units.Quantity(l\_cover).Value
00125         r\_cover = self.form.r\_sideCover.text()
00126         r\_cover = FreeCAD.Units.Quantity(r\_cover).Value
00127         t\_cover = self.form.topCover.text()
00128         t\_cover = FreeCAD.Units.Quantity(t\_cover).Value
00129         diameter = self.form.diameter.text()
00130         diameter = FreeCAD.Units.Quantity(diameter).Value
00131         rounding = self.form.rounding.value()
00132         orientation = self.form.orientation.currentText()
00133         amount\_check = self.form.amount\_radio.isChecked()
00134         spacing\_check = self.form.spacing\_radio.isChecked()
00135         \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4a64ebfb73de83fd42f3a349272e69c7}{Rebar}:
00136             \textcolor{keywordflow}{if} amount\_check:
00137                 amount = self.form.amount.value()
00138                 rebar = \hyperlink{namespaceLShapeRebar_a647a28e94933108c6617da8532d76998}{makeLShapeRebar}(f\_cover, b\_cover, l\_cover, r\_cover, diameter, 
      t\_cover, rounding, \textcolor{keyword}{True}, amount, orientation, self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a71f1ee825528164c18315a0234f6da5d}{SelectedObj}, self.
      \hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f624818baf68844984b3368f27dc421}{FaceName})
00139             \textcolor{keywordflow}{elif} spacing\_check:
00140                 spacing = self.form.spacing.text()
00141                 spacing = FreeCAD.Units.Quantity(spacing).Value
00142                 rebar = \hyperlink{namespaceLShapeRebar_a647a28e94933108c6617da8532d76998}{makeLShapeRebar}(f\_cover, b\_cover, l\_cover, r\_cover, diameter, 
      t\_cover, rounding, \textcolor{keyword}{False}, spacing, orientation, self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a71f1ee825528164c18315a0234f6da5d}{SelectedObj}, self.
      \hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f624818baf68844984b3368f27dc421}{FaceName})
00143         \textcolor{keywordflow}{else}:
00144             \textcolor{keywordflow}{if} amount\_check:
00145                 amount = self.form.amount.value()
00146                 rebar = \hyperlink{namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486}{editLShapeRebar}(self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4a64ebfb73de83fd42f3a349272e69c7}{Rebar}, f\_cover, b\_cover, l\_cover, r\_cover,
       diameter, t\_cover, rounding, \textcolor{keyword}{True}, amount, orientation, self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a71f1ee825528164c18315a0234f6da5d}{SelectedObj}, self.
      \hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f624818baf68844984b3368f27dc421}{FaceName})
00147             \textcolor{keywordflow}{elif} spacing\_check:
00148                 spacing = self.form.spacing.text()
00149                 spacing = FreeCAD.Units.Quantity(spacing).Value
00150                 rebar = \hyperlink{namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486}{editLShapeRebar}(self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4a64ebfb73de83fd42f3a349272e69c7}{Rebar}, f\_cover, b\_cover, l\_cover, r\_cover,
       diameter, t\_cover, rounding, \textcolor{keyword}{False}, spacing, orientation, self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a71f1ee825528164c18315a0234f6da5d}{SelectedObj}, self.
      \hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a8f624818baf68844984b3368f27dc421}{FaceName})
00151         \textcolor{keywordflow}{if} self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_abfd2b9b6897806fd5d69316ca7f2d687}{CustomSpacing}:
00152             rebar.CustomSpacing = self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_abfd2b9b6897806fd5d69316ca7f2d687}{CustomSpacing}
00153             FreeCAD.ActiveDocument.recompute()
00154         self.\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a4a64ebfb73de83fd42f3a349272e69c7}{Rebar} = rebar
00155         \textcolor{keywordflow}{if} signal == int(QtGui.QDialogButtonBox.Apply):
00156             \textcolor{keywordflow}{pass}
00157         \textcolor{keywordflow}{else}:
00158             FreeCADGui.Control.closeDialog(self)
00159 
\hypertarget{LShapeRebar_8py_source.tex_l00160}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a81791eac05be58c6df27977089106a0f}{00160}     \textcolor{keyword}{def }\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a81791eac05be58c6df27977089106a0f}{amount\_radio\_clicked}(self):
00161         self.form.spacing.setEnabled(\textcolor{keyword}{False})
00162         self.form.amount.setEnabled(\textcolor{keyword}{True})
00163 
\hypertarget{LShapeRebar_8py_source.tex_l00164}{}\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a96a085e4b791b00a372b66ea558c440e}{00164}     \textcolor{keyword}{def }\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel_a96a085e4b791b00a372b66ea558c440e}{spacing\_radio\_clicked}(self):
00165         self.form.amount.setEnabled(\textcolor{keyword}{False})
00166         self.form.spacing.setEnabled(\textcolor{keyword}{True})
00167 
00168 
\hypertarget{LShapeRebar_8py_source.tex_l00169}{}\hyperlink{namespaceLShapeRebar_a647a28e94933108c6617da8532d76998}{00169} \textcolor{keyword}{def }\hyperlink{namespaceLShapeRebar_a647a28e94933108c6617da8532d76998}{makeLShapeRebar}(f\_cover, b\_cover, l\_cover, r\_cover, diameter, t\_cover, rounding, 
      amount\_spacing\_check, amount\_spacing\_value, orientation = "Bottom Left", structure = None, facename = None):
00170     \textcolor{stringliteral}{""" makeLShapeRebar(FrontCover, BottomCover, LeftCover, RightCover, Diameter, TopCover, Rounding,
       AmountSpacingCheck, AmountSpacingValue,}
00171 \textcolor{stringliteral}{    Orientation, Structure, Facename): Adds the L-Shape reinforcement bar to the selected structural
       object.}
00172 \textcolor{stringliteral}{    It takes four different orientations input i.e. 'Bottom Left', 'Bottom Right ', 'Top Left', 'Top Right'
      .}
00173 \textcolor{stringliteral}{    """}
00174     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} structure \textcolor{keywordflow}{and} \textcolor{keywordflow}{not} facename:
00175         selected\_obj = FreeCADGui.Selection.getSelectionEx()[0]
00176         structure = selected\_obj.Object
00177         facename = selected\_obj.SubElementNames[0]
00178     face = structure.Shape.Faces[\hyperlink{namespaceRebarfunc_a3885b3b63e3a41508ac79bc7550cf301}{getFaceNumber}(facename) - 1]
00179     \textcolor{comment}{#StructurePRM = getTrueParametersOfStructure(structure)}
00180     FacePRM = \hyperlink{namespaceRebarfunc_a92122b3d7cedd3d47bb63380a5ac4d08}{getParametersOfFace}(structure, facename)
00181     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} FacePRM:
00182         FreeCAD.Console.PrintError(\textcolor{stringliteral}{"Cannot identified shape or from which base object sturctural element is
       derived\(\backslash\)n"})
00183         \textcolor{keywordflow}{return}
00184     \textcolor{comment}{# Get points of L-Shape rebar}
00185     points = \hyperlink{namespaceLShapeRebar_a3019960c6f6476cb70df9ee06f330dfb}{getpointsOfLShapeRebar}(FacePRM, l\_cover, r\_cover, b\_cover, t\_cover, 
      orientation)
00186     \textcolor{keyword}{import} Part
00187     \textcolor{keyword}{import} Arch
00188     sketch = FreeCAD.activeDocument().addObject(\textcolor{stringliteral}{'Sketcher::SketchObject'}, \textcolor{stringliteral}{'Sketch'})
00189     sketch.MapMode = \textcolor{stringliteral}{"FlatFace"}
00190     sketch.Support = [(structure, facename)]
00191     FreeCAD.ActiveDocument.recompute()
00192     sketch.addGeometry(Part.LineSegment(points[0], points[1]), \textcolor{keyword}{False})
00193     sketch.addGeometry(Part.LineSegment(points[1], points[2]), \textcolor{keyword}{False})
00194     \textcolor{keyword}{import} Sketcher
00195     \textcolor{keywordflow}{if} amount\_spacing\_check:
00196         rebar = Arch.makeRebar(structure, sketch, diameter, amount\_spacing\_value, f\_cover)
00197         FreeCAD.ActiveDocument.recompute()
00198     \textcolor{keywordflow}{else}:
00199         size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length
00200         rebar = Arch.makeRebar(structure, sketch, diameter, int((size - diameter) / amount\_spacing\_value), 
      f\_cover)
00201     rebar.Rounding = rounding
00202     \textcolor{comment}{# Adds properties to the rebar object}
00203     rebar.ViewObject.addProperty(\textcolor{stringliteral}{"App::PropertyString"}, \textcolor{stringliteral}{"RebarShape"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Shape of rebar"})).RebarShape = \textcolor{stringliteral}{"LShapeRebar"}
00204     rebar.ViewObject.setEditorMode(\textcolor{stringliteral}{"RebarShape"}, 2)
00205     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"FrontCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Front cover of rebar"})).FrontCover = f\_cover
00206     rebar.setEditorMode(\textcolor{stringliteral}{"FrontCover"}, 2)
00207     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"LeftCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property
      "}, \textcolor{stringliteral}{"Left Side cover of rebar"})).LeftCover = l\_cover
00208     rebar.setEditorMode(\textcolor{stringliteral}{"LeftCover"}, 2)
00209     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"RightCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Right Side cover of rebar"})).RightCover = r\_cover
00210     rebar.setEditorMode(\textcolor{stringliteral}{"RightCover"}, 2)
00211     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"BottomCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Bottom cover of rebar"})).BottomCover = b\_cover
00212     rebar.setEditorMode(\textcolor{stringliteral}{"BottomCover"}, 2)
00213     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyBool"}, \textcolor{stringliteral}{"AmountCheck"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property"},
       \textcolor{stringliteral}{"Amount radio button is checked"})).AmountCheck
00214     rebar.setEditorMode(\textcolor{stringliteral}{"AmountCheck"}, 2)
00215     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"TopCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property"}
      , \textcolor{stringliteral}{"Top cover of rebar"})).TopCover = t\_cover
00216     rebar.setEditorMode(\textcolor{stringliteral}{"TopCover"}, 2)
00217     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"TrueSpacing"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Spacing between of rebars"})).TrueSpacing = amount\_spacing\_value
00218     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyString"}, \textcolor{stringliteral}{"Orientation"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property
      "}, \textcolor{stringliteral}{"Shape of rebar"})).Orientation = orientation
00219     rebar.setEditorMode(\textcolor{stringliteral}{"Orientation"}, 2)
00220     rebar.setEditorMode(\textcolor{stringliteral}{"TrueSpacing"}, 2)
00221     \textcolor{keywordflow}{if} amount\_spacing\_check:
00222         rebar.AmountCheck = \textcolor{keyword}{True}
00223     \textcolor{keywordflow}{else}:
00224         rebar.AmountCheck = \textcolor{keyword}{False}
00225         rebar.TrueSpacing = amount\_spacing\_value
00226     rebar.Label = \textcolor{stringliteral}{"LShapeRebar"}
00227     FreeCAD.ActiveDocument.recompute()
00228     \textcolor{keywordflow}{return} rebar
00229 
\hypertarget{LShapeRebar_8py_source.tex_l00230}{}\hyperlink{namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486}{00230} \textcolor{keyword}{def }\hyperlink{namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486}{editLShapeRebar}(Rebar, f\_cover, b\_cover, l\_cover, r\_cover, diameter, t\_cover, rounding, 
      amount\_spacing\_check, amount\_spacing\_value, orientation, structure = None, facename = None):
00231     sketch = Rebar.Base
00232     \textcolor{keywordflow}{if} structure \textcolor{keywordflow}{and} facename:
00233         sketch.Support = [(structure, facename)]
00234     \textcolor{comment}{# Check if sketch support is empty.}
00235     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} sketch.Support:
00236         \hyperlink{namespaceRebarfunc_a2278a0602d46a62953af1fcf2e574a94}{showWarning}(\textcolor{stringliteral}{"You have checked remove external geometry of base sketchs when needed.\(\backslash\)nTo
       unchecked Edit->Preferences->Arch."})
00237         \textcolor{keywordflow}{return}
00238     \textcolor{comment}{# Assigned values}
00239     facename = sketch.Support[0][1][0]
00240     structure = sketch.Support[0][0]
00241     face = structure.Shape.Faces[\hyperlink{namespaceRebarfunc_a3885b3b63e3a41508ac79bc7550cf301}{getFaceNumber}(facename) - 1]
00242     \textcolor{comment}{#StructurePRM = getTrueParametersOfStructure(structure)}
00243     \textcolor{comment}{# Get parameters of the face where sketch of rebar is drawn}
00244     FacePRM = \hyperlink{namespaceRebarfunc_a92122b3d7cedd3d47bb63380a5ac4d08}{getParametersOfFace}(structure, facename)
00245     \textcolor{comment}{# Get points of L-Shape rebar}
00246     points = \hyperlink{namespaceLShapeRebar_a3019960c6f6476cb70df9ee06f330dfb}{getpointsOfLShapeRebar}(FacePRM, l\_cover, r\_cover, b\_cover, t\_cover, 
      orientation)
00247     sketch.movePoint(0, 1, points[0], 0)
00248     FreeCAD.ActiveDocument.recompute()
00249     sketch.movePoint(0, 2, points[1], 0)
00250     FreeCAD.ActiveDocument.recompute()
00251     sketch.movePoint(1, 1, points[1], 0)
00252     FreeCAD.ActiveDocument.recompute()
00253     sketch.movePoint(1, 2, points[2], 0)
00254     FreeCAD.ActiveDocument.recompute()
00255     Rebar.OffsetStart = f\_cover
00256     Rebar.OffsetEnd = f\_cover
00257     \textcolor{keywordflow}{if} amount\_spacing\_check:
00258         Rebar.Amount = amount\_spacing\_value
00259         FreeCAD.ActiveDocument.recompute()
00260         Rebar.AmountCheck = \textcolor{keyword}{True}
00261     \textcolor{keywordflow}{else}:
00262         size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length
00263         Rebar.Amount = int((size - diameter) / amount\_spacing\_value)
00264         FreeCAD.ActiveDocument.recompute()
00265         Rebar.AmountCheck = \textcolor{keyword}{False}
00266     Rebar.Diameter = diameter
00267     Rebar.FrontCover = f\_cover
00268     Rebar.LeftCover = l\_cover
00269     Rebar.RightCover = r\_cover
00270     Rebar.BottomCover = b\_cover
00271     Rebar.TopCover = t\_cover
00272     Rebar.Rounding = rounding
00273     Rebar.TrueSpacing = amount\_spacing\_value
00274     Rebar.Orientation = orientation
00275     FreeCAD.ActiveDocument.recompute()
00276     \textcolor{keywordflow}{return} Rebar
00277 
\hypertarget{LShapeRebar_8py_source.tex_l00278}{}\hyperlink{namespaceLShapeRebar_a73f1b8d577fecf230a8c071424b2015e}{00278} \textcolor{keyword}{def }\hyperlink{namespaceLShapeRebar_a73f1b8d577fecf230a8c071424b2015e}{editDialog}(vobj):
00279     FreeCADGui.Control.closeDialog()
00280     obj = \hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel}{\_LShapeRebarTaskPanel}(vobj.Object)
00281     obj.form.frontCover.setText(str(vobj.Object.FrontCover))
00282     obj.form.l\_sideCover.setText(str(vobj.Object.LeftCover))
00283     obj.form.r\_sideCover.setText(str(vobj.Object.RightCover))
00284     obj.form.bottomCover.setText(str(vobj.Object.BottomCover))
00285     obj.form.diameter.setText(str(vobj.Object.Diameter))
00286     obj.form.topCover.setText(str(vobj.Object.TopCover))
00287     obj.form.rounding.setValue(vobj.Object.Rounding)
00288     obj.form.orientation.setCurrentIndex(obj.form.orientation.findText(str(vobj.Object.Orientation)))
00289     \textcolor{keywordflow}{if} vobj.Object.AmountCheck:
00290         obj.form.amount.setValue(vobj.Object.Amount)
00291     \textcolor{keywordflow}{else}:
00292         obj.form.amount\_radio.setChecked(\textcolor{keyword}{False})
00293         obj.form.spacing\_radio.setChecked(\textcolor{keyword}{True})
00294         obj.form.amount.setDisabled(\textcolor{keyword}{True})
00295         obj.form.spacing.setEnabled(\textcolor{keyword}{True})
00296         obj.form.spacing.setText(str(vobj.Object.TrueSpacing))
00297     \textcolor{comment}{#obj.form.PickSelectedFace.setVisible(False)}
00298     FreeCADGui.Control.showDialog(obj)
00299 
\hypertarget{LShapeRebar_8py_source.tex_l00300}{}\hyperlink{namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e}{00300} \textcolor{keyword}{def }\hyperlink{namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e}{CommandLShapeRebar}():
00301     selected\_obj = \hyperlink{namespaceRebarfunc_adae2713855a7e1b4bda04081ae671542}{check\_selected\_face}()
00302     \textcolor{keywordflow}{if} selected\_obj:
00303         FreeCADGui.Control.showDialog(\hyperlink{classLShapeRebar_1_1__LShapeRebarTaskPanel}{\_LShapeRebarTaskPanel}())
\end{DoxyCode}
