\hypertarget{StraightRebar_8py_source}{}\section{Straight\+Rebar.\+py}

\begin{DoxyCode}
\hypertarget{StraightRebar_8py_source.tex_l00001}{}\hyperlink{namespaceStraightRebar}{00001} \textcolor{comment}{# -*- coding: utf-8 -*-}
00002 \textcolor{comment}{# ***************************************************************************}
00003 \textcolor{comment}{# *                                                                         *}
00004 \textcolor{comment}{# *   Copyright (c) 2017 - Amritpal Singh <amrit3701@gmail.com>             *}
00005 \textcolor{comment}{# *                                                                         *}
00006 \textcolor{comment}{# *   This program is free software; you can redistribute it and/or modify  *}
00007 \textcolor{comment}{# *   it under the terms of the GNU Lesser General Public License (LGPL)    *}
00008 \textcolor{comment}{# *   as published by the Free Software Foundation; either version 2 of     *}
00009 \textcolor{comment}{# *   the License, or (at your option) any later version.                   *}
00010 \textcolor{comment}{# *   for detail see the LICENCE text file.                                 *}
00011 \textcolor{comment}{# *                                                                         *}
00012 \textcolor{comment}{# *   This program is distributed in the hope that it will be useful,       *}
00013 \textcolor{comment}{# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *}
00014 \textcolor{comment}{# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *}
00015 \textcolor{comment}{# *   GNU Library General Public License for more details.                  *}
00016 \textcolor{comment}{# *                                                                         *}
00017 \textcolor{comment}{# *   You should have received a copy of the GNU Library General Public     *}
00018 \textcolor{comment}{# *   License along with this program; if not, write to the Free Software   *}
00019 \textcolor{comment}{# *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *}
00020 \textcolor{comment}{# *   USA                                                                   *}
00021 \textcolor{comment}{# *                                                                         *}
00022 \textcolor{comment}{# ***************************************************************************}
00023 
\hypertarget{StraightRebar_8py_source.tex_l00024}{}\hyperlink{namespaceStraightRebar_ab1d45eb17133c23d9d6a3e2a6f2abb8a}{00024} \_\_title\_\_ = \textcolor{stringliteral}{"StraightRebar"}
\hypertarget{StraightRebar_8py_source.tex_l00025}{}\hyperlink{namespaceStraightRebar_ad355d40e3bea5e86c24b6fe813264413}{00025} \_\_author\_\_ = \textcolor{stringliteral}{"Amritpal Singh"}
\hypertarget{StraightRebar_8py_source.tex_l00026}{}\hyperlink{namespaceStraightRebar_aebf23f453d8fabed3a611d14f5e7f057}{00026} \_\_url\_\_ = \textcolor{stringliteral}{"https://www.freecadweb.org"}
00027 
00028 \textcolor{keyword}{from} PySide \textcolor{keyword}{import} QtCore, QtGui
00029 \textcolor{keyword}{from} Rebarfunc \textcolor{keyword}{import} *
00030 \textcolor{keyword}{from} PySide.QtCore \textcolor{keyword}{import} QT\_TRANSLATE\_NOOP
00031 \textcolor{keyword}{from} RebarDistribution \textcolor{keyword}{import} runRebarDistribution, removeRebarDistribution
00032 \textcolor{keyword}{from} PopUpImage \textcolor{keyword}{import} showPopUpImageDialog
00033 \textcolor{keyword}{import} FreeCAD
00034 \textcolor{keyword}{import} FreeCADGui
00035 \textcolor{keyword}{import} ArchCommands
00036 \textcolor{keyword}{import} os
00037 \textcolor{keyword}{import} sys
00038 \textcolor{keyword}{import} math
00039 
\hypertarget{StraightRebar_8py_source.tex_l00040}{}\hyperlink{namespaceStraightRebar_a1873c6f7f59b355a64fdd966ad75f778}{00040} \textcolor{keyword}{def }\hyperlink{namespaceStraightRebar_a1873c6f7f59b355a64fdd966ad75f778}{getpointsOfStraightRebar}(FacePRM, rt\_cover, lb\_cover, coverAlong, orientation):
00041     \textcolor{stringliteral}{""" getpointsOfStraightRebar(FacePRM, RightTopcover, LeftBottomcover, CoverAlong, Orientation):}
00042 \textcolor{stringliteral}{    Return points of the Straight rebar in the form of array for sketch.}
00043 \textcolor{stringliteral}{}
00044 \textcolor{stringliteral}{    Case I: When Orientation is 'Horizontal':}
00045 \textcolor{stringliteral}{        We have two option in CoverAlong i.e. 'Bottom Side' or 'Top Side'}
00046 \textcolor{stringliteral}{    Case II: When Orientation is 'Vertical':}
00047 \textcolor{stringliteral}{        We have two option in CoverAlong i.e. 'Left Side' or 'Right Side'}
00048 \textcolor{stringliteral}{    """}
00049     \textcolor{keywordflow}{if} orientation == \textcolor{stringliteral}{"Horizontal"}:
00050         \textcolor{keywordflow}{if} coverAlong[0] == \textcolor{stringliteral}{"Bottom Side"}:
00051             x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + lb\_cover
00052             y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + coverAlong[1]
00053             x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - rt\_cover
00054             y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + coverAlong[1]
00055         \textcolor{keywordflow}{elif} coverAlong[0] == \textcolor{stringliteral}{"Top Side"}:
00056             cover = FacePRM[0][1] - coverAlong[1]
00057             x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + lb\_cover
00058             y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + cover
00059             x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - rt\_cover
00060             y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + cover
00061     \textcolor{keywordflow}{elif} orientation == \textcolor{stringliteral}{"Vertical"}:
00062         \textcolor{keywordflow}{if} coverAlong[0] == \textcolor{stringliteral}{"Left Side"}:
00063             x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + coverAlong[1]
00064             y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + lb\_cover
00065             x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + coverAlong[1]
00066             y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + FacePRM[0][1] - rt\_cover
00067         \textcolor{keywordflow}{elif} coverAlong[0] == \textcolor{stringliteral}{"Right Side"}:
00068             cover = FacePRM[0][0] - coverAlong[1]
00069             x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + cover
00070             y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + lb\_cover
00071             x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + cover
00072             y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + FacePRM[0][1] - rt\_cover
00073     \textcolor{keywordflow}{return} [FreeCAD.Vector(x1, y1, 0), FreeCAD.Vector(x2, y2, 0)]
00074 
\hypertarget{StraightRebar_8py_source.tex_l00075}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel}{00075} \textcolor{keyword}{class }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel}{\_StraightRebarTaskPanel}:
\hypertarget{StraightRebar_8py_source.tex_l00076}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_ad740c5f357b97a2a327e7494bf2b712b}{00076}     \textcolor{keyword}{def }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_ad740c5f357b97a2a327e7494bf2b712b}{\_\_init\_\_}(self, Rebar = None):
\hypertarget{StraightRebar_8py_source.tex_l00077}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a91d60c0007437af93af933a29c66a963}{00077}         self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a91d60c0007437af93af933a29c66a963}{CustomSpacing} = \textcolor{keywordtype}{None}
00078         \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} Rebar:
00079             selected\_obj = FreeCADGui.Selection.getSelectionEx()[0]
\hypertarget{StraightRebar_8py_source.tex_l00080}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a4bdbe85e1cc468f34a907db99faebe85}{00080}             self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a4bdbe85e1cc468f34a907db99faebe85}{SelectedObj} = selected\_obj.Object
\hypertarget{StraightRebar_8py_source.tex_l00081}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_afe733532cc15a149f9ba8f7da4515413}{00081}             self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_afe733532cc15a149f9ba8f7da4515413}{FaceName} = selected\_obj.SubElementNames[0]
00082         \textcolor{keywordflow}{else}:
00083             self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_afe733532cc15a149f9ba8f7da4515413}{FaceName} = Rebar.Base.Support[0][1][0]
00084             self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a4bdbe85e1cc468f34a907db99faebe85}{SelectedObj} = Rebar.Base.Support[0][0]
\hypertarget{StraightRebar_8py_source.tex_l00085}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a88b76fa56bfa51be091abb0cde42a0e0}{00085}         self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a88b76fa56bfa51be091abb0cde42a0e0}{form} = FreeCADGui.PySideUic.loadUi(os.path.splitext(\_\_file\_\_)[0] + \textcolor{stringliteral}{".ui"})
00086         self.form.setWindowTitle(QtGui.QApplication.translate(\textcolor{stringliteral}{"RebarAddon"}, \textcolor{stringliteral}{"Straight Rebar"}, \textcolor{keywordtype}{None}))
00087         self.form.orientation.addItems([\textcolor{stringliteral}{"Horizontal"}, \textcolor{stringliteral}{"Vertical"}])
00088         self.form.coverAlong.addItems([\textcolor{stringliteral}{"Bottom Side"}, \textcolor{stringliteral}{"Top Side"}])
00089         self.form.amount\_radio.clicked.connect(self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a845630e065bb13e756284e71476dd755}{amount\_radio\_clicked})
00090         self.form.spacing\_radio.clicked.connect(self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a03ed1cd992f5b138153b6a45de7777f9}{spacing\_radio\_clicked})
00091         self.form.customSpacing.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespaceRebarDistribution_aa547df5cb10d2e64eaa0b51c445fa30b}{runRebarDistribution}(self))
00092         self.form.removeCustomSpacing.clicked.connect(\textcolor{keyword}{lambda}: 
      \hyperlink{namespaceRebarDistribution_a85270a1b6e8c782a9e0ba54add518f2a}{removeRebarDistribution}(self))
00093         self.form.PickSelectedFace.setCheckable(\textcolor{keyword}{True})
00094         self.form.PickSelectedFace.toggle()
00095         self.form.PickSelectedFace.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespaceRebarfunc_a8c003df49ac5f249bd9ea4acfb7d2f8d}{getSelectedFace}(self))
00096         self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/StraightRebarH.svg"}))
00097         self.form.orientation.currentIndexChanged.connect(self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_abd7abec4d263edf53efb18396857b370}{changeOrientation})
00098         self.form.coverAlong.currentIndexChanged.connect(self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_ae99010cf766375812bf24f80cd3f60e1}{changeCoverAlong})
00099         self.form.toolButton.setIcon(self.form.toolButton.style().standardIcon(
      QtGui.QStyle.SP\_DialogHelpButton))
00100         self.form.toolButton.clicked.connect(\textcolor{keyword}{lambda}: \hyperlink{namespacePopUpImage_a8c565620d7de9b4882a44eacb870ad05}{showPopUpImageDialog}(os.path.split
      (os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"/icons/StraightRebarDetailed.svg"}))
\hypertarget{StraightRebar_8py_source.tex_l00101}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a23fe17475277eae59cbed538f0f183cb}{00101}         self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a23fe17475277eae59cbed538f0f183cb}{Rebar} = Rebar
00102 
\hypertarget{StraightRebar_8py_source.tex_l00103}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_abd7abec4d263edf53efb18396857b370}{00103}     \textcolor{keyword}{def }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_abd7abec4d263edf53efb18396857b370}{changeOrientation}(self):
00104         orientation = self.form.orientation.currentText()
00105         \textcolor{keywordflow}{if} orientation == \textcolor{stringliteral}{"Horizontal"}:
00106             self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/StraightRebarH.svg"}))
00107             self.form.r\_sideCoverLabel.setText(\textcolor{stringliteral}{"Right Side Cover"})
00108             self.form.l\_sideCoverLabel.setText(\textcolor{stringliteral}{"Left Side Cover"})
00109             self.form.coverAlong.clear()
00110             self.form.coverAlong.addItems([\textcolor{stringliteral}{"Bottom Side"}, \textcolor{stringliteral}{"Top Side"}])
00111         \textcolor{keywordflow}{else}:
00112             self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(\_\_file\_\_))[0] + \textcolor{stringliteral}{"
      /icons/StraightRebarV.svg"}))
00113             self.form.r\_sideCoverLabel.setText(\textcolor{stringliteral}{"Top Side Cover"})
00114             self.form.l\_sideCoverLabel.setText(\textcolor{stringliteral}{"Bottom Side Cover"})
00115             self.form.coverAlong.clear()
00116             self.form.coverAlong.addItems([\textcolor{stringliteral}{"Right Side"}, \textcolor{stringliteral}{"Left Side"}])
00117 
\hypertarget{StraightRebar_8py_source.tex_l00118}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_ae99010cf766375812bf24f80cd3f60e1}{00118}     \textcolor{keyword}{def }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_ae99010cf766375812bf24f80cd3f60e1}{changeCoverAlong}(self):
00119         coverAlong = self.form.coverAlong.currentText()
00120         \textcolor{keywordflow}{if} coverAlong == \textcolor{stringliteral}{"Bottom Side"}:
00121             self.form.bottomCoverLabel.setText(\textcolor{stringliteral}{"Bottom Cover"})
00122         \textcolor{keywordflow}{elif} coverAlong == \textcolor{stringliteral}{"Top Side"}:
00123             self.form.bottomCoverLabel.setText(\textcolor{stringliteral}{"Top Cover"})
00124         \textcolor{keywordflow}{elif} coverAlong == \textcolor{stringliteral}{"Right Side"}:
00125             self.form.bottomCoverLabel.setText(\textcolor{stringliteral}{"Right Cover"})
00126         \textcolor{keywordflow}{else}:
00127             self.form.bottomCoverLabel.setText(\textcolor{stringliteral}{"Left Cover"})
00128 
\hypertarget{StraightRebar_8py_source.tex_l00129}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a657fa849f5c787db2303dac9024d8a98}{00129}     \textcolor{keyword}{def }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a657fa849f5c787db2303dac9024d8a98}{getStandardButtons}(self):
00130         \textcolor{keywordflow}{return} int(QtGui.QDialogButtonBox.Ok) | int(QtGui.QDialogButtonBox.Apply) | int(
      QtGui.QDialogButtonBox.Cancel)
00131 
\hypertarget{StraightRebar_8py_source.tex_l00132}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a8190e8acf6121a5fe3b58d968ef17300}{00132}     \textcolor{keyword}{def }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a8190e8acf6121a5fe3b58d968ef17300}{clicked}(self, button):
00133         \textcolor{keywordflow}{if} button == int(QtGui.QDialogButtonBox.Apply):
00134             self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_ad8a49d3d30ef3308b8386c9ebe1b67d8}{accept}(button)
00135 
\hypertarget{StraightRebar_8py_source.tex_l00136}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_ad8a49d3d30ef3308b8386c9ebe1b67d8}{00136}     \textcolor{keyword}{def }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_ad8a49d3d30ef3308b8386c9ebe1b67d8}{accept}(self, signal = None):
00137         f\_cover = self.form.frontCover.text()
00138         f\_cover = FreeCAD.Units.Quantity(f\_cover).Value
00139         cover = self.form.bottomCover.text()
00140         cover = FreeCAD.Units.Quantity(cover).Value
00141         lb\_cover = self.form.l\_sideCover.text()
00142         lb\_cover = FreeCAD.Units.Quantity(lb\_cover).Value
00143         rt\_cover = self.form.r\_sideCover.text()
00144         rt\_cover = FreeCAD.Units.Quantity(rt\_cover).Value
00145         orientation = self.form.orientation.currentText()
00146         coverAlong = self.form.coverAlong.currentText()
00147         diameter = self.form.diameter.text()
00148         diameter = FreeCAD.Units.Quantity(diameter).Value
00149         amount\_check = self.form.amount\_radio.isChecked()
00150         spacing\_check = self.form.spacing\_radio.isChecked()
00151         \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a23fe17475277eae59cbed538f0f183cb}{Rebar}:
00152             \textcolor{keywordflow}{if} amount\_check:
00153                 amount = self.form.amount.value()
00154                 rebar = \hyperlink{namespaceStraightRebar_af6270367d7beae457813e33718d80faf}{makeStraightRebar}(f\_cover, (coverAlong, cover), rt\_cover, lb\_cover
      , diameter, \textcolor{keyword}{True}, amount, orientation, self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a4bdbe85e1cc468f34a907db99faebe85}{SelectedObj}, self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_afe733532cc15a149f9ba8f7da4515413}{FaceName})
00155             \textcolor{keywordflow}{elif} spacing\_check:
00156                 spacing = self.form.spacing.text()
00157                 spacing = FreeCAD.Units.Quantity(spacing).Value
00158                 rebar = \hyperlink{namespaceStraightRebar_af6270367d7beae457813e33718d80faf}{makeStraightRebar}(f\_cover, (coverAlong, cover), rt\_cover, lb\_cover
      , diameter, \textcolor{keyword}{False}, spacing, orientation, self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a4bdbe85e1cc468f34a907db99faebe85}{SelectedObj}, self.
      \hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_afe733532cc15a149f9ba8f7da4515413}{FaceName})
00159         \textcolor{keywordflow}{else}:
00160             \textcolor{keywordflow}{if} amount\_check:
00161                 amount = self.form.amount.value()
00162                 rebar = \hyperlink{namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b}{editStraightRebar}(self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a23fe17475277eae59cbed538f0f183cb}{Rebar}, f\_cover, (coverAlong, cover), 
      rt\_cover, lb\_cover, diameter, \textcolor{keyword}{True}, amount, orientation, self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a4bdbe85e1cc468f34a907db99faebe85}{SelectedObj}, self.
      \hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_afe733532cc15a149f9ba8f7da4515413}{FaceName})
00163             \textcolor{keywordflow}{elif} spacing\_check:
00164                 spacing = self.form.spacing.text()
00165                 spacing = FreeCAD.Units.Quantity(spacing).Value
00166                 rebar = \hyperlink{namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b}{editStraightRebar}(self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a23fe17475277eae59cbed538f0f183cb}{Rebar}, f\_cover, (coverAlong, cover), 
      rt\_cover, lb\_cover, diameter, \textcolor{keyword}{False}, spacing, orientation, self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a4bdbe85e1cc468f34a907db99faebe85}{SelectedObj}, self.
      \hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_afe733532cc15a149f9ba8f7da4515413}{FaceName})
00167         \textcolor{keywordflow}{if} self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a91d60c0007437af93af933a29c66a963}{CustomSpacing}:
00168             rebar.CustomSpacing = self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a91d60c0007437af93af933a29c66a963}{CustomSpacing}
00169             FreeCAD.ActiveDocument.recompute()
00170         self.\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a23fe17475277eae59cbed538f0f183cb}{Rebar} = rebar
00171         \textcolor{keywordflow}{if} signal == int(QtGui.QDialogButtonBox.Apply):
00172             \textcolor{keywordflow}{pass}
00173         \textcolor{keywordflow}{else}:
00174             FreeCADGui.Control.closeDialog(self)
00175 
\hypertarget{StraightRebar_8py_source.tex_l00176}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a845630e065bb13e756284e71476dd755}{00176}     \textcolor{keyword}{def }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a845630e065bb13e756284e71476dd755}{amount\_radio\_clicked}(self):
00177         self.form.spacing.setEnabled(\textcolor{keyword}{False})
00178         self.form.amount.setEnabled(\textcolor{keyword}{True})
00179 
\hypertarget{StraightRebar_8py_source.tex_l00180}{}\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a03ed1cd992f5b138153b6a45de7777f9}{00180}     \textcolor{keyword}{def }\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel_a03ed1cd992f5b138153b6a45de7777f9}{spacing\_radio\_clicked}(self):
00181         self.form.amount.setEnabled(\textcolor{keyword}{False})
00182         self.form.spacing.setEnabled(\textcolor{keyword}{True})
00183 
00184 
\hypertarget{StraightRebar_8py_source.tex_l00185}{}\hyperlink{namespaceStraightRebar_af6270367d7beae457813e33718d80faf}{00185} \textcolor{keyword}{def }\hyperlink{namespaceStraightRebar_af6270367d7beae457813e33718d80faf}{makeStraightRebar}(f\_cover, coverAlong, rt\_cover, lb\_cover, diameter, 
      amount\_spacing\_check, amount\_spacing\_value, orientation = "Horizontal", structure = None, facename = None):
00186     \textcolor{stringliteral}{""" Adds the straight reinforcement bar to the selected structural object.}
00187 \textcolor{stringliteral}{}
00188 \textcolor{stringliteral}{    Case I: When orientation of straight rebar is 'Horizontal':}
00189 \textcolor{stringliteral}{        makeStraightRebar(FrontCover, CoverAlong, RightCover, LeftCover, Diameter, AmountSpacingCheck,
       AmountSpacingValue, Orientation = "Horizontal",}
00190 \textcolor{stringliteral}{        Structure, Facename)}
00191 \textcolor{stringliteral}{        Note: Type of CoverAlong argument is a tuple. Syntax: (<Along>, <Value>). Here we have horizontal
       orientation so we can pass Top Side}
00192 \textcolor{stringliteral}{        and Bottom Side to <Along> arguments.}
00193 \textcolor{stringliteral}{        For eg. ("Top Side", 20) and ("Bottom Side", 20)}
00194 \textcolor{stringliteral}{}
00195 \textcolor{stringliteral}{    Case II: When orientation of straight rebar is 'Vertical':}
00196 \textcolor{stringliteral}{        makeStraightRebar(FrontCover, CoverAlong, TopCover, BottomCover, Diameter, AmountSpacingCheck,
       AmountSpacingValue, Orientation = "Horizontal",}
00197 \textcolor{stringliteral}{        Structure, Facename)}
00198 \textcolor{stringliteral}{        Note: Type of CoverAlong argument is a tuple. Syntax: (<Along>, <Value>). Here we have vertical
       orientation so we can pass Left Side}
00199 \textcolor{stringliteral}{        and Right Side to <Along> arguments.}
00200 \textcolor{stringliteral}{        For eg. ("Left Side", 20) and ("Right Side", 20)}
00201 \textcolor{stringliteral}{    """}
00202     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} structure \textcolor{keywordflow}{and} \textcolor{keywordflow}{not} facename:
00203         selected\_obj = FreeCADGui.Selection.getSelectionEx()[0]
00204         structure = selected\_obj.Object
00205         facename = selected\_obj.SubElementNames[0]
00206     face = structure.Shape.Faces[\hyperlink{namespaceRebarfunc_a3885b3b63e3a41508ac79bc7550cf301}{getFaceNumber}(facename) - 1]
00207     \textcolor{comment}{#StructurePRM = getTrueParametersOfStructure(structure)}
00208     FacePRM = \hyperlink{namespaceRebarfunc_a92122b3d7cedd3d47bb63380a5ac4d08}{getParametersOfFace}(structure, facename)
00209     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} FacePRM:
00210         FreeCAD.Console.PrintError(\textcolor{stringliteral}{"Cannot identified shape or from which base object sturctural element is
       derived\(\backslash\)n"})
00211         \textcolor{keywordflow}{return}
00212     \textcolor{comment}{# Get points of Striaght rebar}
00213     points = \hyperlink{namespaceStraightRebar_a1873c6f7f59b355a64fdd966ad75f778}{getpointsOfStraightRebar}(FacePRM, rt\_cover, lb\_cover, coverAlong, 
      orientation)
00214     \textcolor{keyword}{import} Part
00215     \textcolor{keyword}{import} Arch
00216     sketch = FreeCAD.activeDocument().addObject(\textcolor{stringliteral}{'Sketcher::SketchObject'}, \textcolor{stringliteral}{'Sketch'})
00217     sketch.MapMode = \textcolor{stringliteral}{"FlatFace"}
00218     sketch.Support = [(structure, facename)]
00219     FreeCAD.ActiveDocument.recompute()
00220     sketch.addGeometry(Part.LineSegment(points[0], points[1]), \textcolor{keyword}{False})
00221     \textcolor{keywordflow}{if} amount\_spacing\_check:
00222         rebar = Arch.makeRebar(structure, sketch, diameter, amount\_spacing\_value, f\_cover)
00223         FreeCAD.ActiveDocument.recompute()
00224     \textcolor{keywordflow}{else}:
00225         size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length
00226         rebar = Arch.makeRebar(structure, sketch, diameter, int((size - diameter) / amount\_spacing\_value), 
      f\_cover)
00227     \textcolor{comment}{# Adds properties to the rebar object}
00228     rebar.ViewObject.addProperty(\textcolor{stringliteral}{"App::PropertyString"}, \textcolor{stringliteral}{"RebarShape"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Shape of rebar"})).RebarShape = \textcolor{stringliteral}{"StraightRebar"}
00229     rebar.ViewObject.setEditorMode(\textcolor{stringliteral}{"RebarShape"}, 2)
00230     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"FrontCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Front cover of rebar"})).FrontCover = f\_cover
00231     rebar.setEditorMode(\textcolor{stringliteral}{"FrontCover"}, 2)
00232     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"RightTopCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Right/Top Side cover of rebar"})).RightTopCover = rt\_cover
00233     rebar.setEditorMode(\textcolor{stringliteral}{"RightTopCover"}, 2)
00234     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"LeftBottomCover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Left/Bottom Side cover of rebar"})).LeftBottomCover = lb\_cover
00235     rebar.setEditorMode(\textcolor{stringliteral}{"LeftBottomCover"}, 2)
00236     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyString"}, \textcolor{stringliteral}{"CoverAlong"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property"}
      , \textcolor{stringliteral}{"Cover along"})).CoverAlong = coverAlong[0]
00237     rebar.setEditorMode(\textcolor{stringliteral}{"CoverAlong"}, 2)
00238     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"Cover"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property"}, \textcolor{stringliteral}{"
      Cover of rebar along user selected side"})).Cover = coverAlong[1]
00239     rebar.setEditorMode(\textcolor{stringliteral}{"Cover"}, 2)
00240     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyBool"}, \textcolor{stringliteral}{"AmountCheck"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property"},
       \textcolor{stringliteral}{"Amount radio button is checked"})).AmountCheck
00241     rebar.setEditorMode(\textcolor{stringliteral}{"AmountCheck"}, 2)
00242     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyDistance"}, \textcolor{stringliteral}{"TrueSpacing"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"
      App::Property"}, \textcolor{stringliteral}{"Spacing between of rebars"})).TrueSpacing = amount\_spacing\_value
00243     rebar.setEditorMode(\textcolor{stringliteral}{"TrueSpacing"}, 2)
00244     rebar.addProperty(\textcolor{stringliteral}{"App::PropertyString"}, \textcolor{stringliteral}{"Orientation"}, \textcolor{stringliteral}{"RebarDialog"}, QT\_TRANSLATE\_NOOP(\textcolor{stringliteral}{"App::Property
      "}, \textcolor{stringliteral}{"Shape of rebar"})).Orientation = orientation
00245     rebar.setEditorMode(\textcolor{stringliteral}{"Orientation"}, 2)
00246     \textcolor{keywordflow}{if} amount\_spacing\_check:
00247         rebar.AmountCheck = \textcolor{keyword}{True}
00248     \textcolor{keywordflow}{else}:
00249         rebar.AmountCheck = \textcolor{keyword}{False}
00250         rebar.TrueSpacing = amount\_spacing\_value
00251     rebar.Label = \textcolor{stringliteral}{"StraightRebar"}
00252     FreeCAD.ActiveDocument.recompute()
00253     \textcolor{keywordflow}{return} rebar
00254 
\hypertarget{StraightRebar_8py_source.tex_l00255}{}\hyperlink{namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b}{00255} \textcolor{keyword}{def }\hyperlink{namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b}{editStraightRebar}(Rebar, f\_cover, coverAlong, rt\_cover, lb\_cover, diameter, 
      amount\_spacing\_check, amount\_spacing\_value, orientation, structure = None, facename = None):
00256     sketch = Rebar.Base
00257     \textcolor{keywordflow}{if} structure \textcolor{keywordflow}{and} facename:
00258         sketch.Support = [(structure, facename)]
00259         FreeCAD.ActiveDocument.recompute()
00260     \textcolor{comment}{# Check if sketch support is empty.}
00261     \textcolor{keywordflow}{if} \textcolor{keywordflow}{not} sketch.Support:
00262         \hyperlink{namespaceRebarfunc_a2278a0602d46a62953af1fcf2e574a94}{showWarning}(\textcolor{stringliteral}{"You have checked remove external geometry of base sketchs when needed.\(\backslash\)nTo
       unchecked Edit->Preferences->Arch."})
00263         \textcolor{keywordflow}{return}
00264     \textcolor{comment}{# Assigned values}
00265     facename = sketch.Support[0][1][0]
00266     structure = sketch.Support[0][0]
00267     face = structure.Shape.Faces[\hyperlink{namespaceRebarfunc_a3885b3b63e3a41508ac79bc7550cf301}{getFaceNumber}(facename) - 1]
00268     \textcolor{comment}{#StructurePRM = getTrueParametersOfStructure(structure)}
00269     \textcolor{comment}{# Get parameters of the face where sketch of rebar is drawn}
00270     FacePRM = \hyperlink{namespaceRebarfunc_a92122b3d7cedd3d47bb63380a5ac4d08}{getParametersOfFace}(structure, facename)
00271     \textcolor{comment}{# Get points of Striaght rebar}
00272     points = \hyperlink{namespaceStraightRebar_a1873c6f7f59b355a64fdd966ad75f778}{getpointsOfStraightRebar}(FacePRM, rt\_cover, lb\_cover, coverAlong, 
      orientation)
00273     sketch.movePoint(0, 1, points[0], 0)
00274     FreeCAD.ActiveDocument.recompute()
00275     sketch.movePoint(0, 2, points[1], 0)
00276     FreeCAD.ActiveDocument.recompute()
00277     Rebar.OffsetStart = f\_cover
00278     Rebar.OffsetEnd = f\_cover
00279     \textcolor{keywordflow}{if} amount\_spacing\_check:
00280         Rebar.Amount = amount\_spacing\_value
00281         FreeCAD.ActiveDocument.recompute()
00282         Rebar.AmountCheck = \textcolor{keyword}{True}
00283     \textcolor{keywordflow}{else}:
00284         size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length
00285         Rebar.Amount = int((size - diameter) / amount\_spacing\_value)
00286         FreeCAD.ActiveDocument.recompute()
00287         Rebar.AmountCheck = \textcolor{keyword}{False}
00288     Rebar.FrontCover = f\_cover
00289     Rebar.RightTopCover = rt\_cover
00290     Rebar.LeftBottomCover = lb\_cover
00291     Rebar.CoverAlong = coverAlong[0]
00292     Rebar.Cover = coverAlong[1]
00293     Rebar.TrueSpacing = amount\_spacing\_value
00294     Rebar.Diameter = diameter
00295     Rebar.Orientation = orientation
00296     FreeCAD.ActiveDocument.recompute()
00297     \textcolor{keywordflow}{return} Rebar
00298 
\hypertarget{StraightRebar_8py_source.tex_l00299}{}\hyperlink{namespaceStraightRebar_ad48f93922ce90bb63d051c7c3c794d35}{00299} \textcolor{keyword}{def }\hyperlink{namespaceStraightRebar_ad48f93922ce90bb63d051c7c3c794d35}{editDialog}(vobj):
00300     FreeCADGui.Control.closeDialog()
00301     obj = \hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel}{\_StraightRebarTaskPanel}(vobj.Object)
00302     obj.form.frontCover.setText(str(vobj.Object.FrontCover))
00303     obj.form.r\_sideCover.setText(str(vobj.Object.RightTopCover))
00304     obj.form.l\_sideCover.setText(str(vobj.Object.LeftBottomCover))
00305     obj.form.bottomCover.setText(str(vobj.Object.Cover))
00306     obj.form.diameter.setText(str(vobj.Object.Diameter))
00307     obj.form.orientation.setCurrentIndex(obj.form.orientation.findText(str(vobj.Object.Orientation)))
00308     obj.form.coverAlong.setCurrentIndex(obj.form.coverAlong.findText(str(vobj.Object.CoverAlong)))
00309     \textcolor{keywordflow}{if} vobj.Object.AmountCheck:
00310         obj.form.amount.setValue(vobj.Object.Amount)
00311     \textcolor{keywordflow}{else}:
00312         obj.form.amount\_radio.setChecked(\textcolor{keyword}{False})
00313         obj.form.spacing\_radio.setChecked(\textcolor{keyword}{True})
00314         obj.form.amount.setDisabled(\textcolor{keyword}{True})
00315         obj.form.spacing.setEnabled(\textcolor{keyword}{True})
00316         obj.form.spacing.setText(str(vobj.Object.TrueSpacing))
00317     \textcolor{comment}{#obj.form.PickSelectedFace.setVisible(False)}
00318     FreeCADGui.Control.showDialog(obj)
00319 
\hypertarget{StraightRebar_8py_source.tex_l00320}{}\hyperlink{namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277}{00320} \textcolor{keyword}{def }\hyperlink{namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277}{CommandStraightRebar}():
00321     selected\_obj = \hyperlink{namespaceRebarfunc_adae2713855a7e1b4bda04081ae671542}{check\_selected\_face}()
00322     \textcolor{keywordflow}{if} selected\_obj:
00323         FreeCADGui.Control.showDialog(\hyperlink{classStraightRebar_1_1__StraightRebarTaskPanel}{\_StraightRebarTaskPanel}())
\end{DoxyCode}
