<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Rebar Addon for FreeCAD: BentShapeRebar.py Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Rebar Addon for FreeCAD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li class="current"><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.html"><span>File&#160;List</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">BentShapeRebar.py</div>  </div>
</div><!--header-->
<div class="contents">
<a href="BentShapeRebar_8py.html">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html">    1</a></span>&#160;<span class="comment"># -*- coding: utf-8 -*-</span></div><div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="comment"># ***************************************************************************</span></div><div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="comment"># *   Copyright (c) 2017 - Amritpal Singh &lt;amrit3701@gmail.com&gt;             *</span></div><div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="comment"># *   This program is free software; you can redistribute it and/or modify  *</span></div><div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="comment"># *   it under the terms of the GNU Lesser General Public License (LGPL)    *</span></div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="comment"># *   as published by the Free Software Foundation; either version 2 of     *</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="comment"># *   the License, or (at your option) any later version.                   *</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="comment"># *   for detail see the LICENCE text file.                                 *</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="comment"># *   This program is distributed in the hope that it will be useful,       *</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="comment"># *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="comment"># *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="comment"># *   GNU Library General Public License for more details.                  *</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="comment"># *   You should have received a copy of the GNU Library General Public     *</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="comment"># *   License along with this program; if not, write to the Free Software   *</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="comment"># *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="comment"># *   USA                                                                   *</span></div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;<span class="comment"># ***************************************************************************</span></div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;</div><div class="line"><a name="l00024"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#a38b223debc1826fd2855773a02749bb4">   24</a></span>&#160;__title__ = <span class="stringliteral">&quot;BentShapeRebar&quot;</span></div><div class="line"><a name="l00025"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#ad79a2dbf88601c24aae561033cb48d34">   25</a></span>&#160;__author__ = <span class="stringliteral">&quot;Amritpal Singh&quot;</span></div><div class="line"><a name="l00026"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#aec768ca6a259d1cc738ea11c79a124e2">   26</a></span>&#160;__url__ = <span class="stringliteral">&quot;https://www.freecadweb.org&quot;</span></div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;<span class="keyword">from</span> PySide <span class="keyword">import</span> QtCore, QtGui</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;<span class="keyword">from</span> Rebarfunc <span class="keyword">import</span> *</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;<span class="keyword">from</span> PySide.QtCore <span class="keyword">import</span> QT_TRANSLATE_NOOP</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;<span class="keyword">from</span> RebarDistribution <span class="keyword">import</span> runRebarDistribution, removeRebarDistribution</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;<span class="keyword">from</span> PopUpImage <span class="keyword">import</span> showPopUpImageDialog</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;<span class="keyword">import</span> FreeCAD</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;<span class="keyword">import</span> FreeCADGui</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;<span class="keyword">import</span> ArchCommands</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;<span class="keyword">import</span> os</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;<span class="keyword">import</span> sys</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;<span class="keyword">import</span> math</div><div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;</div><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">   40</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">getpointsOfBentShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation):</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; getpointsOfBentShapeRebar(FacePRM, LeftCover, RightCover, BottomCover, TopCover, BentLength, BentAngle, Orientation):</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="stringliteral">    Return points of the LShape rebar in the form of array for sketch.</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;<span class="stringliteral">    It takes four different orientations input i.e. &#39;Bottom&#39;, &#39;Top&#39;, &#39;Left&#39;, &#39;Right&#39;.</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    <span class="keywordflow">if</span> orientation == <span class="stringliteral">&quot;Bottom&quot;</span>:</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        x2 = x1 + bentLength</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        y2 = y1</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        dis = (FacePRM[0][1] - t_cover - b_cover) * math.tan(math.radians(bentAngle - 90))</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;        x3 = x2 + dis</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;        y3 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;        x4 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover - bentLength - dis</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;        y4 = y3</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;        x5 = x4 + dis</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        y5 = y2</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;        x6 = x5 + bentLength</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;        y6 = y5</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Top&quot;</span>:</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;        y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;        x2 = x1 + bentLength</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;        y2 = y1</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;        dis = (FacePRM[0][1] - t_cover - b_cover) * math.tan(math.radians(bentAngle - 90))</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;        x3 = x2 + dis</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;        y3 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        x4 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover - bentLength - dis</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;        y4 = y3</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;        x5 = x4 + dis</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;        y5 = y2</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        x6 = x5 + bentLength</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;        y6 = y5</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Left&quot;</span>:</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;        x1 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;        x2 = x1</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;        y2 = y1 - bentLength</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;        dis = (FacePRM[0][0] - r_cover - l_cover) * math.tan(math.radians(bentAngle - 90))</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;        x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;        y3 = y2 - dis</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;        x4 = x3</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;        y4 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover + bentLength + dis</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;        x5 = x2</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        y5 = y4 - dis</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;        x6 = x5</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;        y6 = y5 - bentLength</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Right&quot;</span>:</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;        x2 = x1</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;        y2 = y1 - bentLength</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;        dis = (FacePRM[0][0] - r_cover - l_cover) * math.tan(math.radians(bentAngle - 90))</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;        x3 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;        y3 = y2 - dis</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;        x4 = x3</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;        y4 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover + bentLength + dis</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;        x5 = x2</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;        y5 = y4 - dis</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;        x6 = x5</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;        y6 = y5 - bentLength</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;    <span class="keywordflow">return</span> [FreeCAD.Vector(x1, y1, 0), FreeCAD.Vector(x2, y2, 0),\</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;           FreeCAD.Vector(x3, y3, 0), FreeCAD.Vector(x4, y4, 0),\</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;           FreeCAD.Vector(x5, y5, 0), FreeCAD.Vector(x6, y6, 0)]</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;</div><div class="line"><a name="l00105"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">  105</a></span>&#160;<span class="keyword">class </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">_BentShapeRebarTaskPanel</a>:</div><div class="line"><a name="l00106"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a0f978d5a751619f8ae7dfe178fb0473e">  106</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a0f978d5a751619f8ae7dfe178fb0473e">__init__</a>(self, Rebar = None):</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;        <span class="keywordflow">if</span> <span class="keywordflow">not</span> Rebar:</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;            selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00109"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">  109</a></span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a> = selected_obj.Object</div><div class="line"><a name="l00110"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">  110</a></span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a> = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a> = Rebar.Base.Support[0][1][0]</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a> = Rebar.Base.Support[0][0]</div><div class="line"><a name="l00114"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#acbe07c5ace61552cc4e4899b668d93e5">  114</a></span>&#160;        self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#acbe07c5ace61552cc4e4899b668d93e5">form</a> = FreeCADGui.PySideUic.loadUi(os.path.splitext(__file__)[0] + <span class="stringliteral">&quot;.ui&quot;</span>)</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;        self.form.setWindowTitle(QtGui.QApplication.translate(<span class="stringliteral">&quot;RebarAddon&quot;</span>, <span class="stringliteral">&quot;Bent Shape Rebar&quot;</span>, <span class="keywordtype">None</span>))</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;        self.form.orientation.addItems([<span class="stringliteral">&quot;Bottom&quot;</span>, <span class="stringliteral">&quot;Top&quot;</span>, <span class="stringliteral">&quot;Right&quot;</span>, <span class="stringliteral">&quot;Left&quot;</span>])</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;        self.form.amount_radio.clicked.connect(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">amount_radio_clicked</a>)</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;        self.form.spacing_radio.clicked.connect(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">spacing_radio_clicked</a>)</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;        self.form.customSpacing.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespaceRebarDistribution.html#aa547df5cb10d2e64eaa0b51c445fa30b">runRebarDistribution</a>(self))</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;        self.form.removeCustomSpacing.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespaceRebarDistribution.html#a85270a1b6e8c782a9e0ba54add518f2a">removeRebarDistribution</a>(self))</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;        self.form.PickSelectedFace.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespaceRebarfunc.html#a8c003df49ac5f249bd9ea4acfb7d2f8d">getSelectedFace</a>(self))</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;        self.form.orientation.currentIndexChanged.connect(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">getOrientation</a>)</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;        self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + <span class="stringliteral">&quot;/icons/BentShapeRebar.svg&quot;</span>))</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;        self.form.toolButton.setIcon(self.form.toolButton.style().standardIcon(QtGui.QStyle.SP_DialogHelpButton))</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;        self.form.toolButton.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespacePopUpImage.html#a8c565620d7de9b4882a44eacb870ad05">showPopUpImageDialog</a>(os.path.split(os.path.abspath(__file__))[0] + <span class="stringliteral">&quot;/icons/BentShapeRebarDetailed.svg&quot;</span>))</div><div class="line"><a name="l00126"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">  126</a></span>&#160;        self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a> = Rebar</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;</div><div class="line"><a name="l00128"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">  128</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">getOrientation</a>(self):</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;        orientation = self.form.orientation.currentText()</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;        <span class="comment">#if orientation == &quot;Bottom&quot;:</span></div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;        <span class="comment">#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + &quot;/icons/LShapeRebarBR.svg&quot;))</span></div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;        <span class="comment">#elif orientation == &quot;Top&quot;:</span></div><div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;        <span class="comment">#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + &quot;/icons/LShapeRebarBL.svg&quot;))</span></div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;        <span class="comment">#elif orientation == &quot;Right&quot;:</span></div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;        <span class="comment">#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + &quot;/icons/LShapeRebarTR.svg&quot;))</span></div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;        <span class="comment">#else:</span></div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;        <span class="comment">#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + &quot;/icons/LShapeRebarTL.svg&quot;))</span></div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;</div><div class="line"><a name="l00139"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#af363d8287c33547f2b7fc6f6f326d47a">  139</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#af363d8287c33547f2b7fc6f6f326d47a">getStandardButtons</a>(self):</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;        <span class="keywordflow">return</span> int(QtGui.QDialogButtonBox.Ok) | int(QtGui.QDialogButtonBox.Apply) | int(QtGui.QDialogButtonBox.Cancel)</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;</div><div class="line"><a name="l00142"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906">  142</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906">clicked</a>(self, button):</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;        <span class="keywordflow">if</span> button == int(QtGui.QDialogButtonBox.Apply):</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">accept</a>(button)</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;</div><div class="line"><a name="l00146"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">  146</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">accept</a>(self, signal = None):</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;        f_cover = self.form.frontCover.text()</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;        f_cover = FreeCAD.Units.Quantity(f_cover).Value</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;        b_cover = self.form.bottomCover.text()</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;        b_cover = FreeCAD.Units.Quantity(b_cover).Value</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;        l_cover = self.form.l_sideCover.text()</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;        l_cover = FreeCAD.Units.Quantity(l_cover).Value</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;        r_cover = self.form.r_sideCover.text()</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;        r_cover = FreeCAD.Units.Quantity(r_cover).Value</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;        t_cover = self.form.topCover.text()</div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;        t_cover = FreeCAD.Units.Quantity(t_cover).Value</div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;        bentLength = self.form.bentLength.text()</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;        bentLength = FreeCAD.Units.Quantity(bentLength).Value</div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;        bentAngle = self.form.bentAngle.value()</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;        diameter = self.form.diameter.text()</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;        diameter = FreeCAD.Units.Quantity(diameter).Value</div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;        rounding = self.form.rounding.value()</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;        orientation = self.form.orientation.currentText()</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;        amount_check = self.form.amount_radio.isChecked()</div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;        spacing_check = self.form.spacing_radio.isChecked()</div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;        <span class="keywordflow">if</span> <span class="keywordflow">not</span> self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a>:</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;            <span class="keywordflow">if</span> amount_check:</div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;                amount = self.form.amount.value()</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;                rebar = <a class="code" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">makeBentShapeRebar</a>(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, <span class="keyword">True</span>, amount, orientation, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a>, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a>)</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;            <span class="keywordflow">elif</span> spacing_check:</div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;                spacing = self.form.spacing.text()</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;                spacing = FreeCAD.Units.Quantity(spacing).Value</div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;                rebar = <a class="code" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">makeBentShapeRebar</a>(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, <span class="keyword">False</span>, spacing, orientation, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a>, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a>)</div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;            <span class="keywordflow">if</span> amount_check:</div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;                amount = self.form.amount.value()</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;                rebar = <a class="code" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">editBentShapeRebar</a>(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a>, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, <span class="keyword">True</span>, amount, orientation, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a>, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a>)</div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;            <span class="keywordflow">elif</span> spacing_check:</div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;                spacing = self.form.spacing.text()</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;                spacing = FreeCAD.Units.Quantity(spacing).Value</div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;                rebar = <a class="code" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">editBentShapeRebar</a>(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a>, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, <span class="keyword">False</span>, spacing, orientation, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a>, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a>)</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;        <span class="keywordflow">if</span> self.CustomSpacing:</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;            rebar.CustomSpacing = self.CustomSpacing</div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;            FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;        self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a> = rebar</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;        <span class="keywordflow">if</span> signal == int(QtGui.QDialogButtonBox.Apply):</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;            <span class="keywordflow">pass</span></div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;            FreeCADGui.Control.closeDialog(self)</div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;</div><div class="line"><a name="l00191"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">  191</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">amount_radio_clicked</a>(self):</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;        self.form.spacing.setEnabled(<span class="keyword">False</span>)</div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;        self.form.amount.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;</div><div class="line"><a name="l00195"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">  195</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">spacing_radio_clicked</a>(self):</div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;        self.form.amount.setEnabled(<span class="keyword">False</span>)</div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;        self.form.spacing.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;</div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;</div><div class="line"><a name="l00200"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">  200</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">makeBentShapeRebar</a>(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation = &quot;Bottom Left&quot;, structure = None, facename = None):</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; makeBentShapeRebar(FrontCover, BottomCover, LeftCover, RightCover, Diameter, TopCover, BentLength, BentAngle, Rounding,</span></div><div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;<span class="stringliteral">    AmountSpacingCheck, AmountSpacingValue, Orientation, Structure, Facename): Adds the Bent-Shape reinforcement bar to the</span></div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;<span class="stringliteral">    selected structural object.</span></div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;<span class="stringliteral">    It takes four different orientations input i.e. &#39;Bottom&#39;, &#39;Top&#39;, &#39;Left&#39;, &#39;Right&#39;.</span></div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> structure <span class="keywordflow">and</span> <span class="keywordflow">not</span> facename:</div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;        selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;        structure = selected_obj.Object</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;        facename = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename)</div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> FacePRM:</div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;        FreeCAD.Console.PrintError(<span class="stringliteral">&quot;Cannot identified shape or from which base object sturctural element is derived\n&quot;</span>)</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;    <span class="comment"># Get points of L-Shape rebar</span></div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    points = <a class="code" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">getpointsOfBentShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    <span class="keyword">import</span> Part</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    <span class="keyword">import</span> Arch</div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    sketch = FreeCAD.activeDocument().addObject(<span class="stringliteral">&#39;Sketcher::SketchObject&#39;</span>, <span class="stringliteral">&#39;Sketch&#39;</span>)</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    sketch.MapMode = <span class="stringliteral">&quot;FlatFace&quot;</span></div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    sketch.addGeometry(Part.LineSegment(points[0], points[1]), <span class="keyword">False</span>)</div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;    sketch.addGeometry(Part.LineSegment(points[1], points[2]), <span class="keyword">False</span>)</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;    sketch.addGeometry(Part.LineSegment(points[2], points[3]), <span class="keyword">False</span>)</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;    sketch.addGeometry(Part.LineSegment(points[3], points[4]), <span class="keyword">False</span>)</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;    sketch.addGeometry(Part.LineSegment(points[4], points[5]), <span class="keyword">False</span>)</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;    <span class="keyword">import</span> Sketcher</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;        rebar = Arch.makeRebar(structure, sketch, diameter, amount_spacing_value, f_cover)</div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;        rebar = Arch.makeRebar(structure, sketch, diameter, int((size - diameter) / amount_spacing_value), f_cover)</div><div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;    rebar.Rounding = rounding</div><div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;    <span class="comment"># Adds properties to the rebar object</span></div><div class="line"><a name="l00238"></a><span class="lineno">  238</span>&#160;    rebar.ViewObject.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;RebarShape&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).RebarShape = <span class="stringliteral">&quot;BentShapeRebar&quot;</span></div><div class="line"><a name="l00239"></a><span class="lineno">  239</span>&#160;    rebar.ViewObject.setEditorMode(<span class="stringliteral">&quot;RebarShape&quot;</span>, 2)</div><div class="line"><a name="l00240"></a><span class="lineno">  240</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;FrontCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Front cover of rebar&quot;</span>)).FrontCover = f_cover</div><div class="line"><a name="l00241"></a><span class="lineno">  241</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;FrontCover&quot;</span>, 2)</div><div class="line"><a name="l00242"></a><span class="lineno">  242</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;LeftCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Left Side cover of rebar&quot;</span>)).LeftCover = l_cover</div><div class="line"><a name="l00243"></a><span class="lineno">  243</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;LeftCover&quot;</span>, 2)</div><div class="line"><a name="l00244"></a><span class="lineno">  244</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;RightCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Right Side cover of rebar&quot;</span>)).RightCover = r_cover</div><div class="line"><a name="l00245"></a><span class="lineno">  245</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;RightCover&quot;</span>, 2)</div><div class="line"><a name="l00246"></a><span class="lineno">  246</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BottomCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bottom cover of rebar&quot;</span>)).BottomCover = b_cover</div><div class="line"><a name="l00247"></a><span class="lineno">  247</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BottomCover&quot;</span>, 2)</div><div class="line"><a name="l00248"></a><span class="lineno">  248</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyBool&quot;</span>, <span class="stringliteral">&quot;AmountCheck&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Amount radio button is checked&quot;</span>)).AmountCheck</div><div class="line"><a name="l00249"></a><span class="lineno">  249</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;AmountCheck&quot;</span>, 2)</div><div class="line"><a name="l00250"></a><span class="lineno">  250</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TopCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Top cover of rebar&quot;</span>)).TopCover = t_cover</div><div class="line"><a name="l00251"></a><span class="lineno">  251</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TopCover&quot;</span>, 2)</div><div class="line"><a name="l00252"></a><span class="lineno">  252</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TrueSpacing&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Spacing between of rebars&quot;</span>)).TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00253"></a><span class="lineno">  253</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;Orientation&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).Orientation = orientation</div><div class="line"><a name="l00254"></a><span class="lineno">  254</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;Orientation&quot;</span>, 2)</div><div class="line"><a name="l00255"></a><span class="lineno">  255</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TrueSpacing&quot;</span>, 2)</div><div class="line"><a name="l00256"></a><span class="lineno">  256</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BentLength&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;BentLength cover of rebar&quot;</span>)).BentLength = bentLength</div><div class="line"><a name="l00257"></a><span class="lineno">  257</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BentLength&quot;</span>, 2)</div><div class="line"><a name="l00258"></a><span class="lineno">  258</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BentAngle&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bent Angle of rebar&quot;</span>)).BentAngle = bentAngle</div><div class="line"><a name="l00259"></a><span class="lineno">  259</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BentAngle&quot;</span>, 2)</div><div class="line"><a name="l00260"></a><span class="lineno">  260</span>&#160;</div><div class="line"><a name="l00261"></a><span class="lineno">  261</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00262"></a><span class="lineno">  262</span>&#160;        rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00263"></a><span class="lineno">  263</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00264"></a><span class="lineno">  264</span>&#160;        rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00265"></a><span class="lineno">  265</span>&#160;        rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00266"></a><span class="lineno">  266</span>&#160;    rebar.Label = <span class="stringliteral">&quot;BentShapeRebar&quot;</span></div><div class="line"><a name="l00267"></a><span class="lineno">  267</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00268"></a><span class="lineno">  268</span>&#160;    <span class="keywordflow">return</span> rebar</div><div class="line"><a name="l00269"></a><span class="lineno">  269</span>&#160;</div><div class="line"><a name="l00270"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">  270</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">editBentShapeRebar</a>(Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation, structure = None, facename = None):</div><div class="line"><a name="l00271"></a><span class="lineno">  271</span>&#160;    sketch = Rebar.Base</div><div class="line"><a name="l00272"></a><span class="lineno">  272</span>&#160;    <span class="keywordflow">if</span> structure <span class="keywordflow">and</span> facename:</div><div class="line"><a name="l00273"></a><span class="lineno">  273</span>&#160;        sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00274"></a><span class="lineno">  274</span>&#160;    <span class="comment"># Check if sketch support is empty.</span></div><div class="line"><a name="l00275"></a><span class="lineno">  275</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> sketch.Support:</div><div class="line"><a name="l00276"></a><span class="lineno">  276</span>&#160;        <a class="code" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">showWarning</a>(<span class="stringliteral">&quot;You have checked remove external geometry of base sketchs when needed.\nTo unchecked Edit-&gt;Preferences-&gt;Arch.&quot;</span>)</div><div class="line"><a name="l00277"></a><span class="lineno">  277</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00278"></a><span class="lineno">  278</span>&#160;    <span class="comment"># Assigned values</span></div><div class="line"><a name="l00279"></a><span class="lineno">  279</span>&#160;    facename = sketch.Support[0][1][0]</div><div class="line"><a name="l00280"></a><span class="lineno">  280</span>&#160;    structure = sketch.Support[0][0]</div><div class="line"><a name="l00281"></a><span class="lineno">  281</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00282"></a><span class="lineno">  282</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00283"></a><span class="lineno">  283</span>&#160;    <span class="comment"># Get parameters of the face where sketch of rebar is drawn</span></div><div class="line"><a name="l00284"></a><span class="lineno">  284</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename)</div><div class="line"><a name="l00285"></a><span class="lineno">  285</span>&#160;    <span class="comment"># Get points of L-Shape rebar</span></div><div class="line"><a name="l00286"></a><span class="lineno">  286</span>&#160;    points = <a class="code" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">getpointsOfBentShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</div><div class="line"><a name="l00287"></a><span class="lineno">  287</span>&#160;    sketch.movePoint(0, 1, points[0], 0)</div><div class="line"><a name="l00288"></a><span class="lineno">  288</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00289"></a><span class="lineno">  289</span>&#160;    sketch.movePoint(0, 2, points[1], 0)</div><div class="line"><a name="l00290"></a><span class="lineno">  290</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00291"></a><span class="lineno">  291</span>&#160;    sketch.movePoint(1, 1, points[1], 0)</div><div class="line"><a name="l00292"></a><span class="lineno">  292</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00293"></a><span class="lineno">  293</span>&#160;    sketch.movePoint(1, 2, points[2], 0)</div><div class="line"><a name="l00294"></a><span class="lineno">  294</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00295"></a><span class="lineno">  295</span>&#160;</div><div class="line"><a name="l00296"></a><span class="lineno">  296</span>&#160;    sketch.movePoint(2, 1, points[2], 0)</div><div class="line"><a name="l00297"></a><span class="lineno">  297</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00298"></a><span class="lineno">  298</span>&#160;    sketch.movePoint(2, 2, points[3], 0)</div><div class="line"><a name="l00299"></a><span class="lineno">  299</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00300"></a><span class="lineno">  300</span>&#160;    sketch.movePoint(3, 1, points[3], 0)</div><div class="line"><a name="l00301"></a><span class="lineno">  301</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00302"></a><span class="lineno">  302</span>&#160;    sketch.movePoint(3, 2, points[4], 0)</div><div class="line"><a name="l00303"></a><span class="lineno">  303</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00304"></a><span class="lineno">  304</span>&#160;</div><div class="line"><a name="l00305"></a><span class="lineno">  305</span>&#160;    sketch.movePoint(4, 1, points[4], 0)</div><div class="line"><a name="l00306"></a><span class="lineno">  306</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00307"></a><span class="lineno">  307</span>&#160;    sketch.movePoint(4, 2, points[5], 0)</div><div class="line"><a name="l00308"></a><span class="lineno">  308</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00309"></a><span class="lineno">  309</span>&#160;</div><div class="line"><a name="l00310"></a><span class="lineno">  310</span>&#160;    Rebar.OffsetStart = f_cover</div><div class="line"><a name="l00311"></a><span class="lineno">  311</span>&#160;    Rebar.OffsetEnd = f_cover</div><div class="line"><a name="l00312"></a><span class="lineno">  312</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00313"></a><span class="lineno">  313</span>&#160;        Rebar.Amount = amount_spacing_value</div><div class="line"><a name="l00314"></a><span class="lineno">  314</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00315"></a><span class="lineno">  315</span>&#160;        Rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00316"></a><span class="lineno">  316</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00317"></a><span class="lineno">  317</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00318"></a><span class="lineno">  318</span>&#160;        Rebar.Amount = int((size - diameter) / amount_spacing_value)</div><div class="line"><a name="l00319"></a><span class="lineno">  319</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00320"></a><span class="lineno">  320</span>&#160;        Rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00321"></a><span class="lineno">  321</span>&#160;    Rebar.Diameter = diameter</div><div class="line"><a name="l00322"></a><span class="lineno">  322</span>&#160;    Rebar.FrontCover = f_cover</div><div class="line"><a name="l00323"></a><span class="lineno">  323</span>&#160;    Rebar.LeftCover = l_cover</div><div class="line"><a name="l00324"></a><span class="lineno">  324</span>&#160;    Rebar.RightCover = r_cover</div><div class="line"><a name="l00325"></a><span class="lineno">  325</span>&#160;    Rebar.BottomCover = b_cover</div><div class="line"><a name="l00326"></a><span class="lineno">  326</span>&#160;    Rebar.TopCover = t_cover</div><div class="line"><a name="l00327"></a><span class="lineno">  327</span>&#160;    Rebar.BentLength = bentLength</div><div class="line"><a name="l00328"></a><span class="lineno">  328</span>&#160;    Rebar.BentAngle = bentAngle</div><div class="line"><a name="l00329"></a><span class="lineno">  329</span>&#160;    Rebar.Rounding = rounding</div><div class="line"><a name="l00330"></a><span class="lineno">  330</span>&#160;    Rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00331"></a><span class="lineno">  331</span>&#160;    Rebar.Orientation = orientation</div><div class="line"><a name="l00332"></a><span class="lineno">  332</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00333"></a><span class="lineno">  333</span>&#160;    <span class="keywordflow">return</span> Rebar</div><div class="line"><a name="l00334"></a><span class="lineno">  334</span>&#160;</div><div class="line"><a name="l00335"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#ae5db82a49148a0a8f6fa567fa72d93b2">  335</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#ae5db82a49148a0a8f6fa567fa72d93b2">editDialog</a>(vobj):</div><div class="line"><a name="l00336"></a><span class="lineno">  336</span>&#160;    FreeCADGui.Control.closeDialog()</div><div class="line"><a name="l00337"></a><span class="lineno">  337</span>&#160;    obj = <a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">_BentShapeRebarTaskPanel</a>(vobj.Object)</div><div class="line"><a name="l00338"></a><span class="lineno">  338</span>&#160;    obj.form.frontCover.setText(str(vobj.Object.FrontCover))</div><div class="line"><a name="l00339"></a><span class="lineno">  339</span>&#160;    obj.form.l_sideCover.setText(str(vobj.Object.LeftCover))</div><div class="line"><a name="l00340"></a><span class="lineno">  340</span>&#160;    obj.form.r_sideCover.setText(str(vobj.Object.RightCover))</div><div class="line"><a name="l00341"></a><span class="lineno">  341</span>&#160;    obj.form.bottomCover.setText(str(vobj.Object.BottomCover))</div><div class="line"><a name="l00342"></a><span class="lineno">  342</span>&#160;    obj.form.diameter.setText(str(vobj.Object.Diameter))</div><div class="line"><a name="l00343"></a><span class="lineno">  343</span>&#160;    obj.form.topCover.setText(str(vobj.Object.TopCover))</div><div class="line"><a name="l00344"></a><span class="lineno">  344</span>&#160;    obj.form.bentLength.setText(str(vobj.Object.BentLength))</div><div class="line"><a name="l00345"></a><span class="lineno">  345</span>&#160;    obj.form.bentAngle.setValue(vobj.Object.BentAngle)</div><div class="line"><a name="l00346"></a><span class="lineno">  346</span>&#160;    obj.form.rounding.setValue(vobj.Object.Rounding)</div><div class="line"><a name="l00347"></a><span class="lineno">  347</span>&#160;    obj.form.orientation.setCurrentIndex(obj.form.orientation.findText(str(vobj.Object.Orientation)))</div><div class="line"><a name="l00348"></a><span class="lineno">  348</span>&#160;    <span class="keywordflow">if</span> vobj.Object.AmountCheck:</div><div class="line"><a name="l00349"></a><span class="lineno">  349</span>&#160;        obj.form.amount.setValue(vobj.Object.Amount)</div><div class="line"><a name="l00350"></a><span class="lineno">  350</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00351"></a><span class="lineno">  351</span>&#160;        obj.form.amount_radio.setChecked(<span class="keyword">False</span>)</div><div class="line"><a name="l00352"></a><span class="lineno">  352</span>&#160;        obj.form.spacing_radio.setChecked(<span class="keyword">True</span>)</div><div class="line"><a name="l00353"></a><span class="lineno">  353</span>&#160;        obj.form.amount.setDisabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00354"></a><span class="lineno">  354</span>&#160;        obj.form.spacing.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00355"></a><span class="lineno">  355</span>&#160;        obj.form.spacing.setText(str(vobj.Object.TrueSpacing))</div><div class="line"><a name="l00356"></a><span class="lineno">  356</span>&#160;    <span class="comment">#obj.form.PickSelectedFace.setVisible(False)</span></div><div class="line"><a name="l00357"></a><span class="lineno">  357</span>&#160;    FreeCADGui.Control.showDialog(obj)</div><div class="line"><a name="l00358"></a><span class="lineno">  358</span>&#160;</div><div class="line"><a name="l00359"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#abc4f0ada7811da5cf9174551bc3c6b37">  359</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#abc4f0ada7811da5cf9174551bc3c6b37">CommandBentShapeRebar</a>():</div><div class="line"><a name="l00360"></a><span class="lineno">  360</span>&#160;    selected_obj = <a class="code" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">check_selected_face</a>()</div><div class="line"><a name="l00361"></a><span class="lineno">  361</span>&#160;    <span class="keywordflow">if</span> selected_obj:</div><div class="line"><a name="l00362"></a><span class="lineno">  362</span>&#160;        FreeCADGui.Control.showDialog(<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">_BentShapeRebarTaskPanel</a>())</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_afdcf71c6a16711a535971366558ea918"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">BentShapeRebar._BentShapeRebarTaskPanel.accept</a></div><div class="ttdeci">def accept(self, signal=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00146">BentShapeRebar.py:146</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_adae2713855a7e1b4bda04081ae671542"><div class="ttname"><a href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">Rebarfunc.check_selected_face</a></div><div class="ttdeci">def check_selected_face()</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00255">Rebarfunc.py:255</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">BentShapeRebar._BentShapeRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00105">BentShapeRebar.py:105</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_ab33579342d5fa4d4bf0bc8c9b9dfa526"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">BentShapeRebar._BentShapeRebarTaskPanel.getOrientation</a></div><div class="ttdeci">def getOrientation(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00128">BentShapeRebar.py:128</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_acbe07c5ace61552cc4e4899b668d93e5"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#acbe07c5ace61552cc4e4899b668d93e5">BentShapeRebar._BentShapeRebarTaskPanel.form</a></div><div class="ttdeci">form</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00114">BentShapeRebar.py:114</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a8c003df49ac5f249bd9ea4acfb7d2f8d"><div class="ttname"><a href="namespaceRebarfunc.html#a8c003df49ac5f249bd9ea4acfb7d2f8d">Rebarfunc.getSelectedFace</a></div><div class="ttdeci">def getSelectedFace(self)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00278">Rebarfunc.py:278</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceRebarDistribution_html_aa547df5cb10d2e64eaa0b51c445fa30b"><div class="ttname"><a href="namespaceRebarDistribution.html#aa547df5cb10d2e64eaa0b51c445fa30b">RebarDistribution.runRebarDistribution</a></div><div class="ttdeci">def runRebarDistribution(self)</div><div class="ttdef"><b>Definition:</b> <a href="RebarDistribution_8py_source.html#l00098">RebarDistribution.py:98</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_a33951a8ab21a73bae42af9f81d7c43c3"><div class="ttname"><a href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">BentShapeRebar.getpointsOfBentShapeRebar</a></div><div class="ttdeci">def getpointsOfBentShapeRebar(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00040">BentShapeRebar.py:40</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_ad99f80f17842220db5920e1926ff45a2"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">BentShapeRebar._BentShapeRebarTaskPanel.amount_radio_clicked</a></div><div class="ttdeci">def amount_radio_clicked(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00191">BentShapeRebar.py:191</a></div></div>
<div class="ttc" id="namespacePopUpImage_html_a8c565620d7de9b4882a44eacb870ad05"><div class="ttname"><a href="namespacePopUpImage.html#a8c565620d7de9b4882a44eacb870ad05">PopUpImage.showPopUpImageDialog</a></div><div class="ttdeci">def showPopUpImageDialog(img)</div><div class="ttdef"><b>Definition:</b> <a href="PopUpImage_8py_source.html#l00043">PopUpImage.py:43</a></div></div>
<div class="ttc" id="namespaceRebarDistribution_html_a85270a1b6e8c782a9e0ba54add518f2a"><div class="ttname"><a href="namespaceRebarDistribution.html#a85270a1b6e8c782a9e0ba54add518f2a">RebarDistribution.removeRebarDistribution</a></div><div class="ttdeci">def removeRebarDistribution(self)</div><div class="ttdef"><b>Definition:</b> <a href="RebarDistribution_8py_source.html#l00108">RebarDistribution.py:108</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_a941d005845cd497c0beb12bb8fef9171"><div class="ttname"><a href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">BentShapeRebar.editBentShapeRebar</a></div><div class="ttdeci">def editBentShapeRebar(Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00270">BentShapeRebar.py:270</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a2278a0602d46a62953af1fcf2e574a94"><div class="ttname"><a href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">Rebarfunc.showWarning</a></div><div class="ttdeci">def showWarning(message)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00293">Rebarfunc.py:293</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a24d363ab6c058ce4436a2b29e9c0b279"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">BentShapeRebar._BentShapeRebarTaskPanel.SelectedObj</a></div><div class="ttdeci">SelectedObj</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00109">BentShapeRebar.py:109</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_aac46779d3e1905db5a3788917f6e2476"><div class="ttname"><a href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">BentShapeRebar.makeBentShapeRebar</a></div><div class="ttdeci">def makeBentShapeRebar(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation=&quot;Bottom Left&quot;, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00200">BentShapeRebar.py:200</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a499514a87885d4c9462e3c6dc314ec9c"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">BentShapeRebar._BentShapeRebarTaskPanel.FaceName</a></div><div class="ttdeci">FaceName</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00110">BentShapeRebar.py:110</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_ae92dd6ab03c4b967b064fac00fa0d906"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906">BentShapeRebar._BentShapeRebarTaskPanel.clicked</a></div><div class="ttdeci">def clicked(self, button)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00142">BentShapeRebar.py:142</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_ae5db82a49148a0a8f6fa567fa72d93b2"><div class="ttname"><a href="namespaceBentShapeRebar.html#ae5db82a49148a0a8f6fa567fa72d93b2">BentShapeRebar.editDialog</a></div><div class="ttdeci">def editDialog(vobj)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00335">BentShapeRebar.py:335</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_af363d8287c33547f2b7fc6f6f326d47a"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#af363d8287c33547f2b7fc6f6f326d47a">BentShapeRebar._BentShapeRebarTaskPanel.getStandardButtons</a></div><div class="ttdeci">def getStandardButtons(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00139">BentShapeRebar.py:139</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a0f978d5a751619f8ae7dfe178fb0473e"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a0f978d5a751619f8ae7dfe178fb0473e">BentShapeRebar._BentShapeRebarTaskPanel.__init__</a></div><div class="ttdeci">def __init__(self, Rebar=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00106">BentShapeRebar.py:106</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_abc4f0ada7811da5cf9174551bc3c6b37"><div class="ttname"><a href="namespaceBentShapeRebar.html#abc4f0ada7811da5cf9174551bc3c6b37">BentShapeRebar.CommandBentShapeRebar</a></div><div class="ttdeci">def CommandBentShapeRebar()</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00359">BentShapeRebar.py:359</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a7fb1b14fac066c36380036c6d3f3ab4a"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">BentShapeRebar._BentShapeRebarTaskPanel.spacing_radio_clicked</a></div><div class="ttdeci">def spacing_radio_clicked(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00195">BentShapeRebar.py:195</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_aae8fd4e66d675c566d0afcee0af2341f"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">BentShapeRebar._BentShapeRebarTaskPanel.Rebar</a></div><div class="ttdeci">Rebar</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00126">BentShapeRebar.py:126</a></div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Wed Dec 13 2017 22:36:42 for Rebar Addon for FreeCAD by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.11
</small></address>
</body>
</html>
