<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Rebar Addon for FreeCAD: BentShapeRebar._BentShapeRebarTaskPanel Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Rebar Addon for FreeCAD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.html"><span>Class&#160;List</span></a></li>
      <li><a href="classes.html"><span>Class&#160;Index</span></a></li>
      <li><a href="inherits.html"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespaceBentShapeRebar.html">BentShapeRebar</a></li><li class="navelem"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">_BentShapeRebarTaskPanel</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-attribs">Public Attributes</a> &#124;
<a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel-members.html">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">BentShapeRebar._BentShapeRebarTaskPanel Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="dynheader">
Collaboration diagram for BentShapeRebar._BentShapeRebarTaskPanel:</div>
<div class="dyncontent">
<div class="center"><img src="classBentShapeRebar_1_1__BentShapeRebarTaskPanel__coll__graph.png" border="0" usemap="#BentShapeRebar_8__BentShapeRebarTaskPanel_coll__map" alt="Collaboration graph"/></div>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a0f978d5a751619f8ae7dfe178fb0473e"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a0f978d5a751619f8ae7dfe178fb0473e">__init__</a> (self, <a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a>=None)</td></tr>
<tr class="separator:a0f978d5a751619f8ae7dfe178fb0473e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab33579342d5fa4d4bf0bc8c9b9dfa526"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">getOrientation</a> (self)</td></tr>
<tr class="separator:ab33579342d5fa4d4bf0bc8c9b9dfa526"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af363d8287c33547f2b7fc6f6f326d47a"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#af363d8287c33547f2b7fc6f6f326d47a">getStandardButtons</a> (self)</td></tr>
<tr class="separator:af363d8287c33547f2b7fc6f6f326d47a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae92dd6ab03c4b967b064fac00fa0d906"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906">clicked</a> (self, button)</td></tr>
<tr class="separator:ae92dd6ab03c4b967b064fac00fa0d906"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afdcf71c6a16711a535971366558ea918"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">accept</a> (self, signal=None)</td></tr>
<tr class="separator:afdcf71c6a16711a535971366558ea918"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad99f80f17842220db5920e1926ff45a2"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">amount_radio_clicked</a> (self)</td></tr>
<tr class="separator:ad99f80f17842220db5920e1926ff45a2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7fb1b14fac066c36380036c6d3f3ab4a"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">spacing_radio_clicked</a> (self)</td></tr>
<tr class="separator:a7fb1b14fac066c36380036c6d3f3ab4a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr class="memitem:a24d363ab6c058ce4436a2b29e9c0b279"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a></td></tr>
<tr class="separator:a24d363ab6c058ce4436a2b29e9c0b279"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a499514a87885d4c9462e3c6dc314ec9c"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a></td></tr>
<tr class="separator:a499514a87885d4c9462e3c6dc314ec9c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acbe07c5ace61552cc4e4899b668d93e5"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#acbe07c5ace61552cc4e4899b668d93e5">form</a></td></tr>
<tr class="separator:acbe07c5ace61552cc4e4899b668d93e5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aae8fd4e66d675c566d0afcee0af2341f"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a></td></tr>
<tr class="separator:aae8fd4e66d675c566d0afcee0af2341f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock">
<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00105">105</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a0f978d5a751619f8ae7dfe178fb0473e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar._BentShapeRebarTaskPanel.__init__ </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>Rebar</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00106">106</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00106"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a0f978d5a751619f8ae7dfe178fb0473e">  106</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a0f978d5a751619f8ae7dfe178fb0473e">__init__</a>(self, Rebar = None):</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;        <span class="keywordflow">if</span> <span class="keywordflow">not</span> Rebar:</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;            selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00109"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">  109</a></span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a> = selected_obj.Object</div><div class="line"><a name="l00110"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">  110</a></span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a> = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a> = Rebar.Base.Support[0][1][0]</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a> = Rebar.Base.Support[0][0]</div><div class="line"><a name="l00114"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#acbe07c5ace61552cc4e4899b668d93e5">  114</a></span>&#160;        self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#acbe07c5ace61552cc4e4899b668d93e5">form</a> = FreeCADGui.PySideUic.loadUi(os.path.splitext(__file__)[0] + <span class="stringliteral">&quot;.ui&quot;</span>)</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;        self.form.setWindowTitle(QtGui.QApplication.translate(<span class="stringliteral">&quot;RebarAddon&quot;</span>, <span class="stringliteral">&quot;Bent Shape Rebar&quot;</span>, <span class="keywordtype">None</span>))</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;        self.form.orientation.addItems([<span class="stringliteral">&quot;Bottom&quot;</span>, <span class="stringliteral">&quot;Top&quot;</span>, <span class="stringliteral">&quot;Right&quot;</span>, <span class="stringliteral">&quot;Left&quot;</span>])</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;        self.form.amount_radio.clicked.connect(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">amount_radio_clicked</a>)</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;        self.form.spacing_radio.clicked.connect(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">spacing_radio_clicked</a>)</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;        self.form.customSpacing.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespaceRebarDistribution.html#aa547df5cb10d2e64eaa0b51c445fa30b">runRebarDistribution</a>(self))</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;        self.form.removeCustomSpacing.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespaceRebarDistribution.html#a85270a1b6e8c782a9e0ba54add518f2a">removeRebarDistribution</a>(self))</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;        self.form.PickSelectedFace.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespaceRebarfunc.html#a8c003df49ac5f249bd9ea4acfb7d2f8d">getSelectedFace</a>(self))</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;        self.form.orientation.currentIndexChanged.connect(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">getOrientation</a>)</div><div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;        self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + <span class="stringliteral">&quot;/icons/BentShapeRebar.svg&quot;</span>))</div><div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;        self.form.toolButton.setIcon(self.form.toolButton.style().standardIcon(QtGui.QStyle.SP_DialogHelpButton))</div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;        self.form.toolButton.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespacePopUpImage.html#a8c565620d7de9b4882a44eacb870ad05">showPopUpImageDialog</a>(os.path.split(os.path.abspath(__file__))[0] + <span class="stringliteral">&quot;/icons/BentShapeRebarDetailed.svg&quot;</span>))</div><div class="line"><a name="l00126"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">  126</a></span>&#160;        self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a> = Rebar</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_ab33579342d5fa4d4bf0bc8c9b9dfa526"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">BentShapeRebar._BentShapeRebarTaskPanel.getOrientation</a></div><div class="ttdeci">def getOrientation(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00128">BentShapeRebar.py:128</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_acbe07c5ace61552cc4e4899b668d93e5"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#acbe07c5ace61552cc4e4899b668d93e5">BentShapeRebar._BentShapeRebarTaskPanel.form</a></div><div class="ttdeci">form</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00114">BentShapeRebar.py:114</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a8c003df49ac5f249bd9ea4acfb7d2f8d"><div class="ttname"><a href="namespaceRebarfunc.html#a8c003df49ac5f249bd9ea4acfb7d2f8d">Rebarfunc.getSelectedFace</a></div><div class="ttdeci">def getSelectedFace(self)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00278">Rebarfunc.py:278</a></div></div>
<div class="ttc" id="namespaceRebarDistribution_html_aa547df5cb10d2e64eaa0b51c445fa30b"><div class="ttname"><a href="namespaceRebarDistribution.html#aa547df5cb10d2e64eaa0b51c445fa30b">RebarDistribution.runRebarDistribution</a></div><div class="ttdeci">def runRebarDistribution(self)</div><div class="ttdef"><b>Definition:</b> <a href="RebarDistribution_8py_source.html#l00098">RebarDistribution.py:98</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_ad99f80f17842220db5920e1926ff45a2"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">BentShapeRebar._BentShapeRebarTaskPanel.amount_radio_clicked</a></div><div class="ttdeci">def amount_radio_clicked(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00191">BentShapeRebar.py:191</a></div></div>
<div class="ttc" id="namespacePopUpImage_html_a8c565620d7de9b4882a44eacb870ad05"><div class="ttname"><a href="namespacePopUpImage.html#a8c565620d7de9b4882a44eacb870ad05">PopUpImage.showPopUpImageDialog</a></div><div class="ttdeci">def showPopUpImageDialog(img)</div><div class="ttdef"><b>Definition:</b> <a href="PopUpImage_8py_source.html#l00043">PopUpImage.py:43</a></div></div>
<div class="ttc" id="namespaceRebarDistribution_html_a85270a1b6e8c782a9e0ba54add518f2a"><div class="ttname"><a href="namespaceRebarDistribution.html#a85270a1b6e8c782a9e0ba54add518f2a">RebarDistribution.removeRebarDistribution</a></div><div class="ttdeci">def removeRebarDistribution(self)</div><div class="ttdef"><b>Definition:</b> <a href="RebarDistribution_8py_source.html#l00108">RebarDistribution.py:108</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a24d363ab6c058ce4436a2b29e9c0b279"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">BentShapeRebar._BentShapeRebarTaskPanel.SelectedObj</a></div><div class="ttdeci">SelectedObj</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00109">BentShapeRebar.py:109</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a499514a87885d4c9462e3c6dc314ec9c"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">BentShapeRebar._BentShapeRebarTaskPanel.FaceName</a></div><div class="ttdeci">FaceName</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00110">BentShapeRebar.py:110</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a0f978d5a751619f8ae7dfe178fb0473e"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a0f978d5a751619f8ae7dfe178fb0473e">BentShapeRebar._BentShapeRebarTaskPanel.__init__</a></div><div class="ttdeci">def __init__(self, Rebar=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00106">BentShapeRebar.py:106</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a7fb1b14fac066c36380036c6d3f3ab4a"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">BentShapeRebar._BentShapeRebarTaskPanel.spacing_radio_clicked</a></div><div class="ttdeci">def spacing_radio_clicked(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00195">BentShapeRebar.py:195</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_aae8fd4e66d675c566d0afcee0af2341f"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">BentShapeRebar._BentShapeRebarTaskPanel.Rebar</a></div><div class="ttdeci">Rebar</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00126">BentShapeRebar.py:126</a></div></div>
</div><!-- fragment -->
</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="afdcf71c6a16711a535971366558ea918"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar._BentShapeRebarTaskPanel.accept </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>signal</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00146">146</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00146"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">  146</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">accept</a>(self, signal = None):</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;        f_cover = self.form.frontCover.text()</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;        f_cover = FreeCAD.Units.Quantity(f_cover).Value</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;        b_cover = self.form.bottomCover.text()</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;        b_cover = FreeCAD.Units.Quantity(b_cover).Value</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;        l_cover = self.form.l_sideCover.text()</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;        l_cover = FreeCAD.Units.Quantity(l_cover).Value</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;        r_cover = self.form.r_sideCover.text()</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;        r_cover = FreeCAD.Units.Quantity(r_cover).Value</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;        t_cover = self.form.topCover.text()</div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;        t_cover = FreeCAD.Units.Quantity(t_cover).Value</div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;        bentLength = self.form.bentLength.text()</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;        bentLength = FreeCAD.Units.Quantity(bentLength).Value</div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;        bentAngle = self.form.bentAngle.value()</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;        diameter = self.form.diameter.text()</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;        diameter = FreeCAD.Units.Quantity(diameter).Value</div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;        rounding = self.form.rounding.value()</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;        orientation = self.form.orientation.currentText()</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;        amount_check = self.form.amount_radio.isChecked()</div><div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;        spacing_check = self.form.spacing_radio.isChecked()</div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;        <span class="keywordflow">if</span> <span class="keywordflow">not</span> self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a>:</div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;            <span class="keywordflow">if</span> amount_check:</div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;                amount = self.form.amount.value()</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;                rebar = <a class="code" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">makeBentShapeRebar</a>(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, <span class="keyword">True</span>, amount, orientation, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a>, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a>)</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;            <span class="keywordflow">elif</span> spacing_check:</div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;                spacing = self.form.spacing.text()</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;                spacing = FreeCAD.Units.Quantity(spacing).Value</div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;                rebar = <a class="code" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">makeBentShapeRebar</a>(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, <span class="keyword">False</span>, spacing, orientation, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a>, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a>)</div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;            <span class="keywordflow">if</span> amount_check:</div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;                amount = self.form.amount.value()</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;                rebar = <a class="code" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">editBentShapeRebar</a>(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a>, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, <span class="keyword">True</span>, amount, orientation, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a>, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a>)</div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;            <span class="keywordflow">elif</span> spacing_check:</div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;                spacing = self.form.spacing.text()</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;                spacing = FreeCAD.Units.Quantity(spacing).Value</div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;                rebar = <a class="code" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">editBentShapeRebar</a>(self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a>, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, <span class="keyword">False</span>, spacing, orientation, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">SelectedObj</a>, self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">FaceName</a>)</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;        <span class="keywordflow">if</span> self.CustomSpacing:</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;            rebar.CustomSpacing = self.CustomSpacing</div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;            FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;        self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">Rebar</a> = rebar</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;        <span class="keywordflow">if</span> signal == int(QtGui.QDialogButtonBox.Apply):</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;            <span class="keywordflow">pass</span></div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;            FreeCADGui.Control.closeDialog(self)</div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_afdcf71c6a16711a535971366558ea918"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">BentShapeRebar._BentShapeRebarTaskPanel.accept</a></div><div class="ttdeci">def accept(self, signal=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00146">BentShapeRebar.py:146</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_a941d005845cd497c0beb12bb8fef9171"><div class="ttname"><a href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">BentShapeRebar.editBentShapeRebar</a></div><div class="ttdeci">def editBentShapeRebar(Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00270">BentShapeRebar.py:270</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a24d363ab6c058ce4436a2b29e9c0b279"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a24d363ab6c058ce4436a2b29e9c0b279">BentShapeRebar._BentShapeRebarTaskPanel.SelectedObj</a></div><div class="ttdeci">SelectedObj</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00109">BentShapeRebar.py:109</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_aac46779d3e1905db5a3788917f6e2476"><div class="ttname"><a href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">BentShapeRebar.makeBentShapeRebar</a></div><div class="ttdeci">def makeBentShapeRebar(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation=&quot;Bottom Left&quot;, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00200">BentShapeRebar.py:200</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a499514a87885d4c9462e3c6dc314ec9c"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a499514a87885d4c9462e3c6dc314ec9c">BentShapeRebar._BentShapeRebarTaskPanel.FaceName</a></div><div class="ttdeci">FaceName</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00110">BentShapeRebar.py:110</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_aae8fd4e66d675c566d0afcee0af2341f"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#aae8fd4e66d675c566d0afcee0af2341f">BentShapeRebar._BentShapeRebarTaskPanel.Rebar</a></div><div class="ttdeci">Rebar</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00126">BentShapeRebar.py:126</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918_cgraph.png" border="0" usemap="#classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918_cgraph" alt=""/></div>
<map name="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918_cgraph" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918_cgraph">
<area shape="rect" id="node2" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476" title="BentShapeRebar.makeBentShape\lRebar" alt="" coords="249,16,471,58"/>
<area shape="rect" id="node6" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171" title="BentShapeRebar.editBentShape\lRebar" alt="" coords="255,82,465,123"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="781,24,960,50"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="519,24,733,50"/>
<area shape="rect" id="node5" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3" title="BentShapeRebar.getpoints\lOfBentShapeRebar" alt="" coords="537,75,715,116"/>
<area shape="rect" id="node7" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="543,192,709,218"/>
<area shape="rect" id="node8" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="803,192,939,218"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918_icgraph.png" border="0" usemap="#classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918_icgraph" alt=""/></div>
<map name="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918_icgraph" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_afdcf71c6a16711a535971366558ea918_icgraph">
<area shape="rect" id="node2" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906" title="BentShapeRebar._BentShape\lRebarTaskPanel.clicked" alt="" coords="259,5,455,47"/>
<area shape="rect" id="node3" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce" title="HelicalRebar._HelicalRebar\lTaskPanel.clicked" alt="" coords="266,71,449,112"/>
<area shape="rect" id="node4" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="262,136,453,177"/>
<area shape="rect" id="node5" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="249,201,465,243"/>
<area shape="rect" id="node6" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="249,267,465,294"/>
<area shape="rect" id="node7" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="261,319,454,360"/>
<area shape="rect" id="node8" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="259,384,456,425"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ad99f80f17842220db5920e1926ff45a2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar._BentShapeRebarTaskPanel.amount_radio_clicked </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00191">191</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00191"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">  191</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">amount_radio_clicked</a>(self):</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;        self.form.spacing.setEnabled(<span class="keyword">False</span>)</div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;        self.form.amount.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_ad99f80f17842220db5920e1926ff45a2"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ad99f80f17842220db5920e1926ff45a2">BentShapeRebar._BentShapeRebarTaskPanel.amount_radio_clicked</a></div><div class="ttdeci">def amount_radio_clicked(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00191">BentShapeRebar.py:191</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="ae92dd6ab03c4b967b064fac00fa0d906"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar._BentShapeRebarTaskPanel.clicked </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>button</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00142">142</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00142"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906">  142</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906">clicked</a>(self, button):</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;        <span class="keywordflow">if</span> button == int(QtGui.QDialogButtonBox.Apply):</div><div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;            self.<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">accept</a>(button)</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_afdcf71c6a16711a535971366558ea918"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918">BentShapeRebar._BentShapeRebarTaskPanel.accept</a></div><div class="ttdeci">def accept(self, signal=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00146">BentShapeRebar.py:146</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_ae92dd6ab03c4b967b064fac00fa0d906"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906">BentShapeRebar._BentShapeRebarTaskPanel.clicked</a></div><div class="ttdeci">def clicked(self, button)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00142">BentShapeRebar.py:142</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ae92dd6ab03c4b967b064fac00fa0d906_cgraph.png" border="0" usemap="#classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ae92dd6ab03c4b967b064fac00fa0d906_cgraph" alt=""/></div>
<map name="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ae92dd6ab03c4b967b064fac00fa0d906_cgraph" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_ae92dd6ab03c4b967b064fac00fa0d906_cgraph">
<area shape="rect" id="node2" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918" title="BentShapeRebar._BentShape\lRebarTaskPanel.accept" alt="" coords="249,50,445,91"/>
<area shape="rect" id="node3" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476" title="BentShapeRebar.makeBentShape\lRebar" alt="" coords="493,16,715,58"/>
<area shape="rect" id="node7" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171" title="BentShapeRebar.editBentShape\lRebar" alt="" coords="499,82,709,123"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="1025,24,1204,50"/>
<area shape="rect" id="node5" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="763,24,977,50"/>
<area shape="rect" id="node6" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3" title="BentShapeRebar.getpoints\lOfBentShapeRebar" alt="" coords="781,75,959,116"/>
<area shape="rect" id="node8" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="787,192,953,218"/>
<area shape="rect" id="node9" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="1047,192,1183,218"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ab33579342d5fa4d4bf0bc8c9b9dfa526"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar._BentShapeRebarTaskPanel.getOrientation </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00128">128</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00128"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">  128</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">getOrientation</a>(self):</div><div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;        orientation = self.form.orientation.currentText()</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;        <span class="comment">#if orientation == &quot;Bottom&quot;:</span></div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;        <span class="comment">#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + &quot;/icons/LShapeRebarBR.svg&quot;))</span></div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;        <span class="comment">#elif orientation == &quot;Top&quot;:</span></div><div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;        <span class="comment">#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + &quot;/icons/LShapeRebarBL.svg&quot;))</span></div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;        <span class="comment">#elif orientation == &quot;Right&quot;:</span></div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;        <span class="comment">#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + &quot;/icons/LShapeRebarTR.svg&quot;))</span></div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;        <span class="comment">#else:</span></div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;        <span class="comment">#    self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + &quot;/icons/LShapeRebarTL.svg&quot;))</span></div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_ab33579342d5fa4d4bf0bc8c9b9dfa526"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ab33579342d5fa4d4bf0bc8c9b9dfa526">BentShapeRebar._BentShapeRebarTaskPanel.getOrientation</a></div><div class="ttdeci">def getOrientation(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00128">BentShapeRebar.py:128</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="af363d8287c33547f2b7fc6f6f326d47a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar._BentShapeRebarTaskPanel.getStandardButtons </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00139">139</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00139"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#af363d8287c33547f2b7fc6f6f326d47a">  139</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#af363d8287c33547f2b7fc6f6f326d47a">getStandardButtons</a>(self):</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;        <span class="keywordflow">return</span> int(QtGui.QDialogButtonBox.Ok) | int(QtGui.QDialogButtonBox.Apply) | int(QtGui.QDialogButtonBox.Cancel)</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_af363d8287c33547f2b7fc6f6f326d47a"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#af363d8287c33547f2b7fc6f6f326d47a">BentShapeRebar._BentShapeRebarTaskPanel.getStandardButtons</a></div><div class="ttdeci">def getStandardButtons(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00139">BentShapeRebar.py:139</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a7fb1b14fac066c36380036c6d3f3ab4a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar._BentShapeRebarTaskPanel.spacing_radio_clicked </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00195">195</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00195"></a><span class="lineno"><a class="line" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">  195</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">spacing_radio_clicked</a>(self):</div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;        self.form.amount.setEnabled(<span class="keyword">False</span>)</div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;        self.form.spacing.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;</div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html_a7fb1b14fac066c36380036c6d3f3ab4a"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#a7fb1b14fac066c36380036c6d3f3ab4a">BentShapeRebar._BentShapeRebarTaskPanel.spacing_radio_clicked</a></div><div class="ttdeci">def spacing_radio_clicked(self)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00195">BentShapeRebar.py:195</a></div></div>
</div><!-- fragment -->
</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a499514a87885d4c9462e3c6dc314ec9c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">BentShapeRebar._BentShapeRebarTaskPanel.FaceName</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00110">110</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="acbe07c5ace61552cc4e4899b668d93e5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">BentShapeRebar._BentShapeRebarTaskPanel.form</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00114">114</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="aae8fd4e66d675c566d0afcee0af2341f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">BentShapeRebar._BentShapeRebarTaskPanel.Rebar</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00126">126</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="a24d363ab6c058ce4436a2b29e9c0b279"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">BentShapeRebar._BentShapeRebarTaskPanel.SelectedObj</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00109">109</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a></li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Wed Dec 13 2017 22:36:42 for Rebar Addon for FreeCAD by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.11
</small></address>
</body>
</html>
