<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Rebar Addon for FreeCAD: HelicalRebar.py Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Rebar Addon for FreeCAD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li class="current"><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.html"><span>File&#160;List</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">HelicalRebar.py</div>  </div>
</div><!--header-->
<div class="contents">
<a href="HelicalRebar_8py.html">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html">    1</a></span>&#160;<span class="comment"># -*- coding: utf-8 -*-</span></div><div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="comment"># ***************************************************************************</span></div><div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="comment"># *   Copyright (c) 2017 - Amritpal Singh &lt;amrit3701@gmail.com&gt;             *</span></div><div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="comment"># *   This program is free software; you can redistribute it and/or modify  *</span></div><div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="comment"># *   it under the terms of the GNU Lesser General Public License (LGPL)    *</span></div><div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="comment"># *   as published by the Free Software Foundation; either version 2 of     *</span></div><div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="comment"># *   the License, or (at your option) any later version.                   *</span></div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="comment"># *   for detail see the LICENCE text file.                                 *</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="comment"># *   This program is distributed in the hope that it will be useful,       *</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="comment"># *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *</span></div><div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="comment"># *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *</span></div><div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="comment"># *   GNU Library General Public License for more details.                  *</span></div><div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="comment"># *   You should have received a copy of the GNU Library General Public     *</span></div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="comment"># *   License along with this program; if not, write to the Free Software   *</span></div><div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="comment"># *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *</span></div><div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="comment"># *   USA                                                                   *</span></div><div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;<span class="comment"># *                                                                         *</span></div><div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;<span class="comment"># ***************************************************************************</span></div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;</div><div class="line"><a name="l00024"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a28c95505364eadd0c2d4abbd80091bef">   24</a></span>&#160;__title__ = <span class="stringliteral">&quot;HelicalRebar&quot;</span></div><div class="line"><a name="l00025"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a925dcfed2ffef215413157f48d7b6e57">   25</a></span>&#160;__author__ = <span class="stringliteral">&quot;Amritpal Singh&quot;</span></div><div class="line"><a name="l00026"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a9c74e4634d00eef07ed630054e69fbff">   26</a></span>&#160;__url__ = <span class="stringliteral">&quot;https://www.freecadweb.org&quot;</span></div><div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;</div><div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;<span class="keyword">from</span> PySide <span class="keyword">import</span> QtCore, QtGui</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;<span class="keyword">from</span> Rebarfunc <span class="keyword">import</span> *</div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;<span class="keyword">from</span> PySide.QtCore <span class="keyword">import</span> QT_TRANSLATE_NOOP</div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;<span class="keyword">from</span> PopUpImage <span class="keyword">import</span> showPopUpImageDialog</div><div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;<span class="keyword">import</span> FreeCAD</div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;<span class="keyword">import</span> FreeCADGui</div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;<span class="keyword">import</span> ArchCommands</div><div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;<span class="keyword">import</span> os</div><div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;<span class="keyword">import</span> sys</div><div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;<span class="keyword">import</span> math</div><div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;</div><div class="line"><a name="l00039"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a4fcf2dabc065c39ce5c8cf6995051352">   39</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#a4fcf2dabc065c39ce5c8cf6995051352">getpointsOfHelicalRebar</a>(FacePRM, s_cover, b_cover, t_cover, pitch, edges, diameter, size, direction):</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; getpointsOfHelicalRebar(FacePRM, s_cover, b_cover, t_cover):</span></div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;<span class="stringliteral">    Return points of the LShape rebar in the form of array for sketch.&quot;&quot;&quot;</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;    dx = s_cover + diameter / 2</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;    dz = float(pitch) / edges</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;    R = diameter / 2 - dx</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    R = FacePRM[0][0] / 2 - s_cover</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;    points = []</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;    <span class="keywordflow">if</span> direction[2] <span class="keywordflow">in</span> {-1,1}:</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        z = 0</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        l = 0</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        <span class="keywordflow">if</span> direction[2] == 1:</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;            zz = FacePRM[1][2] - t_cover</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;        <span class="keywordflow">elif</span> direction[2] == -1:</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;            zz = FacePRM[1][2] + b_cover</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;        count = 0</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;        flag = <span class="keyword">False</span></div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        <span class="keywordflow">while</span> (round(z) &lt; abs(size - b_cover - t_cover)):</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;            <span class="keywordflow">for</span> i <span class="keywordflow">in</span> range(0, int(edges) + 1):</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                <span class="keywordflow">if</span> <span class="keywordflow">not</span> i <span class="keywordflow">and</span> flag:</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                    <span class="keywordflow">continue</span></div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;                <span class="keywordflow">if</span> <span class="keywordflow">not</span> flag:</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                    z -= dz</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                    flag = <span class="keyword">True</span></div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                iAngle = i * 360 / edges</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;                x =  FacePRM[1][0] + R * math.cos(math.radians(iAngle))</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                y =  FacePRM[1][1] + R * math.sin(math.radians(iAngle))</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                points.append(FreeCAD.Vector(x, y, zz))</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                count += 1</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;                <span class="keywordflow">if</span> direction[2] == 1:</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                    zz -= dz</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                <span class="keywordflow">elif</span> direction[2] == -1:</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;                    zz += dz</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                z += dz</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;    <span class="keywordflow">return</span> points</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="line"><a name="l00075"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">   75</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">createHelicalWire</a>(FacePRM, s_cover, b_cover, t_cover, pitch, size, direction, helix = None):</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; createHelicalWire(FacePRM, SideCover, BottomCover, TopCover, Pitch, Size, Direction, Helix = None):</span></div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;<span class="stringliteral">    It creates a helical wire.&quot;&quot;&quot;</span></div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;    <span class="keyword">import</span> Part</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> helix:</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;        helix = FreeCAD.ActiveDocument.addObject(<span class="stringliteral">&quot;Part::Helix&quot;</span>,<span class="stringliteral">&quot;Helix&quot;</span>)</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;    helix.Pitch = pitch</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;    helix.Radius = FacePRM[0][0] / 2 - s_cover</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;    helix.Angle = 0</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;    helix.LocalCoord = 0</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;    helix.Height = size - b_cover - t_cover</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;    <span class="keywordflow">if</span> round(direction.x) == 1:</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0] - b_cover, FacePRM[1][1], FacePRM[1][2])</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(0, -1, 0), 90)</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;    <span class="keywordflow">elif</span> round(direction.x) == -1:</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0] + t_cover, FacePRM[1][1], FacePRM[1][2])</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(0, -1, 0), -90)</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;    <span class="keywordflow">elif</span> round(direction.y) == 1:</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0], FacePRM[1][1] - b_cover, FacePRM[1][2])</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(1, 0, 0), 90)</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;    <span class="keywordflow">elif</span> round(direction.y) == -1:</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0], FacePRM[1][1] + t_cover, FacePRM[1][2])</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(-1, 0, 0), 90)</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;    <span class="keywordflow">elif</span> round(direction.z) == 1:</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0], FacePRM[1][1], FacePRM[1][2] - size + b_cover)</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(0, 0, 1), 0)</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;    <span class="keywordflow">elif</span> round(direction.z) == -1:</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0], FacePRM[1][1], FacePRM[1][2] + b_cover)</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(0, 0, -1), 0)</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;    <span class="keywordflow">return</span> helix</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;</div><div class="line"><a name="l00107"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">  107</a></span>&#160;<span class="keyword">class </span><a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">_HelicalRebarTaskPanel</a>:</div><div class="line"><a name="l00108"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a1bc9ff9f8e2cdbf9f12d974dd77c8e24">  108</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a1bc9ff9f8e2cdbf9f12d974dd77c8e24">__init__</a>(self, Rebar = None):</div><div class="line"><a name="l00109"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#abfda021716a5b0cd386be846e989ea5f">  109</a></span>&#160;        self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#abfda021716a5b0cd386be846e989ea5f">form</a> = FreeCADGui.PySideUic.loadUi(os.path.splitext(__file__)[0] + <span class="stringliteral">&quot;.ui&quot;</span>)</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;        self.form.setWindowTitle(QtGui.QApplication.translate(<span class="stringliteral">&quot;Arch&quot;</span>, <span class="stringliteral">&quot;Helical Rebar&quot;</span>, <span class="keywordtype">None</span>))</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;        <span class="keywordflow">if</span> <span class="keywordflow">not</span> Rebar:</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;            normal = <a class="code" href="namespaceRebarfunc.html#a3a8c123c290609baec3a547c20a561b9">facenormalDirection</a>()</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;            normal = <a class="code" href="namespaceRebarfunc.html#a3a8c123c290609baec3a547c20a561b9">facenormalDirection</a>(Rebar.Base.Support[0][0], Rebar.Base.Support[0][1][0])</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;        <span class="keywordflow">if</span> <span class="keywordflow">not</span> round(normal.z) <span class="keywordflow">in</span> {1, -1}:</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;            self.form.topCoverLabel.setText(<a class="code" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937">translate</a>(<span class="stringliteral">&quot;RebarAddon&quot;</span>, <span class="stringliteral">&quot;Left Cover&quot;</span>))</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;            self.form.bottomCoverLabel.setText(<a class="code" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937">translate</a>(<span class="stringliteral">&quot;RebarAddon&quot;</span>, <span class="stringliteral">&quot;Right Cover&quot;</span>))</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;        self.form.PickSelectedFace.clicked.connect(self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#aea514ce88bde89c57ab88576e7a27230">getSelectedFace</a>)</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;        self.form.image.setPixmap(QtGui.QPixmap(os.path.split(os.path.abspath(__file__))[0] + <span class="stringliteral">&quot;/icons/HelicalRebar.svg&quot;</span>))</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;        self.form.toolButton.clicked.connect(<span class="keyword">lambda</span>: <a class="code" href="namespacePopUpImage.html#a8c565620d7de9b4882a44eacb870ad05">showPopUpImageDialog</a>(os.path.split(os.path.abspath(__file__))[0] + <span class="stringliteral">&quot;/icons/HelicalRebarDetailed.svg&quot;</span>))</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;        self.form.toolButton.setIcon(self.form.toolButton.style().standardIcon(QtGui.QStyle.SP_DialogHelpButton))</div><div class="line"><a name="l00122"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a18e1b46858c6d4ca5f6925d69ea15807">  122</a></span>&#160;        self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a18e1b46858c6d4ca5f6925d69ea15807">Rebar</a> = Rebar</div><div class="line"><a name="l00123"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a6666e765dc0ac4e8bd4d5c1825862795">  123</a></span>&#160;        self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a6666e765dc0ac4e8bd4d5c1825862795">SelectedObj</a> = <span class="keywordtype">None</span></div><div class="line"><a name="l00124"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ac6f5e0df8c90110fdcb82cb9725ae6b6">  124</a></span>&#160;        self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ac6f5e0df8c90110fdcb82cb9725ae6b6">FaceName</a> = <span class="keywordtype">None</span></div><div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;</div><div class="line"><a name="l00126"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#aef7b43bb1c81a0d21bd80cfbe56229bf">  126</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#aef7b43bb1c81a0d21bd80cfbe56229bf">getStandardButtons</a>(self):</div><div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;        <span class="keywordflow">return</span> int(QtGui.QDialogButtonBox.Ok) | int(QtGui.QDialogButtonBox.Apply) | int(QtGui.QDialogButtonBox.Cancel)</div><div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;</div><div class="line"><a name="l00129"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce">  129</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce">clicked</a>(self, button):</div><div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;        <span class="keywordflow">if</span> button == int(QtGui.QDialogButtonBox.Apply):</div><div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;            self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#acdfb101876d4841ba277e2e884ebaf9d">accept</a>(button)</div><div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;</div><div class="line"><a name="l00133"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#aea514ce88bde89c57ab88576e7a27230">  133</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#aea514ce88bde89c57ab88576e7a27230">getSelectedFace</a>(self):</div><div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;        <a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#aea514ce88bde89c57ab88576e7a27230">getSelectedFace</a>(self)</div><div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;        normal = <a class="code" href="namespaceRebarfunc.html#a3a8c123c290609baec3a547c20a561b9">facenormalDirection</a>()</div><div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;        <span class="keywordflow">if</span> <span class="keywordflow">not</span> round(normal.z) <span class="keywordflow">in</span> {1, -1}:</div><div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;            self.form.topCoverLabel.setText(<a class="code" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937">translate</a>(<span class="stringliteral">&quot;RebarAddon&quot;</span>, <span class="stringliteral">&quot;Left Cover&quot;</span>))</div><div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;            self.form.bottomCoverLabel.setText(<a class="code" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937">translate</a>(<span class="stringliteral">&quot;RebarAddon&quot;</span>, <span class="stringliteral">&quot;Right Cover&quot;</span>))</div><div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;            self.form.topCoverLabel.setText(<a class="code" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937">translate</a>(<span class="stringliteral">&quot;RebarAddon&quot;</span>, <span class="stringliteral">&quot;Top Cover&quot;</span>))</div><div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;            self.form.bottomCoverLabel.setText(<a class="code" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937">translate</a>(<span class="stringliteral">&quot;RebarAddon&quot;</span>, <span class="stringliteral">&quot;Bottom Cover&quot;</span>))</div><div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;</div><div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;</div><div class="line"><a name="l00144"></a><span class="lineno"><a class="line" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#acdfb101876d4841ba277e2e884ebaf9d">  144</a></span>&#160;    <span class="keyword">def </span><a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#acdfb101876d4841ba277e2e884ebaf9d">accept</a>(self, signal = None):</div><div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;        b_cover = self.form.bottomCover.text()</div><div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;        b_cover = FreeCAD.Units.Quantity(b_cover).Value</div><div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;        s_cover = self.form.sideCover.text()</div><div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;        s_cover = FreeCAD.Units.Quantity(s_cover).Value</div><div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;        t_cover = self.form.topCover.text()</div><div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;        t_cover = FreeCAD.Units.Quantity(t_cover).Value</div><div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;        pitch = self.form.pitch.text()</div><div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;        pitch = FreeCAD.Units.Quantity(pitch).Value</div><div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;        diameter = self.form.diameter.text()</div><div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;        diameter = FreeCAD.Units.Quantity(diameter).Value</div><div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;        <span class="keywordflow">if</span> <span class="keywordflow">not</span> self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a18e1b46858c6d4ca5f6925d69ea15807">Rebar</a>:</div><div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;            rebar = <a class="code" href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08">makeHelicalRebar</a>(s_cover, b_cover, diameter, t_cover, pitch, self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a6666e765dc0ac4e8bd4d5c1825862795">SelectedObj</a>, self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ac6f5e0df8c90110fdcb82cb9725ae6b6">FaceName</a>)</div><div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;            rebar = <a class="code" href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b">editHelicalRebar</a>(self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a18e1b46858c6d4ca5f6925d69ea15807">Rebar</a>, s_cover, b_cover, diameter, t_cover, pitch, self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a6666e765dc0ac4e8bd4d5c1825862795">SelectedObj</a>, self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ac6f5e0df8c90110fdcb82cb9725ae6b6">FaceName</a>)</div><div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;        self.<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a18e1b46858c6d4ca5f6925d69ea15807">Rebar</a> = rebar</div><div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;        <span class="keywordflow">if</span> signal == int(QtGui.QDialogButtonBox.Apply):</div><div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;            <span class="keywordflow">pass</span></div><div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;        <span class="keywordflow">else</span>:</div><div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;            FreeCADGui.Control.closeDialog(self)</div><div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;</div><div class="line"><a name="l00165"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08">  165</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08">makeHelicalRebar</a>(s_cover, b_cover, diameter, t_cover, pitch, structure = None, facename = None):</div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; makeHelicalRebar(SideCover, BottomCover, Diameter, TopCover, Pitch, Structure, Facename):</span></div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;<span class="stringliteral">    Adds the Helical reinforcement bar to the selected structural object.&quot;&quot;&quot;</span></div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> structure <span class="keywordflow">and</span> <span class="keywordflow">not</span> facename:</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;        selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;        structure = selected_obj.Object</div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;        facename = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename, <span class="keyword">False</span>)</div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> FacePRM:</div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;        FreeCAD.Console.PrintError(<span class="stringliteral">&quot;Cannot identified shape or from which base object sturctural element is derived\n&quot;</span>)</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;    size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;    normal = face.normalAt(0,0)</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    <span class="comment">#normal = face.Placement.Rotation.inverted().multVec(normal)</span></div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;    <span class="keyword">import</span> Arch</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;    helix = <a class="code" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">createHelicalWire</a>(FacePRM, s_cover, b_cover, t_cover, pitch, size, normal)</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;    helix.Support = [(structure, facename)]</div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;    rebar = Arch.makeRebar(structure, helix, diameter, 1, 0)</div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;    rebar.OffsetStart = 0</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    rebar.OffsetEnd = 0</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;    <span class="comment"># Adds properties to the rebar object</span></div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;    rebar.ViewObject.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;RebarShape&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).RebarShape = <span class="stringliteral">&quot;HelicalRebar&quot;</span></div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;    rebar.ViewObject.setEditorMode(<span class="stringliteral">&quot;RebarShape&quot;</span>, 2)</div><div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;SideCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Front cover of rebar&quot;</span>)).SideCover = s_cover</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;SideCover&quot;</span>, 2)</div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;Pitch&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Left Side cover of rebar&quot;</span>)).Pitch = pitch</div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;Pitch&quot;</span>, 2)</div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BottomCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bottom cover of rebar&quot;</span>)).BottomCover = b_cover</div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BottomCover&quot;</span>, 2)</div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TopCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Top cover of rebar&quot;</span>)).TopCover = t_cover</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TopCover&quot;</span>, 2)</div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;    rebar.Label = <span class="stringliteral">&quot;HelicalRebar&quot;</span></div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;    <span class="keywordflow">return</span> rebar</div><div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;</div><div class="line"><a name="l00203"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b">  203</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b">editHelicalRebar</a>(Rebar, s_cover, b_cover, diameter, t_cover, pitch, structure = None, facename = None):</div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;    sketch = Rebar.Base</div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;    <span class="keywordflow">if</span> structure <span class="keywordflow">and</span> facename:</div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;        sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;    <span class="comment"># Check if sketch support is empty.</span></div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> sketch.Support:</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;        <a class="code" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">showWarning</a>(<span class="stringliteral">&quot;You have checked remove external geometry of base sketchs when needed.\nTo unchecked Edit-&gt;Preferences-&gt;Arch.&quot;</span>)</div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;    <span class="comment"># Assigned values</span></div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    facename = sketch.Support[0][1][0]</div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;    structure = sketch.Support[0][0]</div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;    <span class="comment"># Get parameters of the face where sketch of rebar is drawn</span></div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename, <span class="keyword">False</span>)</div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    normal = face.normalAt(0,0)</div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    <span class="comment">#normal = face.Placement.Rotation.inverted().multVec(normal)</span></div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    helix = <a class="code" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">createHelicalWire</a>(FacePRM, s_cover, b_cover, t_cover, pitch, size, normal, Rebar.Base)</div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    Rebar.Diameter = diameter</div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    Rebar.SideCover = s_cover</div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;    Rebar.BottomCover = b_cover</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;    Rebar.TopCover = t_cover</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;    Rebar.Pitch = pitch</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;    <span class="keywordflow">return</span> Rebar</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;</div><div class="line"><a name="l00231"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#ab9725ab4f1e5650133dba94c24907331">  231</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#ab9725ab4f1e5650133dba94c24907331">editDialog</a>(vobj):</div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;    FreeCADGui.Control.closeDialog()</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    obj = <a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">_HelicalRebarTaskPanel</a>(vobj.Object)</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;    obj.form.sideCover.setText(str(vobj.Object.SideCover))</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;    obj.form.bottomCover.setText(str(vobj.Object.BottomCover))</div><div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;    obj.form.diameter.setText(str(vobj.Object.Diameter))</div><div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;    obj.form.topCover.setText(str(vobj.Object.TopCover))</div><div class="line"><a name="l00238"></a><span class="lineno">  238</span>&#160;    obj.form.pitch.setText(str(vobj.Object.Pitch))</div><div class="line"><a name="l00239"></a><span class="lineno">  239</span>&#160;    FreeCADGui.Control.showDialog(obj)</div><div class="line"><a name="l00240"></a><span class="lineno">  240</span>&#160;</div><div class="line"><a name="l00241"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#ad8ff0caf1e8a56ac47ce25062db8bc46">  241</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#ad8ff0caf1e8a56ac47ce25062db8bc46">CommandHelicalRebar</a>():</div><div class="line"><a name="l00242"></a><span class="lineno">  242</span>&#160;    selected_obj = <a class="code" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">check_selected_face</a>()</div><div class="line"><a name="l00243"></a><span class="lineno">  243</span>&#160;    <span class="keywordflow">if</span> selected_obj:</div><div class="line"><a name="l00244"></a><span class="lineno">  244</span>&#160;        FreeCADGui.Control.showDialog(<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">_HelicalRebarTaskPanel</a>())</div><div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_ab0b70379d225d10e3585478005fc53ce"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce">HelicalRebar._HelicalRebarTaskPanel.clicked</a></div><div class="ttdeci">def clicked(self, button)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00129">HelicalRebar.py:129</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_adae2713855a7e1b4bda04081ae671542"><div class="ttname"><a href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">Rebarfunc.check_selected_face</a></div><div class="ttdeci">def check_selected_face()</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00255">Rebarfunc.py:255</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_aea514ce88bde89c57ab88576e7a27230"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#aea514ce88bde89c57ab88576e7a27230">HelicalRebar._HelicalRebarTaskPanel.getSelectedFace</a></div><div class="ttdeci">def getSelectedFace(self)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00133">HelicalRebar.py:133</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_ad8ff0caf1e8a56ac47ce25062db8bc46"><div class="ttname"><a href="namespaceHelicalRebar.html#ad8ff0caf1e8a56ac47ce25062db8bc46">HelicalRebar.CommandHelicalRebar</a></div><div class="ttdeci">def CommandHelicalRebar()</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00241">HelicalRebar.py:241</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_acdfb101876d4841ba277e2e884ebaf9d"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#acdfb101876d4841ba277e2e884ebaf9d">HelicalRebar._HelicalRebarTaskPanel.accept</a></div><div class="ttdeci">def accept(self, signal=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00144">HelicalRebar.py:144</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">HelicalRebar._HelicalRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00107">HelicalRebar.py:107</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_abfda021716a5b0cd386be846e989ea5f"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#abfda021716a5b0cd386be846e989ea5f">HelicalRebar._HelicalRebarTaskPanel.form</a></div><div class="ttdeci">form</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00109">HelicalRebar.py:109</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_a1bc9ff9f8e2cdbf9f12d974dd77c8e24"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a1bc9ff9f8e2cdbf9f12d974dd77c8e24">HelicalRebar._HelicalRebarTaskPanel.__init__</a></div><div class="ttdeci">def __init__(self, Rebar=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00108">HelicalRebar.py:108</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_a18e1b46858c6d4ca5f6925d69ea15807"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a18e1b46858c6d4ca5f6925d69ea15807">HelicalRebar._HelicalRebarTaskPanel.Rebar</a></div><div class="ttdeci">Rebar</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00122">HelicalRebar.py:122</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_ab9725ab4f1e5650133dba94c24907331"><div class="ttname"><a href="namespaceHelicalRebar.html#ab9725ab4f1e5650133dba94c24907331">HelicalRebar.editDialog</a></div><div class="ttdeci">def editDialog(vobj)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00231">HelicalRebar.py:231</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_aea0d3838b1b171f801acf1046d111c8b"><div class="ttname"><a href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b">HelicalRebar.editHelicalRebar</a></div><div class="ttdeci">def editHelicalRebar(Rebar, s_cover, b_cover, diameter, t_cover, pitch, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00203">HelicalRebar.py:203</a></div></div>
<div class="ttc" id="namespacePopUpImage_html_a8c565620d7de9b4882a44eacb870ad05"><div class="ttname"><a href="namespacePopUpImage.html#a8c565620d7de9b4882a44eacb870ad05">PopUpImage.showPopUpImageDialog</a></div><div class="ttdeci">def showPopUpImageDialog(img)</div><div class="ttdef"><b>Definition:</b> <a href="PopUpImage_8py_source.html#l00043">PopUpImage.py:43</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a2278a0602d46a62953af1fcf2e574a94"><div class="ttname"><a href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">Rebarfunc.showWarning</a></div><div class="ttdeci">def showWarning(message)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00293">Rebarfunc.py:293</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a1467a55852e36c36c472e222855bb937"><div class="ttname"><a href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937">Rebarfunc.translate</a></div><div class="ttdeci">def translate(context, text, disambig=None)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00303">Rebarfunc.py:303</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_ac6f5e0df8c90110fdcb82cb9725ae6b6"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ac6f5e0df8c90110fdcb82cb9725ae6b6">HelicalRebar._HelicalRebarTaskPanel.FaceName</a></div><div class="ttdeci">FaceName</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00124">HelicalRebar.py:124</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_a6666e765dc0ac4e8bd4d5c1825862795"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#a6666e765dc0ac4e8bd4d5c1825862795">HelicalRebar._HelicalRebarTaskPanel.SelectedObj</a></div><div class="ttdeci">SelectedObj</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00123">HelicalRebar.py:123</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a3a8c123c290609baec3a547c20a561b9"><div class="ttname"><a href="namespaceRebarfunc.html#a3a8c123c290609baec3a547c20a561b9">Rebarfunc.facenormalDirection</a></div><div class="ttdeci">def facenormalDirection(structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00081">Rebarfunc.py:81</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_a8a4f12ed70819996ac31877957dfab08"><div class="ttname"><a href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08">HelicalRebar.makeHelicalRebar</a></div><div class="ttdeci">def makeHelicalRebar(s_cover, b_cover, diameter, t_cover, pitch, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00165">HelicalRebar.py:165</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html_aef7b43bb1c81a0d21bd80cfbe56229bf"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#aef7b43bb1c81a0d21bd80cfbe56229bf">HelicalRebar._HelicalRebarTaskPanel.getStandardButtons</a></div><div class="ttdeci">def getStandardButtons(self)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00126">HelicalRebar.py:126</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_a4fcf2dabc065c39ce5c8cf6995051352"><div class="ttname"><a href="namespaceHelicalRebar.html#a4fcf2dabc065c39ce5c8cf6995051352">HelicalRebar.getpointsOfHelicalRebar</a></div><div class="ttdeci">def getpointsOfHelicalRebar(FacePRM, s_cover, b_cover, t_cover, pitch, edges, diameter, size, direction)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00039">HelicalRebar.py:39</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_a1a2b3ce39b904ab0c3892ed0965d2844"><div class="ttname"><a href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">HelicalRebar.createHelicalWire</a></div><div class="ttdeci">def createHelicalWire(FacePRM, s_cover, b_cover, t_cover, pitch, size, direction, helix=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00075">HelicalRebar.py:75</a></div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Wed Dec 13 2017 22:36:42 for Rebar Addon for FreeCAD by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.11
</small></address>
</body>
</html>
