<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Rebar Addon for FreeCAD: Stirrup Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Rebar Addon for FreeCAD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="namespaces.html"><span>Namespace&#160;List</span></a></li>
      <li><a href="namespacemembers.html"><span>Namespace&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">Stirrup Namespace Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classStirrup_1_1__StirrupTaskPanel.html">_StirrupTaskPanel</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:aa6df5118806bfe9d3a799e1bf549bb0a"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a">getpointsOfStirrup</a> (FacePRM, l_cover, r_cover, t_cover, b_cover, bentAngle, bentFactor, diameter, rounding, facenormal)</td></tr>
<tr class="separator:aa6df5118806bfe9d3a799e1bf549bb0a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a705fc121e2af9c8ac05eb299f4fb9f2f"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStirrup.html#a705fc121e2af9c8ac05eb299f4fb9f2f">makeStirrup</a> (l_cover, r_cover, t_cover, b_cover, f_cover, bentAngle, bentFactor, diameter, rounding, amount_spacing_check, amount_spacing_value, structure=None, facename=None)</td></tr>
<tr class="separator:a705fc121e2af9c8ac05eb299f4fb9f2f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1f6d278ace7fe116895dba342e2a3573"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStirrup.html#a1f6d278ace7fe116895dba342e2a3573">editStirrup</a> (Rebar, l_cover, r_cover, t_cover, b_cover, f_cover, bentAngle, bentFactor, diameter, rounding, amount_spacing_check, amount_spacing_value, structure=None, facename=None)</td></tr>
<tr class="separator:a1f6d278ace7fe116895dba342e2a3573"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8ebd17322b7f4f5fe9e50bd578ba670d"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStirrup.html#a8ebd17322b7f4f5fe9e50bd578ba670d">editDialog</a> (vobj)</td></tr>
<tr class="separator:a8ebd17322b7f4f5fe9e50bd578ba670d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3863ce61c716794557101a50f41597b5"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStirrup.html#a3863ce61c716794557101a50f41597b5">CommandStirrup</a> ()</td></tr>
<tr class="separator:a3863ce61c716794557101a50f41597b5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:aac4f16b6285f67fb07673ac264bac3dc"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStirrup.html#aac4f16b6285f67fb07673ac264bac3dc">__title__</a> = &quot;StirrupRebar&quot;</td></tr>
<tr class="separator:aac4f16b6285f67fb07673ac264bac3dc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad470a52dca49f918ddfef810e749291c"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStirrup.html#ad470a52dca49f918ddfef810e749291c">__author__</a> = &quot;Amritpal Singh&quot;</td></tr>
<tr class="separator:ad470a52dca49f918ddfef810e749291c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3b5b07aa3d0183155a2be24e2d0d4a82"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStirrup.html#a3b5b07aa3d0183155a2be24e2d0d4a82">__url__</a> = &quot;https://www.freecadweb.org&quot;</td></tr>
<tr class="separator:a3b5b07aa3d0183155a2be24e2d0d4a82"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a3863ce61c716794557101a50f41597b5"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def Stirrup.CommandStirrup </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="Stirrup_8py_source.html#l00350">350</a> of file <a class="el" href="Stirrup_8py_source.html">Stirrup.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00350"></a><span class="lineno"><a class="line" href="namespaceStirrup.html#a3863ce61c716794557101a50f41597b5">  350</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceStirrup.html#a3863ce61c716794557101a50f41597b5">CommandStirrup</a>():</div><div class="line"><a name="l00351"></a><span class="lineno">  351</span>&#160;    selected_obj = <a class="code" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">check_selected_face</a>()</div><div class="line"><a name="l00352"></a><span class="lineno">  352</span>&#160;    <span class="keywordflow">if</span> selected_obj:</div><div class="line"><a name="l00353"></a><span class="lineno">  353</span>&#160;        FreeCADGui.Control.showDialog(<a class="code" href="classStirrup_1_1__StirrupTaskPanel.html">_StirrupTaskPanel</a>())</div><div class="line"><a name="l00354"></a><span class="lineno">  354</span>&#160;<div class="ttc" id="namespaceRebarfunc_html_adae2713855a7e1b4bda04081ae671542"><div class="ttname"><a href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">Rebarfunc.check_selected_face</a></div><div class="ttdeci">def check_selected_face()</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00255">Rebarfunc.py:255</a></div></div>
<div class="ttc" id="namespaceStirrup_html_a3863ce61c716794557101a50f41597b5"><div class="ttname"><a href="namespaceStirrup.html#a3863ce61c716794557101a50f41597b5">Stirrup.CommandStirrup</a></div><div class="ttdeci">def CommandStirrup()</div><div class="ttdef"><b>Definition:</b> <a href="Stirrup_8py_source.html#l00350">Stirrup.py:350</a></div></div>
<div class="ttc" id="classStirrup_1_1__StirrupTaskPanel_html"><div class="ttname"><a href="classStirrup_1_1__StirrupTaskPanel.html">Stirrup._StirrupTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="Stirrup_8py_source.html#l00123">Stirrup.py:123</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStirrup_a3863ce61c716794557101a50f41597b5_cgraph.png" border="0" usemap="#namespaceStirrup_a3863ce61c716794557101a50f41597b5_cgraph" alt=""/></div>
<map name="namespaceStirrup_a3863ce61c716794557101a50f41597b5_cgraph" id="namespaceStirrup_a3863ce61c716794557101a50f41597b5_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542" title="Rebarfunc.check_selected_face" alt="" coords="216,5,425,32"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="473,5,639,32"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="687,5,823,32"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStirrup_a3863ce61c716794557101a50f41597b5_icgraph.png" border="0" usemap="#namespaceStirrup_a3863ce61c716794557101a50f41597b5_icgraph" alt=""/></div>
<map name="namespaceStirrup_a3863ce61c716794557101a50f41597b5_icgraph" id="namespaceStirrup_a3863ce61c716794557101a50f41597b5_icgraph">
<area shape="rect" id="node2" href="classRebarTools_1_1StirrupTool.html#a8ab82071978a99ee1f68cbf5b971ac8a" title="RebarTools.StirrupTool.Activated" alt="" coords="216,5,431,32"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a8ebd17322b7f4f5fe9e50bd578ba670d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def Stirrup.editDialog </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>vobj</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="Stirrup_8py_source.html#l00327">327</a> of file <a class="el" href="Stirrup_8py_source.html">Stirrup.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00327"></a><span class="lineno"><a class="line" href="namespaceStirrup.html#a8ebd17322b7f4f5fe9e50bd578ba670d">  327</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceStirrup.html#a8ebd17322b7f4f5fe9e50bd578ba670d">editDialog</a>(vobj):</div><div class="line"><a name="l00328"></a><span class="lineno">  328</span>&#160;    FreeCADGui.Control.closeDialog()</div><div class="line"><a name="l00329"></a><span class="lineno">  329</span>&#160;    obj = <a class="code" href="classStirrup_1_1__StirrupTaskPanel.html">_StirrupTaskPanel</a>(vobj.Object)</div><div class="line"><a name="l00330"></a><span class="lineno">  330</span>&#160;    obj.form.frontCover.setText(str(vobj.Object.FrontCover))</div><div class="line"><a name="l00331"></a><span class="lineno">  331</span>&#160;    obj.form.l_sideCover.setText(str(vobj.Object.LeftCover))</div><div class="line"><a name="l00332"></a><span class="lineno">  332</span>&#160;    obj.form.r_sideCover.setText(str(vobj.Object.RightCover))</div><div class="line"><a name="l00333"></a><span class="lineno">  333</span>&#160;    obj.form.t_sideCover.setText(str(vobj.Object.TopCover))</div><div class="line"><a name="l00334"></a><span class="lineno">  334</span>&#160;    obj.form.b_sideCover.setText(str(vobj.Object.BottomCover))</div><div class="line"><a name="l00335"></a><span class="lineno">  335</span>&#160;    obj.form.diameter.setText(str(vobj.Object.Diameter))</div><div class="line"><a name="l00336"></a><span class="lineno">  336</span>&#160;    obj.form.bentAngle.setCurrentIndex(obj.form.bentAngle.findText(str(vobj.Object.BentAngle)))</div><div class="line"><a name="l00337"></a><span class="lineno">  337</span>&#160;    obj.form.bentFactor.setValue(vobj.Object.BentFactor)</div><div class="line"><a name="l00338"></a><span class="lineno">  338</span>&#160;    obj.form.rounding.setValue(vobj.Object.Rounding)</div><div class="line"><a name="l00339"></a><span class="lineno">  339</span>&#160;    <span class="keywordflow">if</span> vobj.Object.AmountCheck:</div><div class="line"><a name="l00340"></a><span class="lineno">  340</span>&#160;        obj.form.amount.setValue(vobj.Object.Amount)</div><div class="line"><a name="l00341"></a><span class="lineno">  341</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00342"></a><span class="lineno">  342</span>&#160;        obj.form.amount_radio.setChecked(<span class="keyword">False</span>)</div><div class="line"><a name="l00343"></a><span class="lineno">  343</span>&#160;        obj.form.spacing_radio.setChecked(<span class="keyword">True</span>)</div><div class="line"><a name="l00344"></a><span class="lineno">  344</span>&#160;        obj.form.amount.setDisabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00345"></a><span class="lineno">  345</span>&#160;        obj.form.spacing.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00346"></a><span class="lineno">  346</span>&#160;        obj.form.spacing.setText(str(vobj.Object.TrueSpacing))</div><div class="line"><a name="l00347"></a><span class="lineno">  347</span>&#160;    <span class="comment">#obj.form.PickSelectedFace.setVisible(False)</span></div><div class="line"><a name="l00348"></a><span class="lineno">  348</span>&#160;    FreeCADGui.Control.showDialog(obj)</div><div class="line"><a name="l00349"></a><span class="lineno">  349</span>&#160;</div><div class="ttc" id="namespaceStirrup_html_a8ebd17322b7f4f5fe9e50bd578ba670d"><div class="ttname"><a href="namespaceStirrup.html#a8ebd17322b7f4f5fe9e50bd578ba670d">Stirrup.editDialog</a></div><div class="ttdeci">def editDialog(vobj)</div><div class="ttdef"><b>Definition:</b> <a href="Stirrup_8py_source.html#l00327">Stirrup.py:327</a></div></div>
<div class="ttc" id="classStirrup_1_1__StirrupTaskPanel_html"><div class="ttname"><a href="classStirrup_1_1__StirrupTaskPanel.html">Stirrup._StirrupTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="Stirrup_8py_source.html#l00123">Stirrup.py:123</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a1f6d278ace7fe116895dba342e2a3573"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def Stirrup.editStirrup </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>Rebar</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>f_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentAngle</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentFactor</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rounding</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_check</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_value</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="Stirrup_8py_source.html#l00281">281</a> of file <a class="el" href="Stirrup_8py_source.html">Stirrup.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00281"></a><span class="lineno"><a class="line" href="namespaceStirrup.html#a1f6d278ace7fe116895dba342e2a3573">  281</a></span>&#160;        amount_spacing_check, amount_spacing_value, structure = <span class="keywordtype">None</span>, facename = <span class="keywordtype">None</span>):</div><div class="line"><a name="l00282"></a><span class="lineno">  282</span>&#160;    sketch = Rebar.Base</div><div class="line"><a name="l00283"></a><span class="lineno">  283</span>&#160;    <span class="keywordflow">if</span> structure <span class="keywordflow">and</span> facename:</div><div class="line"><a name="l00284"></a><span class="lineno">  284</span>&#160;        sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00285"></a><span class="lineno">  285</span>&#160;    <span class="comment"># Check if sketch support is empty.</span></div><div class="line"><a name="l00286"></a><span class="lineno">  286</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> sketch.Support:</div><div class="line"><a name="l00287"></a><span class="lineno">  287</span>&#160;        <a class="code" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">showWarning</a>(<span class="stringliteral">&quot;You have checked remove external geometry of base sketchs when needed.\nTo unchecked Edit-&gt;Preferences-&gt;Arch.&quot;</span>)</div><div class="line"><a name="l00288"></a><span class="lineno">  288</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00289"></a><span class="lineno">  289</span>&#160;    <span class="comment"># Assigned values</span></div><div class="line"><a name="l00290"></a><span class="lineno">  290</span>&#160;    facename = sketch.Support[0][1][0]</div><div class="line"><a name="l00291"></a><span class="lineno">  291</span>&#160;    structure = sketch.Support[0][0]</div><div class="line"><a name="l00292"></a><span class="lineno">  292</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00293"></a><span class="lineno">  293</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00294"></a><span class="lineno">  294</span>&#160;    <span class="comment"># Get parameters of the face where sketch of rebar is drawn</span></div><div class="line"><a name="l00295"></a><span class="lineno">  295</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename, <span class="keyword">False</span>)</div><div class="line"><a name="l00296"></a><span class="lineno">  296</span>&#160;    FaceNormal = face.normalAt(0, 0)</div><div class="line"><a name="l00297"></a><span class="lineno">  297</span>&#160;    <span class="comment">#FaceNormal = face.Placement.Rotation.inverted().multVec(FaceNormal)</span></div><div class="line"><a name="l00298"></a><span class="lineno">  298</span>&#160;    <span class="comment"># Calculate the coordinates value of Stirrup rebar</span></div><div class="line"><a name="l00299"></a><span class="lineno">  299</span>&#160;    points = <a class="code" href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a">getpointsOfStirrup</a>(FacePRM, l_cover, r_cover, t_cover, b_cover, bentAngle, bentFactor, diameter, rounding, FaceNormal)</div><div class="line"><a name="l00300"></a><span class="lineno">  300</span>&#160;    Rebar.Base.Points = points</div><div class="line"><a name="l00301"></a><span class="lineno">  301</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00302"></a><span class="lineno">  302</span>&#160;    Rebar.Direction = FaceNormal.negative()</div><div class="line"><a name="l00303"></a><span class="lineno">  303</span>&#160;    Rebar.OffsetStart = f_cover</div><div class="line"><a name="l00304"></a><span class="lineno">  304</span>&#160;    Rebar.OffsetEnd = f_cover</div><div class="line"><a name="l00305"></a><span class="lineno">  305</span>&#160;    Rebar.BentAngle = bentAngle</div><div class="line"><a name="l00306"></a><span class="lineno">  306</span>&#160;    Rebar.BentFactor = bentFactor</div><div class="line"><a name="l00307"></a><span class="lineno">  307</span>&#160;    Rebar.Rounding = rounding</div><div class="line"><a name="l00308"></a><span class="lineno">  308</span>&#160;    Rebar.Diameter = diameter</div><div class="line"><a name="l00309"></a><span class="lineno">  309</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00310"></a><span class="lineno">  310</span>&#160;        Rebar.Amount = amount_spacing_value</div><div class="line"><a name="l00311"></a><span class="lineno">  311</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00312"></a><span class="lineno">  312</span>&#160;        Rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00313"></a><span class="lineno">  313</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00314"></a><span class="lineno">  314</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00315"></a><span class="lineno">  315</span>&#160;        Rebar.Amount = int((size - diameter) / amount_spacing_value)</div><div class="line"><a name="l00316"></a><span class="lineno">  316</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00317"></a><span class="lineno">  317</span>&#160;        Rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00318"></a><span class="lineno">  318</span>&#160;    Rebar.FrontCover = f_cover</div><div class="line"><a name="l00319"></a><span class="lineno">  319</span>&#160;    Rebar.LeftCover = l_cover</div><div class="line"><a name="l00320"></a><span class="lineno">  320</span>&#160;    Rebar.RightCover = r_cover</div><div class="line"><a name="l00321"></a><span class="lineno">  321</span>&#160;    Rebar.TopCover = t_cover</div><div class="line"><a name="l00322"></a><span class="lineno">  322</span>&#160;    Rebar.BottomCover = b_cover</div><div class="line"><a name="l00323"></a><span class="lineno">  323</span>&#160;    Rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00324"></a><span class="lineno">  324</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00325"></a><span class="lineno">  325</span>&#160;    <span class="keywordflow">return</span> Rebar</div><div class="line"><a name="l00326"></a><span class="lineno">  326</span>&#160;</div><div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a2278a0602d46a62953af1fcf2e574a94"><div class="ttname"><a href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">Rebarfunc.showWarning</a></div><div class="ttdeci">def showWarning(message)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00293">Rebarfunc.py:293</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
<div class="ttc" id="namespaceStirrup_html_aa6df5118806bfe9d3a799e1bf549bb0a"><div class="ttname"><a href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a">Stirrup.getpointsOfStirrup</a></div><div class="ttdeci">def getpointsOfStirrup(FacePRM, l_cover, r_cover, t_cover, b_cover, bentAngle, bentFactor, diameter, rounding, facenormal)</div><div class="ttdef"><b>Definition:</b> <a href="Stirrup_8py_source.html#l00040">Stirrup.py:40</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStirrup_a1f6d278ace7fe116895dba342e2a3573_cgraph.png" border="0" usemap="#namespaceStirrup_a1f6d278ace7fe116895dba342e2a3573_cgraph" alt=""/></div>
<map name="namespaceStirrup_a1f6d278ace7fe116895dba342e2a3573_cgraph" id="namespaceStirrup_a1f6d278ace7fe116895dba342e2a3573_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="201,5,366,32"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="443,77,621,104"/>
<area shape="rect" id="node5" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="176,107,391,133"/>
<area shape="rect" id="node6" href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a" title="Stirrup.getpointsOfStirrup" alt="" coords="199,157,368,184"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="464,5,600,32"/>
<area shape="rect" id="node7" href="namespaceRebarfunc.html#aaeecb468e0fcfc5eee69d6a24c5c5aef" title="Rebarfunc.extendedTangent\lPartLength" alt="" coords="439,139,625,181"/>
<area shape="rect" id="node8" href="namespaceRebarfunc.html#ab5637ab0a8e202409ee8657d39ca87a0" title="Rebarfunc.extendedTangent\lLength" alt="" coords="439,205,625,246"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStirrup_a1f6d278ace7fe116895dba342e2a3573_icgraph.png" border="0" usemap="#namespaceStirrup_a1f6d278ace7fe116895dba342e2a3573_icgraph" alt=""/></div>
<map name="namespaceStirrup_a1f6d278ace7fe116895dba342e2a3573_icgraph" id="namespaceStirrup_a1f6d278ace7fe116895dba342e2a3573_icgraph">
<area shape="rect" id="node2" href="classStirrup_1_1__StirrupTaskPanel.html#a49957596860a74388ec2e64535eacbc6" title="Stirrup._StirrupTaskPanel.accept" alt="" coords="361,64,576,91"/>
<area shape="rect" id="node6" href="namespaceStirrup.html#a705fc121e2af9c8ac05eb299f4fb9f2f" title="Stirrup.makeStirrup" alt="" coords="176,115,311,141"/>
<area shape="rect" id="node3" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="627,5,843,32"/>
<area shape="rect" id="node4" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="638,57,831,98"/>
<area shape="rect" id="node5" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="636,122,833,163"/>
<area shape="rect" id="node7" href="classStirrup_1_1__StirrupTaskPanel.html#ac091360b77eb8b65a0f520af0d2c4584" title="Stirrup._StirrupTaskPanel.spacing\l_radio_clicked" alt="" coords="359,115,579,157"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="aa6df5118806bfe9d3a799e1bf549bb0a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def Stirrup.getpointsOfStirrup </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>FacePRM</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentAngle</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentFactor</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rounding</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facenormal</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">getpointsOfStirrup(FacePRM, LeftCover, RightCover, TopCover, BottomCover, BentAngle, BentFactor, Diameter, Rounding, FaceNormal):
Return the coordinates points of the Stirrup in the form of array.</pre> 
<p>Definition at line <a class="el" href="Stirrup_8py_source.html#l00040">40</a> of file <a class="el" href="Stirrup_8py_source.html">Stirrup.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a">   40</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a">getpointsOfStirrup</a>(FacePRM, l_cover, r_cover, t_cover, b_cover, bentAngle, bentFactor, diameter, rounding, facenormal):</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; getpointsOfStirrup(FacePRM, LeftCover, RightCover, TopCover, BottomCover, BentAngle, BentFactor, Diameter, Rounding, FaceNormal):</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="stringliteral">    Return the coordinates points of the Stirrup in the form of array.&quot;&quot;&quot;</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;    angle = 180 - bentAngle</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;    tangent_part_length = <a class="code" href="namespaceRebarfunc.html#aaeecb468e0fcfc5eee69d6a24c5c5aef">extendedTangentPartLength</a>(rounding, diameter, angle)</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    tangent_length = <a class="code" href="namespaceRebarfunc.html#ab5637ab0a8e202409ee8657d39ca87a0">extendedTangentLength</a>(rounding, diameter, angle)</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;    <span class="keywordflow">if</span> round(facenormal[0]) <span class="keywordflow">in</span> {1,-1}:</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;        x1 = FacePRM[1][0]</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        y1 = FacePRM[1][1] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        z1 = FacePRM[1][2] + FacePRM[0][1] / 2 - t_cover + tangent_part_length</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        y2 = FacePRM[1][1] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;        z2 = FacePRM[1][2] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;        y3 = FacePRM[1][1] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;        z3 = FacePRM[1][2] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;        y4 = FacePRM[1][1] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;        z4 = FacePRM[1][2] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        y5 = FacePRM[1][1] - FacePRM[0][0] / 2 + l_cover - tangent_part_length</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;        z5 = FacePRM[1][2] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;        side_length = abs(y5 - y4) - tangent_part_length</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;        normal_dis = (diameter * (side_length + tangent_part_length)) / side_length</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;        x2 = x1 - normal_dis / 4</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;        x3 = x2 - normal_dis / 4</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;        x4 = x3 - normal_dis / 4</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;        x5 = x4 - normal_dis / 4</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;        x0 = x1 + normal_dis / 4</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;        y0 = y1 + (tangent_length + bentFactor * diameter) * math.sin(math.radians(angle))</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;        z0 = z1 - (tangent_length + bentFactor * diameter) * math.cos(math.radians(angle))</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        x6 = x5 - normal_dis / 4</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;        y6 = y5 + (tangent_length + bentFactor * diameter) * math.sin(math.radians(90 - angle))</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;        z6 = z5 - (tangent_length + bentFactor * diameter) * math.cos(math.radians(90 - angle))</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;    <span class="keywordflow">elif</span> round(facenormal[1]) <span class="keywordflow">in</span> {1,-1}:</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;        y1 = FacePRM[1][1]</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;        z1 = FacePRM[1][2] + FacePRM[0][1] / 2 - t_cover + tangent_part_length</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;        x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;        z2 = FacePRM[1][2] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;        x3 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;        z3 = FacePRM[1][2] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;        x4 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;        z4 = FacePRM[1][2] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;        x5 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover - tangent_part_length</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;        z5 = FacePRM[1][2] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;        side_length = abs(x5 - x4) - tangent_part_length</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;        normal_dis = (diameter * (side_length + tangent_part_length)) / side_length</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        y2 = y1 - normal_dis / 4</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;        y3 = y2 - normal_dis / 4</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;        y4 = y3 - normal_dis / 4</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;        y5 = y4 - normal_dis / 4</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;        y0 = y1 + normal_dis / 4</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;        x0 = x1 + (tangent_length + bentFactor * diameter) * math.sin(math.radians(angle))</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;        z0 = z1 - (tangent_length + bentFactor * diameter) * math.cos(math.radians(angle))</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;        x6 = x5 + (tangent_length + bentFactor * diameter) * math.sin(math.radians(90 - angle))</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;        y6 = y5 - normal_dis / 4</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;        z6 = z5 - (tangent_length + bentFactor * diameter) * math.cos(math.radians(90 - angle))</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;    <span class="keywordflow">elif</span> round(facenormal[2]) <span class="keywordflow">in</span> {1,-1}:</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover + tangent_part_length</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;        z1 = FacePRM[1][2]</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;        x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;        y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;        x3 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;        y3 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;        x4 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;        y4 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;        x5 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover - tangent_part_length</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;        y5 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;        side_length = abs(x5 - x4) - tangent_part_length</div><div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;        normal_dis = (diameter * (side_length + tangent_part_length)) / side_length</div><div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;        z2 = z1 - normal_dis / 4</div><div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;        z3 = z2 - normal_dis / 4</div><div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;        z4 = z3 - normal_dis / 4</div><div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;        z5 = z4 - normal_dis / 4</div><div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;        z0 = z1 + normal_dis / 4</div><div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;        x0 = x1 + (tangent_length + bentFactor * diameter) * math.sin(math.radians(angle))</div><div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;        y0 = y1 - (tangent_length + bentFactor * diameter) * math.cos(math.radians(angle))</div><div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;        x6 = x5 + (tangent_length + bentFactor * diameter) * math.sin(math.radians(90 - angle))</div><div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;        y6 = y5 - (tangent_length + bentFactor * diameter) * math.cos(math.radians(90 - angle))</div><div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;        z6 = z5 - normal_dis / 4</div><div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;    <span class="keywordflow">return</span> [FreeCAD.Vector(x0, y0, z0), FreeCAD.Vector(x1, y1, z1),\</div><div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;            FreeCAD.Vector(x2, y2, z2), FreeCAD.Vector(x3, y3, z3),\</div><div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;            FreeCAD.Vector(x4, y4, z4), FreeCAD.Vector(x5, y5, z5),\</div><div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;            FreeCAD.Vector(x6, y6, z6)]</div><div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;</div><div class="ttc" id="namespaceRebarfunc_html_ab5637ab0a8e202409ee8657d39ca87a0"><div class="ttname"><a href="namespaceRebarfunc.html#ab5637ab0a8e202409ee8657d39ca87a0">Rebarfunc.extendedTangentLength</a></div><div class="ttdeci">def extendedTangentLength(rounding, diameter, angle)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00243">Rebarfunc.py:243</a></div></div>
<div class="ttc" id="namespaceStirrup_html_aa6df5118806bfe9d3a799e1bf549bb0a"><div class="ttname"><a href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a">Stirrup.getpointsOfStirrup</a></div><div class="ttdeci">def getpointsOfStirrup(FacePRM, l_cover, r_cover, t_cover, b_cover, bentAngle, bentFactor, diameter, rounding, facenormal)</div><div class="ttdef"><b>Definition:</b> <a href="Stirrup_8py_source.html#l00040">Stirrup.py:40</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_aaeecb468e0fcfc5eee69d6a24c5c5aef"><div class="ttname"><a href="namespaceRebarfunc.html#aaeecb468e0fcfc5eee69d6a24c5c5aef">Rebarfunc.extendedTangentPartLength</a></div><div class="ttdeci">def extendedTangentPartLength(rounding, diameter, angle)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00235">Rebarfunc.py:235</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStirrup_aa6df5118806bfe9d3a799e1bf549bb0a_cgraph.png" border="0" usemap="#namespaceStirrup_aa6df5118806bfe9d3a799e1bf549bb0a_cgraph" alt=""/></div>
<map name="namespaceStirrup_aa6df5118806bfe9d3a799e1bf549bb0a_cgraph" id="namespaceStirrup_aa6df5118806bfe9d3a799e1bf549bb0a_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#aaeecb468e0fcfc5eee69d6a24c5c5aef" title="Rebarfunc.extendedTangent\lPartLength" alt="" coords="223,5,409,47"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#ab5637ab0a8e202409ee8657d39ca87a0" title="Rebarfunc.extendedTangent\lLength" alt="" coords="223,71,409,112"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStirrup_aa6df5118806bfe9d3a799e1bf549bb0a_icgraph.png" border="0" usemap="#namespaceStirrup_aa6df5118806bfe9d3a799e1bf549bb0a_icgraph" alt=""/></div>
<map name="namespaceStirrup_aa6df5118806bfe9d3a799e1bf549bb0a_icgraph" id="namespaceStirrup_aa6df5118806bfe9d3a799e1bf549bb0a_icgraph">
<area shape="rect" id="node2" href="namespaceStirrup.html#a705fc121e2af9c8ac05eb299f4fb9f2f" title="Stirrup.makeStirrup" alt="" coords="393,21,528,47"/>
<area shape="rect" id="node8" href="namespaceStirrup.html#a1f6d278ace7fe116895dba342e2a3573" title="Stirrup.editStirrup" alt="" coords="223,71,345,98"/>
<area shape="rect" id="node3" href="classStirrup_1_1__StirrupTaskPanel.html#a49957596860a74388ec2e64535eacbc6" title="Stirrup._StirrupTaskPanel.accept" alt="" coords="579,71,793,98"/>
<area shape="rect" id="node7" href="classStirrup_1_1__StirrupTaskPanel.html#ac091360b77eb8b65a0f520af0d2c4584" title="Stirrup._StirrupTaskPanel.spacing\l_radio_clicked" alt="" coords="576,5,796,47"/>
<area shape="rect" id="node4" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="844,13,1060,39"/>
<area shape="rect" id="node5" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="855,64,1049,105"/>
<area shape="rect" id="node6" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="853,129,1051,171"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a705fc121e2af9c8ac05eb299f4fb9f2f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def Stirrup.makeStirrup </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>f_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentAngle</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentFactor</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rounding</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_check</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_value</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">makeStirrup(LeftCover, RightCover, TopCover, BottomCover, FrontCover, BentAngle,
BentFactor, Diameter, Rounding, AmountSpacingCheck, AmountSpacingValue, Structure, Facename):
Adds the Stirrup reinforcement bar to the selected structural object.</pre> 
<p>Definition at line <a class="el" href="Stirrup_8py_source.html#l00210">210</a> of file <a class="el" href="Stirrup_8py_source.html">Stirrup.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00210"></a><span class="lineno"><a class="line" href="namespaceStirrup.html#a705fc121e2af9c8ac05eb299f4fb9f2f">  210</a></span>&#160;        amount_spacing_check, amount_spacing_value, structure = <span class="keywordtype">None</span>, facename = <span class="keywordtype">None</span>):</div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; makeStirrup(LeftCover, RightCover, TopCover, BottomCover, FrontCover, BentAngle,</span></div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;<span class="stringliteral">    BentFactor, Diameter, Rounding, AmountSpacingCheck, AmountSpacingValue, Structure, Facename):</span></div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;<span class="stringliteral">    Adds the Stirrup reinforcement bar to the selected structural object.&quot;&quot;&quot;</span></div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> structure <span class="keywordflow">and</span> <span class="keywordflow">not</span> facename:</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;        selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;        structure = selected_obj.Object</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;        facename = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename, <span class="keyword">False</span>)</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    FaceNormal = face.normalAt(0,0)</div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    <span class="comment">#FaceNormal = face.Placement.Rotation.inverted().multVec(FaceNormal)</span></div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> FacePRM:</div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;        FreeCAD.Console.PrintError(<span class="stringliteral">&quot;Cannot identified shape or from which base object sturctural element is derived\n&quot;</span>)</div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;    <span class="comment"># Calculate the coordinate values of Stirrup</span></div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;    points = <a class="code" href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a">getpointsOfStirrup</a>(FacePRM, l_cover, r_cover, t_cover, b_cover, bentAngle, bentFactor, diameter, rounding, FaceNormal)</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;    <span class="keyword">import</span> Draft</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;    line = Draft.makeWire(points, closed = <span class="keyword">False</span>, face = <span class="keyword">True</span>, support = <span class="keywordtype">None</span>)</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;    <span class="keyword">import</span> Arch</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;    line.Support = [(structure, facename)]</div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;        rebar = Arch.makeRebar(structure, line, diameter, amount_spacing_value, f_cover)</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;        rebar = Arch.makeRebar(structure, line, diameter,\</div><div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;            int((size - diameter) / amount_spacing_value), f_cover)</div><div class="line"><a name="l00238"></a><span class="lineno">  238</span>&#160;    rebar.Direction = FaceNormal.negative()</div><div class="line"><a name="l00239"></a><span class="lineno">  239</span>&#160;    rebar.Rounding = rounding</div><div class="line"><a name="l00240"></a><span class="lineno">  240</span>&#160;    <span class="comment"># Adds properties to the rebar object</span></div><div class="line"><a name="l00241"></a><span class="lineno">  241</span>&#160;    rebar.ViewObject.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;RebarShape&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00242"></a><span class="lineno">  242</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>,<span class="stringliteral">&quot;Shape of rebar&quot;</span>)).RebarShape = <span class="stringliteral">&quot;Stirrup&quot;</span></div><div class="line"><a name="l00243"></a><span class="lineno">  243</span>&#160;    rebar.ViewObject.setEditorMode(<span class="stringliteral">&quot;RebarShape&quot;</span>, 2)</div><div class="line"><a name="l00244"></a><span class="lineno">  244</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;LeftCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00245"></a><span class="lineno">  245</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Left Side cover of rebar&quot;</span>)).LeftCover = l_cover</div><div class="line"><a name="l00246"></a><span class="lineno">  246</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;LeftCover&quot;</span>, 2)</div><div class="line"><a name="l00247"></a><span class="lineno">  247</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;RightCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00248"></a><span class="lineno">  248</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Right Side cover of rebar&quot;</span>)).RightCover = r_cover</div><div class="line"><a name="l00249"></a><span class="lineno">  249</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;RightCover&quot;</span>, 2)</div><div class="line"><a name="l00250"></a><span class="lineno">  250</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TopCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00251"></a><span class="lineno">  251</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Top Side cover of rebar&quot;</span>)).TopCover = t_cover</div><div class="line"><a name="l00252"></a><span class="lineno">  252</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TopCover&quot;</span>, 2)</div><div class="line"><a name="l00253"></a><span class="lineno">  253</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BottomCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00254"></a><span class="lineno">  254</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bottom Side cover of rebar&quot;</span>)).BottomCover = b_cover</div><div class="line"><a name="l00255"></a><span class="lineno">  255</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BottomCover&quot;</span>, 2)</div><div class="line"><a name="l00256"></a><span class="lineno">  256</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;FrontCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00257"></a><span class="lineno">  257</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Top cover of rebar&quot;</span>)).FrontCover = f_cover</div><div class="line"><a name="l00258"></a><span class="lineno">  258</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;FrontCover&quot;</span>, 2)</div><div class="line"><a name="l00259"></a><span class="lineno">  259</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyInteger&quot;</span>, <span class="stringliteral">&quot;BentAngle&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00260"></a><span class="lineno">  260</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bent angle between at the end of rebar&quot;</span>)).BentAngle = bentAngle</div><div class="line"><a name="l00261"></a><span class="lineno">  261</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BentAngle&quot;</span>, 2)</div><div class="line"><a name="l00262"></a><span class="lineno">  262</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyInteger&quot;</span>, <span class="stringliteral">&quot;BentFactor&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00263"></a><span class="lineno">  263</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bent Length is the equal to BentFactor * Diameter&quot;</span>)).BentFactor = bentFactor</div><div class="line"><a name="l00264"></a><span class="lineno">  264</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BentFactor&quot;</span>, 2)</div><div class="line"><a name="l00265"></a><span class="lineno">  265</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyBool&quot;</span>, <span class="stringliteral">&quot;AmountCheck&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00266"></a><span class="lineno">  266</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Amount radio button is checked&quot;</span>)).AmountCheck</div><div class="line"><a name="l00267"></a><span class="lineno">  267</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;AmountCheck&quot;</span>, 2)</div><div class="line"><a name="l00268"></a><span class="lineno">  268</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TrueSpacing&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>,\</div><div class="line"><a name="l00269"></a><span class="lineno">  269</span>&#160;        QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Spacing between of rebars&quot;</span>)).TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00270"></a><span class="lineno">  270</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TrueSpacing&quot;</span>, 2)</div><div class="line"><a name="l00271"></a><span class="lineno">  271</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00272"></a><span class="lineno">  272</span>&#160;        rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00273"></a><span class="lineno">  273</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00274"></a><span class="lineno">  274</span>&#160;        rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00275"></a><span class="lineno">  275</span>&#160;        rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00276"></a><span class="lineno">  276</span>&#160;    rebar.Label = <span class="stringliteral">&quot;Stirrup&quot;</span></div><div class="line"><a name="l00277"></a><span class="lineno">  277</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00278"></a><span class="lineno">  278</span>&#160;    <span class="keywordflow">return</span> rebar</div><div class="line"><a name="l00279"></a><span class="lineno">  279</span>&#160;</div><div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
<div class="ttc" id="namespaceStirrup_html_aa6df5118806bfe9d3a799e1bf549bb0a"><div class="ttname"><a href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a">Stirrup.getpointsOfStirrup</a></div><div class="ttdeci">def getpointsOfStirrup(FacePRM, l_cover, r_cover, t_cover, b_cover, bentAngle, bentFactor, diameter, rounding, facenormal)</div><div class="ttdef"><b>Definition:</b> <a href="Stirrup_8py_source.html#l00040">Stirrup.py:40</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStirrup_a705fc121e2af9c8ac05eb299f4fb9f2f_cgraph.png" border="0" usemap="#namespaceStirrup_a705fc121e2af9c8ac05eb299f4fb9f2f_cgraph" alt=""/></div>
<map name="namespaceStirrup_a705fc121e2af9c8ac05eb299f4fb9f2f_cgraph" id="namespaceStirrup_a705fc121e2af9c8ac05eb299f4fb9f2f_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="625,27,804,53"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="359,27,573,53"/>
<area shape="rect" id="node4" href="namespaceStirrup.html#aa6df5118806bfe9d3a799e1bf549bb0a" title="Stirrup.getpointsOfStirrup" alt="" coords="381,179,551,205"/>
<area shape="rect" id="node7" href="namespaceStirrup.html#a1f6d278ace7fe116895dba342e2a3573" title="Stirrup.editStirrup" alt="" coords="188,77,311,104"/>
<area shape="rect" id="node5" href="namespaceRebarfunc.html#aaeecb468e0fcfc5eee69d6a24c5c5aef" title="Rebarfunc.extendedTangent\lPartLength" alt="" coords="621,237,808,278"/>
<area shape="rect" id="node6" href="namespaceRebarfunc.html#ab5637ab0a8e202409ee8657d39ca87a0" title="Rebarfunc.extendedTangent\lLength" alt="" coords="621,171,808,213"/>
<area shape="rect" id="node8" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="383,128,549,155"/>
<area shape="rect" id="node9" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="647,120,783,147"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStirrup_a705fc121e2af9c8ac05eb299f4fb9f2f_icgraph.png" border="0" usemap="#namespaceStirrup_a705fc121e2af9c8ac05eb299f4fb9f2f_icgraph" alt=""/></div>
<map name="namespaceStirrup_a705fc121e2af9c8ac05eb299f4fb9f2f_icgraph" id="namespaceStirrup_a705fc121e2af9c8ac05eb299f4fb9f2f_icgraph">
<area shape="rect" id="node2" href="classStirrup_1_1__StirrupTaskPanel.html#a49957596860a74388ec2e64535eacbc6" title="Stirrup._StirrupTaskPanel.accept" alt="" coords="191,64,405,91"/>
<area shape="rect" id="node6" href="classStirrup_1_1__StirrupTaskPanel.html#ac091360b77eb8b65a0f520af0d2c4584" title="Stirrup._StirrupTaskPanel.spacing\l_radio_clicked" alt="" coords="188,115,408,157"/>
<area shape="rect" id="node3" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="456,5,672,32"/>
<area shape="rect" id="node4" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="467,57,661,98"/>
<area shape="rect" id="node5" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="465,122,663,163"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="ad470a52dca49f918ddfef810e749291c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string Stirrup.__author__ = &quot;Amritpal Singh&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="Stirrup_8py_source.html#l00025">25</a> of file <a class="el" href="Stirrup_8py_source.html">Stirrup.py</a>.</p>

</div>
</div>
<a class="anchor" id="aac4f16b6285f67fb07673ac264bac3dc"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string Stirrup.__title__ = &quot;StirrupRebar&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="Stirrup_8py_source.html#l00024">24</a> of file <a class="el" href="Stirrup_8py_source.html">Stirrup.py</a>.</p>

</div>
</div>
<a class="anchor" id="a3b5b07aa3d0183155a2be24e2d0d4a82"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string Stirrup.__url__ = &quot;https://www.freecadweb.org&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="Stirrup_8py_source.html#l00026">26</a> of file <a class="el" href="Stirrup_8py_source.html">Stirrup.py</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Wed Dec 13 2017 22:36:42 for Rebar Addon for FreeCAD by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.11
</small></address>
</body>
</html>
