<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Rebar Addon for FreeCAD: HelicalRebar Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Rebar Addon for FreeCAD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="namespaces.html"><span>Namespace&#160;List</span></a></li>
      <li><a href="namespacemembers.html"><span>Namespace&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">HelicalRebar Namespace Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">_HelicalRebarTaskPanel</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a4fcf2dabc065c39ce5c8cf6995051352"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#a4fcf2dabc065c39ce5c8cf6995051352">getpointsOfHelicalRebar</a> (FacePRM, s_cover, b_cover, t_cover, pitch, edges, diameter, size, direction)</td></tr>
<tr class="separator:a4fcf2dabc065c39ce5c8cf6995051352"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1a2b3ce39b904ab0c3892ed0965d2844"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">createHelicalWire</a> (FacePRM, s_cover, b_cover, t_cover, pitch, size, direction, helix=None)</td></tr>
<tr class="separator:a1a2b3ce39b904ab0c3892ed0965d2844"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8a4f12ed70819996ac31877957dfab08"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08">makeHelicalRebar</a> (s_cover, b_cover, diameter, t_cover, pitch, structure=None, facename=None)</td></tr>
<tr class="separator:a8a4f12ed70819996ac31877957dfab08"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aea0d3838b1b171f801acf1046d111c8b"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b">editHelicalRebar</a> (Rebar, s_cover, b_cover, diameter, t_cover, pitch, structure=None, facename=None)</td></tr>
<tr class="separator:aea0d3838b1b171f801acf1046d111c8b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab9725ab4f1e5650133dba94c24907331"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#ab9725ab4f1e5650133dba94c24907331">editDialog</a> (vobj)</td></tr>
<tr class="separator:ab9725ab4f1e5650133dba94c24907331"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad8ff0caf1e8a56ac47ce25062db8bc46"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#ad8ff0caf1e8a56ac47ce25062db8bc46">CommandHelicalRebar</a> ()</td></tr>
<tr class="separator:ad8ff0caf1e8a56ac47ce25062db8bc46"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a28c95505364eadd0c2d4abbd80091bef"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#a28c95505364eadd0c2d4abbd80091bef">__title__</a> = &quot;HelicalRebar&quot;</td></tr>
<tr class="separator:a28c95505364eadd0c2d4abbd80091bef"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a925dcfed2ffef215413157f48d7b6e57"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#a925dcfed2ffef215413157f48d7b6e57">__author__</a> = &quot;Amritpal Singh&quot;</td></tr>
<tr class="separator:a925dcfed2ffef215413157f48d7b6e57"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9c74e4634d00eef07ed630054e69fbff"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceHelicalRebar.html#a9c74e4634d00eef07ed630054e69fbff">__url__</a> = &quot;https://www.freecadweb.org&quot;</td></tr>
<tr class="separator:a9c74e4634d00eef07ed630054e69fbff"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="ad8ff0caf1e8a56ac47ce25062db8bc46"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def HelicalRebar.CommandHelicalRebar </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00241">241</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00241"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#ad8ff0caf1e8a56ac47ce25062db8bc46">  241</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#ad8ff0caf1e8a56ac47ce25062db8bc46">CommandHelicalRebar</a>():</div><div class="line"><a name="l00242"></a><span class="lineno">  242</span>&#160;    selected_obj = <a class="code" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">check_selected_face</a>()</div><div class="line"><a name="l00243"></a><span class="lineno">  243</span>&#160;    <span class="keywordflow">if</span> selected_obj:</div><div class="line"><a name="l00244"></a><span class="lineno">  244</span>&#160;        FreeCADGui.Control.showDialog(<a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">_HelicalRebarTaskPanel</a>())</div><div class="line"><a name="l00245"></a><span class="lineno">  245</span>&#160;<div class="ttc" id="namespaceRebarfunc_html_adae2713855a7e1b4bda04081ae671542"><div class="ttname"><a href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">Rebarfunc.check_selected_face</a></div><div class="ttdeci">def check_selected_face()</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00255">Rebarfunc.py:255</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_ad8ff0caf1e8a56ac47ce25062db8bc46"><div class="ttname"><a href="namespaceHelicalRebar.html#ad8ff0caf1e8a56ac47ce25062db8bc46">HelicalRebar.CommandHelicalRebar</a></div><div class="ttdeci">def CommandHelicalRebar()</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00241">HelicalRebar.py:241</a></div></div>
<div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">HelicalRebar._HelicalRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00107">HelicalRebar.py:107</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceHelicalRebar_ad8ff0caf1e8a56ac47ce25062db8bc46_cgraph.png" border="0" usemap="#namespaceHelicalRebar_ad8ff0caf1e8a56ac47ce25062db8bc46_cgraph" alt=""/></div>
<map name="namespaceHelicalRebar_ad8ff0caf1e8a56ac47ce25062db8bc46_cgraph" id="namespaceHelicalRebar_ad8ff0caf1e8a56ac47ce25062db8bc46_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542" title="Rebarfunc.check_selected_face" alt="" coords="255,13,464,39"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="512,13,677,39"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="725,13,861,39"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceHelicalRebar_ad8ff0caf1e8a56ac47ce25062db8bc46_icgraph.png" border="0" usemap="#namespaceHelicalRebar_ad8ff0caf1e8a56ac47ce25062db8bc46_icgraph" alt=""/></div>
<map name="namespaceHelicalRebar_ad8ff0caf1e8a56ac47ce25062db8bc46_icgraph" id="namespaceHelicalRebar_ad8ff0caf1e8a56ac47ce25062db8bc46_icgraph">
<area shape="rect" id="node2" href="classRebarTools_1_1HelicalRebarTool.html#a07cfe1e1107dbdea6f0370d049a9c0f7" title="RebarTools.HelicalRebarTool.\lActivated" alt="" coords="255,5,452,47"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a1a2b3ce39b904ab0c3892ed0965d2844"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def HelicalRebar.createHelicalWire </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>FacePRM</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>s_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>pitch</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>direction</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>helix</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">createHelicalWire(FacePRM, SideCover, BottomCover, TopCover, Pitch, Size, Direction, Helix = None):
It creates a helical wire.</pre> 
<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00075">75</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00075"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">   75</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">createHelicalWire</a>(FacePRM, s_cover, b_cover, t_cover, pitch, size, direction, helix = None):</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; createHelicalWire(FacePRM, SideCover, BottomCover, TopCover, Pitch, Size, Direction, Helix = None):</span></div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;<span class="stringliteral">    It creates a helical wire.&quot;&quot;&quot;</span></div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;    <span class="keyword">import</span> Part</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> helix:</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;        helix = FreeCAD.ActiveDocument.addObject(<span class="stringliteral">&quot;Part::Helix&quot;</span>,<span class="stringliteral">&quot;Helix&quot;</span>)</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;    helix.Pitch = pitch</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;    helix.Radius = FacePRM[0][0] / 2 - s_cover</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;    helix.Angle = 0</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;    helix.LocalCoord = 0</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;    helix.Height = size - b_cover - t_cover</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;    <span class="keywordflow">if</span> round(direction.x) == 1:</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0] - b_cover, FacePRM[1][1], FacePRM[1][2])</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(0, -1, 0), 90)</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;    <span class="keywordflow">elif</span> round(direction.x) == -1:</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0] + t_cover, FacePRM[1][1], FacePRM[1][2])</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(0, -1, 0), -90)</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;    <span class="keywordflow">elif</span> round(direction.y) == 1:</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0], FacePRM[1][1] - b_cover, FacePRM[1][2])</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(1, 0, 0), 90)</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;    <span class="keywordflow">elif</span> round(direction.y) == -1:</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0], FacePRM[1][1] + t_cover, FacePRM[1][2])</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(-1, 0, 0), 90)</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;    <span class="keywordflow">elif</span> round(direction.z) == 1:</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0], FacePRM[1][1], FacePRM[1][2] - size + b_cover)</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(0, 0, 1), 0)</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;    <span class="keywordflow">elif</span> round(direction.z) == -1:</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;        helix.Placement.Base = FreeCAD.Vector(FacePRM[1][0], FacePRM[1][1], FacePRM[1][2] + b_cover)</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;        helix.Placement.Rotation = FreeCAD.Rotation(FreeCAD.Vector(0, 0, -1), 0)</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;    <span class="keywordflow">return</span> helix</div><div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;</div><div class="ttc" id="namespaceHelicalRebar_html_a1a2b3ce39b904ab0c3892ed0965d2844"><div class="ttname"><a href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">HelicalRebar.createHelicalWire</a></div><div class="ttdeci">def createHelicalWire(FacePRM, s_cover, b_cover, t_cover, pitch, size, direction, helix=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00075">HelicalRebar.py:75</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceHelicalRebar_a1a2b3ce39b904ab0c3892ed0965d2844_icgraph.png" border="0" usemap="#namespaceHelicalRebar_a1a2b3ce39b904ab0c3892ed0965d2844_icgraph" alt=""/></div>
<map name="namespaceHelicalRebar_a1a2b3ce39b904ab0c3892ed0965d2844_icgraph" id="namespaceHelicalRebar_a1a2b3ce39b904ab0c3892ed0965d2844_icgraph">
<area shape="rect" id="node2" href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08" title="HelicalRebar.makeHelical\lRebar" alt="" coords="257,132,431,173"/>
<area shape="rect" id="node10" href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b" title="HelicalRebar.editHelical\lRebar" alt="" coords="263,197,425,239"/>
<area shape="rect" id="node3" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#acdfb101876d4841ba277e2e884ebaf9d" title="HelicalRebar._HelicalRebar\lTaskPanel.accept" alt="" coords="479,165,661,207"/>
<area shape="rect" id="node4" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce" title="HelicalRebar._HelicalRebar\lTaskPanel.clicked" alt="" coords="726,5,909,47"/>
<area shape="rect" id="node5" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="722,71,913,112"/>
<area shape="rect" id="node6" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="709,136,925,177"/>
<area shape="rect" id="node7" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="709,202,925,229"/>
<area shape="rect" id="node8" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="721,253,914,295"/>
<area shape="rect" id="node9" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="719,319,916,360"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ab9725ab4f1e5650133dba94c24907331"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def HelicalRebar.editDialog </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>vobj</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00231">231</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00231"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#ab9725ab4f1e5650133dba94c24907331">  231</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#ab9725ab4f1e5650133dba94c24907331">editDialog</a>(vobj):</div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;    FreeCADGui.Control.closeDialog()</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    obj = <a class="code" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">_HelicalRebarTaskPanel</a>(vobj.Object)</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;    obj.form.sideCover.setText(str(vobj.Object.SideCover))</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;    obj.form.bottomCover.setText(str(vobj.Object.BottomCover))</div><div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;    obj.form.diameter.setText(str(vobj.Object.Diameter))</div><div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;    obj.form.topCover.setText(str(vobj.Object.TopCover))</div><div class="line"><a name="l00238"></a><span class="lineno">  238</span>&#160;    obj.form.pitch.setText(str(vobj.Object.Pitch))</div><div class="line"><a name="l00239"></a><span class="lineno">  239</span>&#160;    FreeCADGui.Control.showDialog(obj)</div><div class="line"><a name="l00240"></a><span class="lineno">  240</span>&#160;</div><div class="ttc" id="classHelicalRebar_1_1__HelicalRebarTaskPanel_html"><div class="ttname"><a href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html">HelicalRebar._HelicalRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00107">HelicalRebar.py:107</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_ab9725ab4f1e5650133dba94c24907331"><div class="ttname"><a href="namespaceHelicalRebar.html#ab9725ab4f1e5650133dba94c24907331">HelicalRebar.editDialog</a></div><div class="ttdeci">def editDialog(vobj)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00231">HelicalRebar.py:231</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="aea0d3838b1b171f801acf1046d111c8b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def HelicalRebar.editHelicalRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>Rebar</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>s_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>pitch</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00203">203</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00203"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b">  203</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b">editHelicalRebar</a>(Rebar, s_cover, b_cover, diameter, t_cover, pitch, structure = None, facename = None):</div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;    sketch = Rebar.Base</div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;    <span class="keywordflow">if</span> structure <span class="keywordflow">and</span> facename:</div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;        sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;    <span class="comment"># Check if sketch support is empty.</span></div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> sketch.Support:</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;        <a class="code" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">showWarning</a>(<span class="stringliteral">&quot;You have checked remove external geometry of base sketchs when needed.\nTo unchecked Edit-&gt;Preferences-&gt;Arch.&quot;</span>)</div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;    <span class="comment"># Assigned values</span></div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    facename = sketch.Support[0][1][0]</div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;    structure = sketch.Support[0][0]</div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;    <span class="comment"># Get parameters of the face where sketch of rebar is drawn</span></div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename, <span class="keyword">False</span>)</div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    normal = face.normalAt(0,0)</div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    <span class="comment">#normal = face.Placement.Rotation.inverted().multVec(normal)</span></div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    helix = <a class="code" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">createHelicalWire</a>(FacePRM, s_cover, b_cover, t_cover, pitch, size, normal, Rebar.Base)</div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    Rebar.Diameter = diameter</div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    Rebar.SideCover = s_cover</div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;    Rebar.BottomCover = b_cover</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;    Rebar.TopCover = t_cover</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;    Rebar.Pitch = pitch</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;    <span class="keywordflow">return</span> Rebar</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;</div><div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_aea0d3838b1b171f801acf1046d111c8b"><div class="ttname"><a href="namespaceHelicalRebar.html#aea0d3838b1b171f801acf1046d111c8b">HelicalRebar.editHelicalRebar</a></div><div class="ttdeci">def editHelicalRebar(Rebar, s_cover, b_cover, diameter, t_cover, pitch, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00203">HelicalRebar.py:203</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a2278a0602d46a62953af1fcf2e574a94"><div class="ttname"><a href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">Rebarfunc.showWarning</a></div><div class="ttdeci">def showWarning(message)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00293">Rebarfunc.py:293</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_a1a2b3ce39b904ab0c3892ed0965d2844"><div class="ttname"><a href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">HelicalRebar.createHelicalWire</a></div><div class="ttdeci">def createHelicalWire(FacePRM, s_cover, b_cover, t_cover, pitch, size, direction, helix=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00075">HelicalRebar.py:75</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceHelicalRebar_aea0d3838b1b171f801acf1046d111c8b_cgraph.png" border="0" usemap="#namespaceHelicalRebar_aea0d3838b1b171f801acf1046d111c8b_cgraph" alt=""/></div>
<map name="namespaceHelicalRebar_aea0d3838b1b171f801acf1046d111c8b_cgraph" id="namespaceHelicalRebar_aea0d3838b1b171f801acf1046d111c8b_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="241,5,406,32"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="479,81,657,108"/>
<area shape="rect" id="node5" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="216,107,431,133"/>
<area shape="rect" id="node6" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844" title="HelicalRebar.createHelicalWire" alt="" coords="221,157,425,184"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="500,5,636,32"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceHelicalRebar_aea0d3838b1b171f801acf1046d111c8b_icgraph.png" border="0" usemap="#namespaceHelicalRebar_aea0d3838b1b171f801acf1046d111c8b_icgraph" alt=""/></div>
<map name="namespaceHelicalRebar_aea0d3838b1b171f801acf1046d111c8b_icgraph" id="namespaceHelicalRebar_aea0d3838b1b171f801acf1046d111c8b_icgraph">
<area shape="rect" id="node2" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#acdfb101876d4841ba277e2e884ebaf9d" title="HelicalRebar._HelicalRebar\lTaskPanel.accept" alt="" coords="216,165,399,207"/>
<area shape="rect" id="node3" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce" title="HelicalRebar._HelicalRebar\lTaskPanel.clicked" alt="" coords="463,5,646,47"/>
<area shape="rect" id="node4" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="459,71,650,112"/>
<area shape="rect" id="node5" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="447,136,663,177"/>
<area shape="rect" id="node6" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="447,202,663,229"/>
<area shape="rect" id="node7" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="458,253,651,295"/>
<area shape="rect" id="node8" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="456,319,653,360"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a4fcf2dabc065c39ce5c8cf6995051352"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def HelicalRebar.getpointsOfHelicalRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>FacePRM</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>s_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>pitch</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>edges</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>direction</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">getpointsOfHelicalRebar(FacePRM, s_cover, b_cover, t_cover):
Return points of the LShape rebar in the form of array for sketch.</pre> 
<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00039">39</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00039"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a4fcf2dabc065c39ce5c8cf6995051352">   39</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#a4fcf2dabc065c39ce5c8cf6995051352">getpointsOfHelicalRebar</a>(FacePRM, s_cover, b_cover, t_cover, pitch, edges, diameter, size, direction):</div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; getpointsOfHelicalRebar(FacePRM, s_cover, b_cover, t_cover):</span></div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;<span class="stringliteral">    Return points of the LShape rebar in the form of array for sketch.&quot;&quot;&quot;</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;    dx = s_cover + diameter / 2</div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;    dz = float(pitch) / edges</div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;    R = diameter / 2 - dx</div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    R = FacePRM[0][0] / 2 - s_cover</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;    points = []</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;    <span class="keywordflow">if</span> direction[2] <span class="keywordflow">in</span> {-1,1}:</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        z = 0</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        l = 0</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        <span class="keywordflow">if</span> direction[2] == 1:</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;            zz = FacePRM[1][2] - t_cover</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;        <span class="keywordflow">elif</span> direction[2] == -1:</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;            zz = FacePRM[1][2] + b_cover</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;        count = 0</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;        flag = <span class="keyword">False</span></div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        <span class="keywordflow">while</span> (round(z) &lt; abs(size - b_cover - t_cover)):</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;            <span class="keywordflow">for</span> i <span class="keywordflow">in</span> range(0, int(edges) + 1):</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                <span class="keywordflow">if</span> <span class="keywordflow">not</span> i <span class="keywordflow">and</span> flag:</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;                    <span class="keywordflow">continue</span></div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;                <span class="keywordflow">if</span> <span class="keywordflow">not</span> flag:</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                    z -= dz</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;                    flag = <span class="keyword">True</span></div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;                iAngle = i * 360 / edges</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;                x =  FacePRM[1][0] + R * math.cos(math.radians(iAngle))</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;                y =  FacePRM[1][1] + R * math.sin(math.radians(iAngle))</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;                points.append(FreeCAD.Vector(x, y, zz))</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;                count += 1</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;                <span class="keywordflow">if</span> direction[2] == 1:</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;                    zz -= dz</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                <span class="keywordflow">elif</span> direction[2] == -1:</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;                    zz += dz</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;                z += dz</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;    <span class="keywordflow">return</span> points</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="ttc" id="namespaceHelicalRebar_html_a4fcf2dabc065c39ce5c8cf6995051352"><div class="ttname"><a href="namespaceHelicalRebar.html#a4fcf2dabc065c39ce5c8cf6995051352">HelicalRebar.getpointsOfHelicalRebar</a></div><div class="ttdeci">def getpointsOfHelicalRebar(FacePRM, s_cover, b_cover, t_cover, pitch, edges, diameter, size, direction)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00039">HelicalRebar.py:39</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a8a4f12ed70819996ac31877957dfab08"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def HelicalRebar.makeHelicalRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>s_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>pitch</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">makeHelicalRebar(SideCover, BottomCover, Diameter, TopCover, Pitch, Structure, Facename):
Adds the Helical reinforcement bar to the selected structural object.</pre> 
<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00165">165</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00165"></a><span class="lineno"><a class="line" href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08">  165</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08">makeHelicalRebar</a>(s_cover, b_cover, diameter, t_cover, pitch, structure = None, facename = None):</div><div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; makeHelicalRebar(SideCover, BottomCover, Diameter, TopCover, Pitch, Structure, Facename):</span></div><div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;<span class="stringliteral">    Adds the Helical reinforcement bar to the selected structural object.&quot;&quot;&quot;</span></div><div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> structure <span class="keywordflow">and</span> <span class="keywordflow">not</span> facename:</div><div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;        selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;        structure = selected_obj.Object</div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;        facename = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename, <span class="keyword">False</span>)</div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> FacePRM:</div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;        FreeCAD.Console.PrintError(<span class="stringliteral">&quot;Cannot identified shape or from which base object sturctural element is derived\n&quot;</span>)</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;    size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;    normal = face.normalAt(0,0)</div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    <span class="comment">#normal = face.Placement.Rotation.inverted().multVec(normal)</span></div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;    <span class="keyword">import</span> Arch</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;    helix = <a class="code" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">createHelicalWire</a>(FacePRM, s_cover, b_cover, t_cover, pitch, size, normal)</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;    helix.Support = [(structure, facename)]</div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;    rebar = Arch.makeRebar(structure, helix, diameter, 1, 0)</div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;    rebar.OffsetStart = 0</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    rebar.OffsetEnd = 0</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;    <span class="comment"># Adds properties to the rebar object</span></div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;    rebar.ViewObject.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;RebarShape&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).RebarShape = <span class="stringliteral">&quot;HelicalRebar&quot;</span></div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;    rebar.ViewObject.setEditorMode(<span class="stringliteral">&quot;RebarShape&quot;</span>, 2)</div><div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;SideCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Front cover of rebar&quot;</span>)).SideCover = s_cover</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;SideCover&quot;</span>, 2)</div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;Pitch&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Left Side cover of rebar&quot;</span>)).Pitch = pitch</div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;Pitch&quot;</span>, 2)</div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BottomCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bottom cover of rebar&quot;</span>)).BottomCover = b_cover</div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BottomCover&quot;</span>, 2)</div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TopCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Top cover of rebar&quot;</span>)).TopCover = t_cover</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TopCover&quot;</span>, 2)</div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;    rebar.Label = <span class="stringliteral">&quot;HelicalRebar&quot;</span></div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;    <span class="keywordflow">return</span> rebar</div><div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;</div><div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_a8a4f12ed70819996ac31877957dfab08"><div class="ttname"><a href="namespaceHelicalRebar.html#a8a4f12ed70819996ac31877957dfab08">HelicalRebar.makeHelicalRebar</a></div><div class="ttdeci">def makeHelicalRebar(s_cover, b_cover, diameter, t_cover, pitch, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00165">HelicalRebar.py:165</a></div></div>
<div class="ttc" id="namespaceHelicalRebar_html_a1a2b3ce39b904ab0c3892ed0965d2844"><div class="ttname"><a href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844">HelicalRebar.createHelicalWire</a></div><div class="ttdeci">def createHelicalWire(FacePRM, s_cover, b_cover, t_cover, pitch, size, direction, helix=None)</div><div class="ttdef"><b>Definition:</b> <a href="HelicalRebar_8py_source.html#l00075">HelicalRebar.py:75</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceHelicalRebar_a8a4f12ed70819996ac31877957dfab08_cgraph.png" border="0" usemap="#namespaceHelicalRebar_a8a4f12ed70819996ac31877957dfab08_cgraph" alt=""/></div>
<map name="namespaceHelicalRebar_a8a4f12ed70819996ac31877957dfab08_cgraph" id="namespaceHelicalRebar_a8a4f12ed70819996ac31877957dfab08_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="489,5,668,32"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="227,31,441,57"/>
<area shape="rect" id="node4" href="namespaceHelicalRebar.html#a1a2b3ce39b904ab0c3892ed0965d2844" title="HelicalRebar.createHelicalWire" alt="" coords="232,81,436,108"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceHelicalRebar_a8a4f12ed70819996ac31877957dfab08_icgraph.png" border="0" usemap="#namespaceHelicalRebar_a8a4f12ed70819996ac31877957dfab08_icgraph" alt=""/></div>
<map name="namespaceHelicalRebar_a8a4f12ed70819996ac31877957dfab08_icgraph" id="namespaceHelicalRebar_a8a4f12ed70819996ac31877957dfab08_icgraph">
<area shape="rect" id="node2" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#acdfb101876d4841ba277e2e884ebaf9d" title="HelicalRebar._HelicalRebar\lTaskPanel.accept" alt="" coords="227,165,409,207"/>
<area shape="rect" id="node3" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce" title="HelicalRebar._HelicalRebar\lTaskPanel.clicked" alt="" coords="474,5,657,47"/>
<area shape="rect" id="node4" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="470,71,661,112"/>
<area shape="rect" id="node5" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="457,136,673,177"/>
<area shape="rect" id="node6" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="457,202,673,229"/>
<area shape="rect" id="node7" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="469,253,662,295"/>
<area shape="rect" id="node8" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="467,319,664,360"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="a925dcfed2ffef215413157f48d7b6e57"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string HelicalRebar.__author__ = &quot;Amritpal Singh&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00025">25</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="a28c95505364eadd0c2d4abbd80091bef"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string HelicalRebar.__title__ = &quot;HelicalRebar&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00024">24</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="a9c74e4634d00eef07ed630054e69fbff"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string HelicalRebar.__url__ = &quot;https://www.freecadweb.org&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="HelicalRebar_8py_source.html#l00026">26</a> of file <a class="el" href="HelicalRebar_8py_source.html">HelicalRebar.py</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Wed Dec 13 2017 22:36:42 for Rebar Addon for FreeCAD by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.11
</small></address>
</body>
</html>
