<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Rebar Addon for FreeCAD: LShapeRebar Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Rebar Addon for FreeCAD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="namespaces.html"><span>Namespace&#160;List</span></a></li>
      <li><a href="namespacemembers.html"><span>Namespace&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">LShapeRebar Namespace Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html">_LShapeRebarTaskPanel</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a3019960c6f6476cb70df9ee06f330dfb"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb">getpointsOfLShapeRebar</a> (FacePRM, l_cover, r_cover, b_cover, t_cover, orientation)</td></tr>
<tr class="separator:a3019960c6f6476cb70df9ee06f330dfb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a647a28e94933108c6617da8532d76998"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceLShapeRebar.html#a647a28e94933108c6617da8532d76998">makeLShapeRebar</a> (f_cover, b_cover, l_cover, r_cover, diameter, t_cover, rounding, amount_spacing_check, amount_spacing_value, orientation=&quot;Bottom Left&quot;, structure=None, facename=None)</td></tr>
<tr class="separator:a647a28e94933108c6617da8532d76998"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9915291e3457e1c27f556d7903e02486"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceLShapeRebar.html#a9915291e3457e1c27f556d7903e02486">editLShapeRebar</a> (Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, rounding, amount_spacing_check, amount_spacing_value, orientation, structure=None, facename=None)</td></tr>
<tr class="separator:a9915291e3457e1c27f556d7903e02486"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a73f1b8d577fecf230a8c071424b2015e"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceLShapeRebar.html#a73f1b8d577fecf230a8c071424b2015e">editDialog</a> (vobj)</td></tr>
<tr class="separator:a73f1b8d577fecf230a8c071424b2015e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5439b0c3265fa6d432d4a81e47f4441e"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceLShapeRebar.html#a5439b0c3265fa6d432d4a81e47f4441e">CommandLShapeRebar</a> ()</td></tr>
<tr class="separator:a5439b0c3265fa6d432d4a81e47f4441e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a0ac8e9cb97e560c6ce362c1ac5144c31"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceLShapeRebar.html#a0ac8e9cb97e560c6ce362c1ac5144c31">__title__</a> = &quot;LShapeRebar&quot;</td></tr>
<tr class="separator:a0ac8e9cb97e560c6ce362c1ac5144c31"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad398517c2df8a455dfd0b670e54285ea"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceLShapeRebar.html#ad398517c2df8a455dfd0b670e54285ea">__author__</a> = &quot;Amritpal Singh&quot;</td></tr>
<tr class="separator:ad398517c2df8a455dfd0b670e54285ea"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7bca929f0dda68928d1f3978b4e877f8"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceLShapeRebar.html#a7bca929f0dda68928d1f3978b4e877f8">__url__</a> = &quot;https://www.freecadweb.org&quot;</td></tr>
<tr class="separator:a7bca929f0dda68928d1f3978b4e877f8"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a5439b0c3265fa6d432d4a81e47f4441e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def LShapeRebar.CommandLShapeRebar </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="LShapeRebar_8py_source.html#l00300">300</a> of file <a class="el" href="LShapeRebar_8py_source.html">LShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00300"></a><span class="lineno"><a class="line" href="namespaceLShapeRebar.html#a5439b0c3265fa6d432d4a81e47f4441e">  300</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceLShapeRebar.html#a5439b0c3265fa6d432d4a81e47f4441e">CommandLShapeRebar</a>():</div><div class="line"><a name="l00301"></a><span class="lineno">  301</span>&#160;    selected_obj = <a class="code" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">check_selected_face</a>()</div><div class="line"><a name="l00302"></a><span class="lineno">  302</span>&#160;    <span class="keywordflow">if</span> selected_obj:</div><div class="line"><a name="l00303"></a><span class="lineno">  303</span>&#160;        FreeCADGui.Control.showDialog(<a class="code" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html">_LShapeRebarTaskPanel</a>())</div><div class="line"><a name="l00304"></a><span class="lineno">  304</span>&#160;<div class="ttc" id="namespaceRebarfunc_html_adae2713855a7e1b4bda04081ae671542"><div class="ttname"><a href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">Rebarfunc.check_selected_face</a></div><div class="ttdeci">def check_selected_face()</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00255">Rebarfunc.py:255</a></div></div>
<div class="ttc" id="namespaceLShapeRebar_html_a5439b0c3265fa6d432d4a81e47f4441e"><div class="ttname"><a href="namespaceLShapeRebar.html#a5439b0c3265fa6d432d4a81e47f4441e">LShapeRebar.CommandLShapeRebar</a></div><div class="ttdeci">def CommandLShapeRebar()</div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00300">LShapeRebar.py:300</a></div></div>
<div class="ttc" id="classLShapeRebar_1_1__LShapeRebarTaskPanel_html"><div class="ttname"><a href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html">LShapeRebar._LShapeRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00076">LShapeRebar.py:76</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e_cgraph.png" border="0" usemap="#namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e_cgraph" alt=""/></div>
<map name="namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e_cgraph" id="namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542" title="Rebarfunc.check_selected_face" alt="" coords="263,13,472,39"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="520,13,685,39"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="733,13,869,39"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e_icgraph.png" border="0" usemap="#namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e_icgraph" alt=""/></div>
<map name="namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e_icgraph" id="namespaceLShapeRebar_a5439b0c3265fa6d432d4a81e47f4441e_icgraph">
<area shape="rect" id="node2" href="classRebarTools_1_1LShapeRebarTool.html#aa3d0620b97ea017d8225c923b361d224" title="RebarTools.LShapeRebarTool.\lActivated" alt="" coords="263,5,464,47"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a73f1b8d577fecf230a8c071424b2015e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def LShapeRebar.editDialog </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>vobj</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="LShapeRebar_8py_source.html#l00278">278</a> of file <a class="el" href="LShapeRebar_8py_source.html">LShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00278"></a><span class="lineno"><a class="line" href="namespaceLShapeRebar.html#a73f1b8d577fecf230a8c071424b2015e">  278</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceLShapeRebar.html#a73f1b8d577fecf230a8c071424b2015e">editDialog</a>(vobj):</div><div class="line"><a name="l00279"></a><span class="lineno">  279</span>&#160;    FreeCADGui.Control.closeDialog()</div><div class="line"><a name="l00280"></a><span class="lineno">  280</span>&#160;    obj = <a class="code" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html">_LShapeRebarTaskPanel</a>(vobj.Object)</div><div class="line"><a name="l00281"></a><span class="lineno">  281</span>&#160;    obj.form.frontCover.setText(str(vobj.Object.FrontCover))</div><div class="line"><a name="l00282"></a><span class="lineno">  282</span>&#160;    obj.form.l_sideCover.setText(str(vobj.Object.LeftCover))</div><div class="line"><a name="l00283"></a><span class="lineno">  283</span>&#160;    obj.form.r_sideCover.setText(str(vobj.Object.RightCover))</div><div class="line"><a name="l00284"></a><span class="lineno">  284</span>&#160;    obj.form.bottomCover.setText(str(vobj.Object.BottomCover))</div><div class="line"><a name="l00285"></a><span class="lineno">  285</span>&#160;    obj.form.diameter.setText(str(vobj.Object.Diameter))</div><div class="line"><a name="l00286"></a><span class="lineno">  286</span>&#160;    obj.form.topCover.setText(str(vobj.Object.TopCover))</div><div class="line"><a name="l00287"></a><span class="lineno">  287</span>&#160;    obj.form.rounding.setValue(vobj.Object.Rounding)</div><div class="line"><a name="l00288"></a><span class="lineno">  288</span>&#160;    obj.form.orientation.setCurrentIndex(obj.form.orientation.findText(str(vobj.Object.Orientation)))</div><div class="line"><a name="l00289"></a><span class="lineno">  289</span>&#160;    <span class="keywordflow">if</span> vobj.Object.AmountCheck:</div><div class="line"><a name="l00290"></a><span class="lineno">  290</span>&#160;        obj.form.amount.setValue(vobj.Object.Amount)</div><div class="line"><a name="l00291"></a><span class="lineno">  291</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00292"></a><span class="lineno">  292</span>&#160;        obj.form.amount_radio.setChecked(<span class="keyword">False</span>)</div><div class="line"><a name="l00293"></a><span class="lineno">  293</span>&#160;        obj.form.spacing_radio.setChecked(<span class="keyword">True</span>)</div><div class="line"><a name="l00294"></a><span class="lineno">  294</span>&#160;        obj.form.amount.setDisabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00295"></a><span class="lineno">  295</span>&#160;        obj.form.spacing.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00296"></a><span class="lineno">  296</span>&#160;        obj.form.spacing.setText(str(vobj.Object.TrueSpacing))</div><div class="line"><a name="l00297"></a><span class="lineno">  297</span>&#160;    <span class="comment">#obj.form.PickSelectedFace.setVisible(False)</span></div><div class="line"><a name="l00298"></a><span class="lineno">  298</span>&#160;    FreeCADGui.Control.showDialog(obj)</div><div class="line"><a name="l00299"></a><span class="lineno">  299</span>&#160;</div><div class="ttc" id="classLShapeRebar_1_1__LShapeRebarTaskPanel_html"><div class="ttname"><a href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html">LShapeRebar._LShapeRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00076">LShapeRebar.py:76</a></div></div>
<div class="ttc" id="namespaceLShapeRebar_html_a73f1b8d577fecf230a8c071424b2015e"><div class="ttname"><a href="namespaceLShapeRebar.html#a73f1b8d577fecf230a8c071424b2015e">LShapeRebar.editDialog</a></div><div class="ttdeci">def editDialog(vobj)</div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00278">LShapeRebar.py:278</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a9915291e3457e1c27f556d7903e02486"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def LShapeRebar.editLShapeRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>Rebar</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>f_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rounding</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_check</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_value</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="LShapeRebar_8py_source.html#l00230">230</a> of file <a class="el" href="LShapeRebar_8py_source.html">LShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00230"></a><span class="lineno"><a class="line" href="namespaceLShapeRebar.html#a9915291e3457e1c27f556d7903e02486">  230</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceLShapeRebar.html#a9915291e3457e1c27f556d7903e02486">editLShapeRebar</a>(Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, rounding, amount_spacing_check, amount_spacing_value, orientation, structure = None, facename = None):</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;    sketch = Rebar.Base</div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;    <span class="keywordflow">if</span> structure <span class="keywordflow">and</span> facename:</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;        sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;    <span class="comment"># Check if sketch support is empty.</span></div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> sketch.Support:</div><div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;        <a class="code" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">showWarning</a>(<span class="stringliteral">&quot;You have checked remove external geometry of base sketchs when needed.\nTo unchecked Edit-&gt;Preferences-&gt;Arch.&quot;</span>)</div><div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00238"></a><span class="lineno">  238</span>&#160;    <span class="comment"># Assigned values</span></div><div class="line"><a name="l00239"></a><span class="lineno">  239</span>&#160;    facename = sketch.Support[0][1][0]</div><div class="line"><a name="l00240"></a><span class="lineno">  240</span>&#160;    structure = sketch.Support[0][0]</div><div class="line"><a name="l00241"></a><span class="lineno">  241</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00242"></a><span class="lineno">  242</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00243"></a><span class="lineno">  243</span>&#160;    <span class="comment"># Get parameters of the face where sketch of rebar is drawn</span></div><div class="line"><a name="l00244"></a><span class="lineno">  244</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename)</div><div class="line"><a name="l00245"></a><span class="lineno">  245</span>&#160;    <span class="comment"># Get points of L-Shape rebar</span></div><div class="line"><a name="l00246"></a><span class="lineno">  246</span>&#160;    points = <a class="code" href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb">getpointsOfLShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, orientation)</div><div class="line"><a name="l00247"></a><span class="lineno">  247</span>&#160;    sketch.movePoint(0, 1, points[0], 0)</div><div class="line"><a name="l00248"></a><span class="lineno">  248</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00249"></a><span class="lineno">  249</span>&#160;    sketch.movePoint(0, 2, points[1], 0)</div><div class="line"><a name="l00250"></a><span class="lineno">  250</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00251"></a><span class="lineno">  251</span>&#160;    sketch.movePoint(1, 1, points[1], 0)</div><div class="line"><a name="l00252"></a><span class="lineno">  252</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00253"></a><span class="lineno">  253</span>&#160;    sketch.movePoint(1, 2, points[2], 0)</div><div class="line"><a name="l00254"></a><span class="lineno">  254</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00255"></a><span class="lineno">  255</span>&#160;    Rebar.OffsetStart = f_cover</div><div class="line"><a name="l00256"></a><span class="lineno">  256</span>&#160;    Rebar.OffsetEnd = f_cover</div><div class="line"><a name="l00257"></a><span class="lineno">  257</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00258"></a><span class="lineno">  258</span>&#160;        Rebar.Amount = amount_spacing_value</div><div class="line"><a name="l00259"></a><span class="lineno">  259</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00260"></a><span class="lineno">  260</span>&#160;        Rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00261"></a><span class="lineno">  261</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00262"></a><span class="lineno">  262</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00263"></a><span class="lineno">  263</span>&#160;        Rebar.Amount = int((size - diameter) / amount_spacing_value)</div><div class="line"><a name="l00264"></a><span class="lineno">  264</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00265"></a><span class="lineno">  265</span>&#160;        Rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00266"></a><span class="lineno">  266</span>&#160;    Rebar.Diameter = diameter</div><div class="line"><a name="l00267"></a><span class="lineno">  267</span>&#160;    Rebar.FrontCover = f_cover</div><div class="line"><a name="l00268"></a><span class="lineno">  268</span>&#160;    Rebar.LeftCover = l_cover</div><div class="line"><a name="l00269"></a><span class="lineno">  269</span>&#160;    Rebar.RightCover = r_cover</div><div class="line"><a name="l00270"></a><span class="lineno">  270</span>&#160;    Rebar.BottomCover = b_cover</div><div class="line"><a name="l00271"></a><span class="lineno">  271</span>&#160;    Rebar.TopCover = t_cover</div><div class="line"><a name="l00272"></a><span class="lineno">  272</span>&#160;    Rebar.Rounding = rounding</div><div class="line"><a name="l00273"></a><span class="lineno">  273</span>&#160;    Rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00274"></a><span class="lineno">  274</span>&#160;    Rebar.Orientation = orientation</div><div class="line"><a name="l00275"></a><span class="lineno">  275</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00276"></a><span class="lineno">  276</span>&#160;    <span class="keywordflow">return</span> Rebar</div><div class="line"><a name="l00277"></a><span class="lineno">  277</span>&#160;</div><div class="ttc" id="namespaceLShapeRebar_html_a9915291e3457e1c27f556d7903e02486"><div class="ttname"><a href="namespaceLShapeRebar.html#a9915291e3457e1c27f556d7903e02486">LShapeRebar.editLShapeRebar</a></div><div class="ttdeci">def editLShapeRebar(Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, rounding, amount_spacing_check, amount_spacing_value, orientation, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00230">LShapeRebar.py:230</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceLShapeRebar_html_a3019960c6f6476cb70df9ee06f330dfb"><div class="ttname"><a href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb">LShapeRebar.getpointsOfLShapeRebar</a></div><div class="ttdeci">def getpointsOfLShapeRebar(FacePRM, l_cover, r_cover, b_cover, t_cover, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00040">LShapeRebar.py:40</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a2278a0602d46a62953af1fcf2e574a94"><div class="ttname"><a href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">Rebarfunc.showWarning</a></div><div class="ttdeci">def showWarning(message)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00293">Rebarfunc.py:293</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486_cgraph.png" border="0" usemap="#namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486_cgraph" alt=""/></div>
<map name="namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486_cgraph" id="namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="284,5,449,32"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="523,81,701,108"/>
<area shape="rect" id="node5" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="259,107,474,133"/>
<area shape="rect" id="node6" href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb" title="LShapeRebar.getpointsOfLShape\lRebar" alt="" coords="259,158,475,199"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="544,5,680,32"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486_icgraph.png" border="0" usemap="#namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486_icgraph" alt=""/></div>
<map name="namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486_icgraph" id="namespaceLShapeRebar_a9915291e3457e1c27f556d7903e02486_icgraph">
<area shape="rect" id="node2" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#a4d62ad224c06875ec721ba9acbdea774" title="LShapeRebar._LShapeRebar\lTaskPanel.accept" alt="" coords="259,129,449,171"/>
<area shape="rect" id="node3" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="510,5,701,47"/>
<area shape="rect" id="node4" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="497,71,713,112"/>
<area shape="rect" id="node5" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="497,137,713,163"/>
<area shape="rect" id="node6" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="509,188,702,229"/>
<area shape="rect" id="node7" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="507,253,704,295"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a3019960c6f6476cb70df9ee06f330dfb"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def LShapeRebar.getpointsOfLShapeRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>FacePRM</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">getpointsOfLShapeRebar(FacePRM, LeftCover, RightCover, BottomCover, TopCover, Orientation):
Return points of the LShape rebar in the form of array for sketch.
It takes four different orientations input i.e. 'Bottom Left', 'Bottom Right ', 'Top Left', 'Top Right'.
</pre> 
<p>Definition at line <a class="el" href="LShapeRebar_8py_source.html#l00040">40</a> of file <a class="el" href="LShapeRebar_8py_source.html">LShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb">   40</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb">getpointsOfLShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, orientation):</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; getpointsOfLShapeRebar(FacePRM, LeftCover, RightCover, BottomCover, TopCover, Orientation):</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="stringliteral">    Return points of the LShape rebar in the form of array for sketch.</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;<span class="stringliteral">    It takes four different orientations input i.e. &#39;Bottom Left&#39;, &#39;Bottom Right &#39;, &#39;Top Left&#39;, &#39;Top Right&#39;.</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    <span class="keywordflow">if</span> orientation == <span class="stringliteral">&quot;Bottom Left&quot;</span>:</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r_cover</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;        y3 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Bottom Right&quot;</span>:</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r_cover</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;        x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r_cover</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;        x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;        y3 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Top Left&quot;</span>:</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;        y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;        x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;        y2 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;        x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r_cover</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;        y3 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Top Right&quot;</span>:</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r_cover</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;        y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;        x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - r_cover</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;        y2 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;        y3 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;    <span class="keywordflow">return</span> [FreeCAD.Vector(x1, y1, 0), FreeCAD.Vector(x2, y2, 0),\</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;           FreeCAD.Vector(x3, y3, 0)]</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;</div><div class="ttc" id="namespaceLShapeRebar_html_a3019960c6f6476cb70df9ee06f330dfb"><div class="ttname"><a href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb">LShapeRebar.getpointsOfLShapeRebar</a></div><div class="ttdeci">def getpointsOfLShapeRebar(FacePRM, l_cover, r_cover, b_cover, t_cover, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00040">LShapeRebar.py:40</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceLShapeRebar_a3019960c6f6476cb70df9ee06f330dfb_icgraph.png" border="0" usemap="#namespaceLShapeRebar_a3019960c6f6476cb70df9ee06f330dfb_icgraph" alt=""/></div>
<map name="namespaceLShapeRebar_a3019960c6f6476cb70df9ee06f330dfb_icgraph" id="namespaceLShapeRebar_a3019960c6f6476cb70df9ee06f330dfb_icgraph">
<area shape="rect" id="node2" href="namespaceLShapeRebar.html#a647a28e94933108c6617da8532d76998" title="LShapeRebar.makeLShapeRebar" alt="" coords="269,111,485,138"/>
<area shape="rect" id="node9" href="namespaceLShapeRebar.html#a9915291e3457e1c27f556d7903e02486" title="LShapeRebar.editLShapeRebar" alt="" coords="275,162,480,189"/>
<area shape="rect" id="node3" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#a4d62ad224c06875ec721ba9acbdea774" title="LShapeRebar._LShapeRebar\lTaskPanel.accept" alt="" coords="533,129,724,171"/>
<area shape="rect" id="node4" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="785,5,975,47"/>
<area shape="rect" id="node5" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="772,71,988,112"/>
<area shape="rect" id="node6" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="772,137,988,163"/>
<area shape="rect" id="node7" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="783,188,977,229"/>
<area shape="rect" id="node8" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="781,253,979,295"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a647a28e94933108c6617da8532d76998"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def LShapeRebar.makeLShapeRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>f_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rounding</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_check</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_value</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em> = <code>&quot;Bottom&#160;Left&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">makeLShapeRebar(FrontCover, BottomCover, LeftCover, RightCover, Diameter, TopCover, Rounding, AmountSpacingCheck, AmountSpacingValue,
Orientation, Structure, Facename): Adds the L-Shape reinforcement bar to the selected structural object.
It takes four different orientations input i.e. 'Bottom Left', 'Bottom Right ', 'Top Left', 'Top Right'.
</pre> 
<p>Definition at line <a class="el" href="LShapeRebar_8py_source.html#l00169">169</a> of file <a class="el" href="LShapeRebar_8py_source.html">LShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00169"></a><span class="lineno"><a class="line" href="namespaceLShapeRebar.html#a647a28e94933108c6617da8532d76998">  169</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceLShapeRebar.html#a647a28e94933108c6617da8532d76998">makeLShapeRebar</a>(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, rounding, amount_spacing_check, amount_spacing_value, orientation = &quot;Bottom Left&quot;, structure = None, facename = None):</div><div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; makeLShapeRebar(FrontCover, BottomCover, LeftCover, RightCover, Diameter, TopCover, Rounding, AmountSpacingCheck, AmountSpacingValue,</span></div><div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;<span class="stringliteral">    Orientation, Structure, Facename): Adds the L-Shape reinforcement bar to the selected structural object.</span></div><div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;<span class="stringliteral">    It takes four different orientations input i.e. &#39;Bottom Left&#39;, &#39;Bottom Right &#39;, &#39;Top Left&#39;, &#39;Top Right&#39;.</span></div><div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div><div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> structure <span class="keywordflow">and</span> <span class="keywordflow">not</span> facename:</div><div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;        selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;        structure = selected_obj.Object</div><div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;        facename = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename)</div><div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> FacePRM:</div><div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;        FreeCAD.Console.PrintError(<span class="stringliteral">&quot;Cannot identified shape or from which base object sturctural element is derived\n&quot;</span>)</div><div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;    <span class="comment"># Get points of L-Shape rebar</span></div><div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;    points = <a class="code" href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb">getpointsOfLShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, orientation)</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    <span class="keyword">import</span> Part</div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;    <span class="keyword">import</span> Arch</div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;    sketch = FreeCAD.activeDocument().addObject(<span class="stringliteral">&#39;Sketcher::SketchObject&#39;</span>, <span class="stringliteral">&#39;Sketch&#39;</span>)</div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;    sketch.MapMode = <span class="stringliteral">&quot;FlatFace&quot;</span></div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;    sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;    sketch.addGeometry(Part.LineSegment(points[0], points[1]), <span class="keyword">False</span>)</div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;    sketch.addGeometry(Part.LineSegment(points[1], points[2]), <span class="keyword">False</span>)</div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;    <span class="keyword">import</span> Sketcher</div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;        rebar = Arch.makeRebar(structure, sketch, diameter, amount_spacing_value, f_cover)</div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;        rebar = Arch.makeRebar(structure, sketch, diameter, int((size - diameter) / amount_spacing_value), f_cover)</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;    rebar.Rounding = rounding</div><div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;    <span class="comment"># Adds properties to the rebar object</span></div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;    rebar.ViewObject.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;RebarShape&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).RebarShape = <span class="stringliteral">&quot;LShapeRebar&quot;</span></div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;    rebar.ViewObject.setEditorMode(<span class="stringliteral">&quot;RebarShape&quot;</span>, 2)</div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;FrontCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Front cover of rebar&quot;</span>)).FrontCover = f_cover</div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;FrontCover&quot;</span>, 2)</div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;LeftCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Left Side cover of rebar&quot;</span>)).LeftCover = l_cover</div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;LeftCover&quot;</span>, 2)</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;RightCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Right Side cover of rebar&quot;</span>)).RightCover = r_cover</div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;RightCover&quot;</span>, 2)</div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BottomCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bottom cover of rebar&quot;</span>)).BottomCover = b_cover</div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BottomCover&quot;</span>, 2)</div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyBool&quot;</span>, <span class="stringliteral">&quot;AmountCheck&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Amount radio button is checked&quot;</span>)).AmountCheck</div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;AmountCheck&quot;</span>, 2)</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TopCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Top cover of rebar&quot;</span>)).TopCover = t_cover</div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TopCover&quot;</span>, 2)</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TrueSpacing&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Spacing between of rebars&quot;</span>)).TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;Orientation&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).Orientation = orientation</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;Orientation&quot;</span>, 2)</div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TrueSpacing&quot;</span>, 2)</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;        rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;        rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;        rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;    rebar.Label = <span class="stringliteral">&quot;LShapeRebar&quot;</span></div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;    <span class="keywordflow">return</span> rebar</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;</div><div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceLShapeRebar_html_a3019960c6f6476cb70df9ee06f330dfb"><div class="ttname"><a href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb">LShapeRebar.getpointsOfLShapeRebar</a></div><div class="ttdeci">def getpointsOfLShapeRebar(FacePRM, l_cover, r_cover, b_cover, t_cover, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00040">LShapeRebar.py:40</a></div></div>
<div class="ttc" id="namespaceLShapeRebar_html_a647a28e94933108c6617da8532d76998"><div class="ttname"><a href="namespaceLShapeRebar.html#a647a28e94933108c6617da8532d76998">LShapeRebar.makeLShapeRebar</a></div><div class="ttdeci">def makeLShapeRebar(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, rounding, amount_spacing_check, amount_spacing_value, orientation=&quot;Bottom Left&quot;, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="LShapeRebar_8py_source.html#l00169">LShapeRebar.py:169</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceLShapeRebar_a647a28e94933108c6617da8532d76998_cgraph.png" border="0" usemap="#namespaceLShapeRebar_a647a28e94933108c6617da8532d76998_cgraph" alt=""/></div>
<map name="namespaceLShapeRebar_a647a28e94933108c6617da8532d76998_cgraph" id="namespaceLShapeRebar_a647a28e94933108c6617da8532d76998_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="533,5,712,32"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="270,31,485,57"/>
<area shape="rect" id="node4" href="namespaceLShapeRebar.html#a3019960c6f6476cb70df9ee06f330dfb" title="LShapeRebar.getpointsOfLShape\lRebar" alt="" coords="269,82,485,123"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceLShapeRebar_a647a28e94933108c6617da8532d76998_icgraph.png" border="0" usemap="#namespaceLShapeRebar_a647a28e94933108c6617da8532d76998_icgraph" alt=""/></div>
<map name="namespaceLShapeRebar_a647a28e94933108c6617da8532d76998_icgraph" id="namespaceLShapeRebar_a647a28e94933108c6617da8532d76998_icgraph">
<area shape="rect" id="node2" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#a4d62ad224c06875ec721ba9acbdea774" title="LShapeRebar._LShapeRebar\lTaskPanel.accept" alt="" coords="269,129,460,171"/>
<area shape="rect" id="node3" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="521,5,711,47"/>
<area shape="rect" id="node4" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="508,71,724,112"/>
<area shape="rect" id="node5" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="508,137,724,163"/>
<area shape="rect" id="node6" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="519,188,713,229"/>
<area shape="rect" id="node7" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="517,253,715,295"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="ad398517c2df8a455dfd0b670e54285ea"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string LShapeRebar.__author__ = &quot;Amritpal Singh&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="LShapeRebar_8py_source.html#l00025">25</a> of file <a class="el" href="LShapeRebar_8py_source.html">LShapeRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="a0ac8e9cb97e560c6ce362c1ac5144c31"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string LShapeRebar.__title__ = &quot;LShapeRebar&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="LShapeRebar_8py_source.html#l00024">24</a> of file <a class="el" href="LShapeRebar_8py_source.html">LShapeRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="a7bca929f0dda68928d1f3978b4e877f8"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string LShapeRebar.__url__ = &quot;https://www.freecadweb.org&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="LShapeRebar_8py_source.html#l00026">26</a> of file <a class="el" href="LShapeRebar_8py_source.html">LShapeRebar.py</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Wed Dec 13 2017 22:36:42 for Rebar Addon for FreeCAD by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.11
</small></address>
</body>
</html>
