<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Rebar Addon for FreeCAD: BentShapeRebar Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Rebar Addon for FreeCAD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="namespaces.html"><span>Namespace&#160;List</span></a></li>
      <li><a href="namespacemembers.html"><span>Namespace&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">BentShapeRebar Namespace Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">_BentShapeRebarTaskPanel</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a33951a8ab21a73bae42af9f81d7c43c3"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">getpointsOfBentShapeRebar</a> (FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</td></tr>
<tr class="separator:a33951a8ab21a73bae42af9f81d7c43c3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aac46779d3e1905db5a3788917f6e2476"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">makeBentShapeRebar</a> (f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation=&quot;Bottom Left&quot;, structure=None, facename=None)</td></tr>
<tr class="separator:aac46779d3e1905db5a3788917f6e2476"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a941d005845cd497c0beb12bb8fef9171"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">editBentShapeRebar</a> (Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation, structure=None, facename=None)</td></tr>
<tr class="separator:a941d005845cd497c0beb12bb8fef9171"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae5db82a49148a0a8f6fa567fa72d93b2"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceBentShapeRebar.html#ae5db82a49148a0a8f6fa567fa72d93b2">editDialog</a> (vobj)</td></tr>
<tr class="separator:ae5db82a49148a0a8f6fa567fa72d93b2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abc4f0ada7811da5cf9174551bc3c6b37"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceBentShapeRebar.html#abc4f0ada7811da5cf9174551bc3c6b37">CommandBentShapeRebar</a> ()</td></tr>
<tr class="separator:abc4f0ada7811da5cf9174551bc3c6b37"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a38b223debc1826fd2855773a02749bb4"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceBentShapeRebar.html#a38b223debc1826fd2855773a02749bb4">__title__</a> = &quot;BentShapeRebar&quot;</td></tr>
<tr class="separator:a38b223debc1826fd2855773a02749bb4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad79a2dbf88601c24aae561033cb48d34"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceBentShapeRebar.html#ad79a2dbf88601c24aae561033cb48d34">__author__</a> = &quot;Amritpal Singh&quot;</td></tr>
<tr class="separator:ad79a2dbf88601c24aae561033cb48d34"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aec768ca6a259d1cc738ea11c79a124e2"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceBentShapeRebar.html#aec768ca6a259d1cc738ea11c79a124e2">__url__</a> = &quot;https://www.freecadweb.org&quot;</td></tr>
<tr class="separator:aec768ca6a259d1cc738ea11c79a124e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="abc4f0ada7811da5cf9174551bc3c6b37"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar.CommandBentShapeRebar </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00359">359</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00359"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#abc4f0ada7811da5cf9174551bc3c6b37">  359</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#abc4f0ada7811da5cf9174551bc3c6b37">CommandBentShapeRebar</a>():</div><div class="line"><a name="l00360"></a><span class="lineno">  360</span>&#160;    selected_obj = <a class="code" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">check_selected_face</a>()</div><div class="line"><a name="l00361"></a><span class="lineno">  361</span>&#160;    <span class="keywordflow">if</span> selected_obj:</div><div class="line"><a name="l00362"></a><span class="lineno">  362</span>&#160;        FreeCADGui.Control.showDialog(<a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">_BentShapeRebarTaskPanel</a>())</div><div class="line"><a name="l00363"></a><span class="lineno">  363</span>&#160;<div class="ttc" id="namespaceRebarfunc_html_adae2713855a7e1b4bda04081ae671542"><div class="ttname"><a href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">Rebarfunc.check_selected_face</a></div><div class="ttdeci">def check_selected_face()</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00255">Rebarfunc.py:255</a></div></div>
<div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">BentShapeRebar._BentShapeRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00105">BentShapeRebar.py:105</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_abc4f0ada7811da5cf9174551bc3c6b37"><div class="ttname"><a href="namespaceBentShapeRebar.html#abc4f0ada7811da5cf9174551bc3c6b37">BentShapeRebar.CommandBentShapeRebar</a></div><div class="ttdeci">def CommandBentShapeRebar()</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00359">BentShapeRebar.py:359</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37_cgraph.png" border="0" usemap="#namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37_cgraph" alt=""/></div>
<map name="namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37_cgraph" id="namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542" title="Rebarfunc.check_selected_face" alt="" coords="265,13,475,39"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="523,13,688,39"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="736,13,872,39"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37_icgraph.png" border="0" usemap="#namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37_icgraph" alt=""/></div>
<map name="namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37_icgraph" id="namespaceBentShapeRebar_abc4f0ada7811da5cf9174551bc3c6b37_icgraph">
<area shape="rect" id="node2" href="classRebarTools_1_1BentShapeRebarTool.html#a585e9cc95894ac70b9c2257eee535dcb" title="RebarTools.BentShapeRebar\lTool.Activated" alt="" coords="265,5,457,47"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a941d005845cd497c0beb12bb8fef9171"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar.editBentShapeRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>Rebar</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>f_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentLength</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentAngle</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rounding</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_check</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_value</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00270">270</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00270"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">  270</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">editBentShapeRebar</a>(Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation, structure = None, facename = None):</div><div class="line"><a name="l00271"></a><span class="lineno">  271</span>&#160;    sketch = Rebar.Base</div><div class="line"><a name="l00272"></a><span class="lineno">  272</span>&#160;    <span class="keywordflow">if</span> structure <span class="keywordflow">and</span> facename:</div><div class="line"><a name="l00273"></a><span class="lineno">  273</span>&#160;        sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00274"></a><span class="lineno">  274</span>&#160;    <span class="comment"># Check if sketch support is empty.</span></div><div class="line"><a name="l00275"></a><span class="lineno">  275</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> sketch.Support:</div><div class="line"><a name="l00276"></a><span class="lineno">  276</span>&#160;        <a class="code" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">showWarning</a>(<span class="stringliteral">&quot;You have checked remove external geometry of base sketchs when needed.\nTo unchecked Edit-&gt;Preferences-&gt;Arch.&quot;</span>)</div><div class="line"><a name="l00277"></a><span class="lineno">  277</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00278"></a><span class="lineno">  278</span>&#160;    <span class="comment"># Assigned values</span></div><div class="line"><a name="l00279"></a><span class="lineno">  279</span>&#160;    facename = sketch.Support[0][1][0]</div><div class="line"><a name="l00280"></a><span class="lineno">  280</span>&#160;    structure = sketch.Support[0][0]</div><div class="line"><a name="l00281"></a><span class="lineno">  281</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00282"></a><span class="lineno">  282</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00283"></a><span class="lineno">  283</span>&#160;    <span class="comment"># Get parameters of the face where sketch of rebar is drawn</span></div><div class="line"><a name="l00284"></a><span class="lineno">  284</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename)</div><div class="line"><a name="l00285"></a><span class="lineno">  285</span>&#160;    <span class="comment"># Get points of L-Shape rebar</span></div><div class="line"><a name="l00286"></a><span class="lineno">  286</span>&#160;    points = <a class="code" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">getpointsOfBentShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</div><div class="line"><a name="l00287"></a><span class="lineno">  287</span>&#160;    sketch.movePoint(0, 1, points[0], 0)</div><div class="line"><a name="l00288"></a><span class="lineno">  288</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00289"></a><span class="lineno">  289</span>&#160;    sketch.movePoint(0, 2, points[1], 0)</div><div class="line"><a name="l00290"></a><span class="lineno">  290</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00291"></a><span class="lineno">  291</span>&#160;    sketch.movePoint(1, 1, points[1], 0)</div><div class="line"><a name="l00292"></a><span class="lineno">  292</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00293"></a><span class="lineno">  293</span>&#160;    sketch.movePoint(1, 2, points[2], 0)</div><div class="line"><a name="l00294"></a><span class="lineno">  294</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00295"></a><span class="lineno">  295</span>&#160;</div><div class="line"><a name="l00296"></a><span class="lineno">  296</span>&#160;    sketch.movePoint(2, 1, points[2], 0)</div><div class="line"><a name="l00297"></a><span class="lineno">  297</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00298"></a><span class="lineno">  298</span>&#160;    sketch.movePoint(2, 2, points[3], 0)</div><div class="line"><a name="l00299"></a><span class="lineno">  299</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00300"></a><span class="lineno">  300</span>&#160;    sketch.movePoint(3, 1, points[3], 0)</div><div class="line"><a name="l00301"></a><span class="lineno">  301</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00302"></a><span class="lineno">  302</span>&#160;    sketch.movePoint(3, 2, points[4], 0)</div><div class="line"><a name="l00303"></a><span class="lineno">  303</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00304"></a><span class="lineno">  304</span>&#160;</div><div class="line"><a name="l00305"></a><span class="lineno">  305</span>&#160;    sketch.movePoint(4, 1, points[4], 0)</div><div class="line"><a name="l00306"></a><span class="lineno">  306</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00307"></a><span class="lineno">  307</span>&#160;    sketch.movePoint(4, 2, points[5], 0)</div><div class="line"><a name="l00308"></a><span class="lineno">  308</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00309"></a><span class="lineno">  309</span>&#160;</div><div class="line"><a name="l00310"></a><span class="lineno">  310</span>&#160;    Rebar.OffsetStart = f_cover</div><div class="line"><a name="l00311"></a><span class="lineno">  311</span>&#160;    Rebar.OffsetEnd = f_cover</div><div class="line"><a name="l00312"></a><span class="lineno">  312</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00313"></a><span class="lineno">  313</span>&#160;        Rebar.Amount = amount_spacing_value</div><div class="line"><a name="l00314"></a><span class="lineno">  314</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00315"></a><span class="lineno">  315</span>&#160;        Rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00316"></a><span class="lineno">  316</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00317"></a><span class="lineno">  317</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00318"></a><span class="lineno">  318</span>&#160;        Rebar.Amount = int((size - diameter) / amount_spacing_value)</div><div class="line"><a name="l00319"></a><span class="lineno">  319</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00320"></a><span class="lineno">  320</span>&#160;        Rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00321"></a><span class="lineno">  321</span>&#160;    Rebar.Diameter = diameter</div><div class="line"><a name="l00322"></a><span class="lineno">  322</span>&#160;    Rebar.FrontCover = f_cover</div><div class="line"><a name="l00323"></a><span class="lineno">  323</span>&#160;    Rebar.LeftCover = l_cover</div><div class="line"><a name="l00324"></a><span class="lineno">  324</span>&#160;    Rebar.RightCover = r_cover</div><div class="line"><a name="l00325"></a><span class="lineno">  325</span>&#160;    Rebar.BottomCover = b_cover</div><div class="line"><a name="l00326"></a><span class="lineno">  326</span>&#160;    Rebar.TopCover = t_cover</div><div class="line"><a name="l00327"></a><span class="lineno">  327</span>&#160;    Rebar.BentLength = bentLength</div><div class="line"><a name="l00328"></a><span class="lineno">  328</span>&#160;    Rebar.BentAngle = bentAngle</div><div class="line"><a name="l00329"></a><span class="lineno">  329</span>&#160;    Rebar.Rounding = rounding</div><div class="line"><a name="l00330"></a><span class="lineno">  330</span>&#160;    Rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00331"></a><span class="lineno">  331</span>&#160;    Rebar.Orientation = orientation</div><div class="line"><a name="l00332"></a><span class="lineno">  332</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00333"></a><span class="lineno">  333</span>&#160;    <span class="keywordflow">return</span> Rebar</div><div class="line"><a name="l00334"></a><span class="lineno">  334</span>&#160;</div><div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_a33951a8ab21a73bae42af9f81d7c43c3"><div class="ttname"><a href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">BentShapeRebar.getpointsOfBentShapeRebar</a></div><div class="ttdeci">def getpointsOfBentShapeRebar(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00040">BentShapeRebar.py:40</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_a941d005845cd497c0beb12bb8fef9171"><div class="ttname"><a href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171">BentShapeRebar.editBentShapeRebar</a></div><div class="ttdeci">def editBentShapeRebar(Rebar, f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00270">BentShapeRebar.py:270</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a2278a0602d46a62953af1fcf2e574a94"><div class="ttname"><a href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">Rebarfunc.showWarning</a></div><div class="ttdeci">def showWarning(message)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00293">Rebarfunc.py:293</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171_cgraph.png" border="0" usemap="#namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171_cgraph" alt=""/></div>
<map name="namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171_cgraph" id="namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="289,5,454,32"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="527,81,705,108"/>
<area shape="rect" id="node5" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="264,107,479,133"/>
<area shape="rect" id="node6" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3" title="BentShapeRebar.getpoints\lOfBentShapeRebar" alt="" coords="282,158,461,199"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="548,5,684,32"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171_icgraph.png" border="0" usemap="#namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171_icgraph" alt=""/></div>
<map name="namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171_icgraph" id="namespaceBentShapeRebar_a941d005845cd497c0beb12bb8fef9171_icgraph">
<area shape="rect" id="node2" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918" title="BentShapeRebar._BentShape\lRebarTaskPanel.accept" alt="" coords="264,201,460,243"/>
<area shape="rect" id="node3" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906" title="BentShapeRebar._BentShape\lRebarTaskPanel.clicked" alt="" coords="518,5,714,47"/>
<area shape="rect" id="node4" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce" title="HelicalRebar._HelicalRebar\lTaskPanel.clicked" alt="" coords="525,71,707,112"/>
<area shape="rect" id="node5" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="521,136,711,177"/>
<area shape="rect" id="node6" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="508,201,724,243"/>
<area shape="rect" id="node7" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="508,267,724,294"/>
<area shape="rect" id="node8" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="519,319,713,360"/>
<area shape="rect" id="node9" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="517,384,715,425"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ae5db82a49148a0a8f6fa567fa72d93b2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar.editDialog </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>vobj</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00335">335</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00335"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#ae5db82a49148a0a8f6fa567fa72d93b2">  335</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#ae5db82a49148a0a8f6fa567fa72d93b2">editDialog</a>(vobj):</div><div class="line"><a name="l00336"></a><span class="lineno">  336</span>&#160;    FreeCADGui.Control.closeDialog()</div><div class="line"><a name="l00337"></a><span class="lineno">  337</span>&#160;    obj = <a class="code" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">_BentShapeRebarTaskPanel</a>(vobj.Object)</div><div class="line"><a name="l00338"></a><span class="lineno">  338</span>&#160;    obj.form.frontCover.setText(str(vobj.Object.FrontCover))</div><div class="line"><a name="l00339"></a><span class="lineno">  339</span>&#160;    obj.form.l_sideCover.setText(str(vobj.Object.LeftCover))</div><div class="line"><a name="l00340"></a><span class="lineno">  340</span>&#160;    obj.form.r_sideCover.setText(str(vobj.Object.RightCover))</div><div class="line"><a name="l00341"></a><span class="lineno">  341</span>&#160;    obj.form.bottomCover.setText(str(vobj.Object.BottomCover))</div><div class="line"><a name="l00342"></a><span class="lineno">  342</span>&#160;    obj.form.diameter.setText(str(vobj.Object.Diameter))</div><div class="line"><a name="l00343"></a><span class="lineno">  343</span>&#160;    obj.form.topCover.setText(str(vobj.Object.TopCover))</div><div class="line"><a name="l00344"></a><span class="lineno">  344</span>&#160;    obj.form.bentLength.setText(str(vobj.Object.BentLength))</div><div class="line"><a name="l00345"></a><span class="lineno">  345</span>&#160;    obj.form.bentAngle.setValue(vobj.Object.BentAngle)</div><div class="line"><a name="l00346"></a><span class="lineno">  346</span>&#160;    obj.form.rounding.setValue(vobj.Object.Rounding)</div><div class="line"><a name="l00347"></a><span class="lineno">  347</span>&#160;    obj.form.orientation.setCurrentIndex(obj.form.orientation.findText(str(vobj.Object.Orientation)))</div><div class="line"><a name="l00348"></a><span class="lineno">  348</span>&#160;    <span class="keywordflow">if</span> vobj.Object.AmountCheck:</div><div class="line"><a name="l00349"></a><span class="lineno">  349</span>&#160;        obj.form.amount.setValue(vobj.Object.Amount)</div><div class="line"><a name="l00350"></a><span class="lineno">  350</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00351"></a><span class="lineno">  351</span>&#160;        obj.form.amount_radio.setChecked(<span class="keyword">False</span>)</div><div class="line"><a name="l00352"></a><span class="lineno">  352</span>&#160;        obj.form.spacing_radio.setChecked(<span class="keyword">True</span>)</div><div class="line"><a name="l00353"></a><span class="lineno">  353</span>&#160;        obj.form.amount.setDisabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00354"></a><span class="lineno">  354</span>&#160;        obj.form.spacing.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00355"></a><span class="lineno">  355</span>&#160;        obj.form.spacing.setText(str(vobj.Object.TrueSpacing))</div><div class="line"><a name="l00356"></a><span class="lineno">  356</span>&#160;    <span class="comment">#obj.form.PickSelectedFace.setVisible(False)</span></div><div class="line"><a name="l00357"></a><span class="lineno">  357</span>&#160;    FreeCADGui.Control.showDialog(obj)</div><div class="line"><a name="l00358"></a><span class="lineno">  358</span>&#160;</div><div class="ttc" id="classBentShapeRebar_1_1__BentShapeRebarTaskPanel_html"><div class="ttname"><a href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html">BentShapeRebar._BentShapeRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00105">BentShapeRebar.py:105</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_ae5db82a49148a0a8f6fa567fa72d93b2"><div class="ttname"><a href="namespaceBentShapeRebar.html#ae5db82a49148a0a8f6fa567fa72d93b2">BentShapeRebar.editDialog</a></div><div class="ttdeci">def editDialog(vobj)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00335">BentShapeRebar.py:335</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="a33951a8ab21a73bae42af9f81d7c43c3"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar.getpointsOfBentShapeRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>FacePRM</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentLength</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentAngle</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">getpointsOfBentShapeRebar(FacePRM, LeftCover, RightCover, BottomCover, TopCover, BentLength, BentAngle, Orientation):
Return points of the LShape rebar in the form of array for sketch.
It takes four different orientations input i.e. 'Bottom', 'Top', 'Left', 'Right'.
</pre> 
<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00040">40</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">   40</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">getpointsOfBentShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation):</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; getpointsOfBentShapeRebar(FacePRM, LeftCover, RightCover, BottomCover, TopCover, BentLength, BentAngle, Orientation):</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="stringliteral">    Return points of the LShape rebar in the form of array for sketch.</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;<span class="stringliteral">    It takes four different orientations input i.e. &#39;Bottom&#39;, &#39;Top&#39;, &#39;Left&#39;, &#39;Right&#39;.</span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    <span class="keywordflow">if</span> orientation == <span class="stringliteral">&quot;Bottom&quot;</span>:</div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        x2 = x1 + bentLength</div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        y2 = y1</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        dis = (FacePRM[0][1] - t_cover - b_cover) * math.tan(math.radians(bentAngle - 90))</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;        x3 = x2 + dis</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;        y3 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;        x4 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover - bentLength - dis</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;        y4 = y3</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;        x5 = x4 + dis</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        y5 = y2</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;        x6 = x5 + bentLength</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;        y6 = y5</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Top&quot;</span>:</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;        y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;        x2 = x1 + bentLength</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;        y2 = y1</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;        dis = (FacePRM[0][1] - t_cover - b_cover) * math.tan(math.radians(bentAngle - 90))</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;        x3 = x2 + dis</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;        y3 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        x4 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover - bentLength - dis</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;        y4 = y3</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;        x5 = x4 + dis</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;        y5 = y2</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        x6 = x5 + bentLength</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;        y6 = y5</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Left&quot;</span>:</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;        x1 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;        x2 = x1</div><div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;        y2 = y1 - bentLength</div><div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;        dis = (FacePRM[0][0] - r_cover - l_cover) * math.tan(math.radians(bentAngle - 90))</div><div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;        x3 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;        y3 = y2 - dis</div><div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;        x4 = x3</div><div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;        y4 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover + bentLength + dis</div><div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;        x5 = x2</div><div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        y5 = y4 - dis</div><div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;        x6 = x5</div><div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;        y6 = y5 - bentLength</div><div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Right&quot;</span>:</div><div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;        x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + l_cover</div><div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;        y1 = FacePRM[1][1] + FacePRM[0][1] / 2 - t_cover</div><div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;        x2 = x1</div><div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;        y2 = y1 - bentLength</div><div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;        dis = (FacePRM[0][0] - r_cover - l_cover) * math.tan(math.radians(bentAngle - 90))</div><div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;        x3 = FacePRM[1][0] + FacePRM[0][0] / 2 - r_cover</div><div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;        y3 = y2 - dis</div><div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;        x4 = x3</div><div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;        y4 = FacePRM[1][1] - FacePRM[0][1] / 2 + b_cover + bentLength + dis</div><div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;        x5 = x2</div><div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;        y5 = y4 - dis</div><div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;        x6 = x5</div><div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;        y6 = y5 - bentLength</div><div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;    <span class="keywordflow">return</span> [FreeCAD.Vector(x1, y1, 0), FreeCAD.Vector(x2, y2, 0),\</div><div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;           FreeCAD.Vector(x3, y3, 0), FreeCAD.Vector(x4, y4, 0),\</div><div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;           FreeCAD.Vector(x5, y5, 0), FreeCAD.Vector(x6, y6, 0)]</div><div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;</div><div class="ttc" id="namespaceBentShapeRebar_html_a33951a8ab21a73bae42af9f81d7c43c3"><div class="ttname"><a href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">BentShapeRebar.getpointsOfBentShapeRebar</a></div><div class="ttdeci">def getpointsOfBentShapeRebar(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00040">BentShapeRebar.py:40</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceBentShapeRebar_a33951a8ab21a73bae42af9f81d7c43c3_icgraph.png" border="0" usemap="#namespaceBentShapeRebar_a33951a8ab21a73bae42af9f81d7c43c3_icgraph" alt=""/></div>
<map name="namespaceBentShapeRebar_a33951a8ab21a73bae42af9f81d7c43c3_icgraph" id="namespaceBentShapeRebar_a33951a8ab21a73bae42af9f81d7c43c3_icgraph">
<area shape="rect" id="node2" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476" title="BentShapeRebar.makeBentShape\lRebar" alt="" coords="232,168,453,209"/>
<area shape="rect" id="node11" href="namespaceBentShapeRebar.html#a941d005845cd497c0beb12bb8fef9171" title="BentShapeRebar.editBentShape\lRebar" alt="" coords="237,233,448,275"/>
<area shape="rect" id="node3" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918" title="BentShapeRebar._BentShape\lRebarTaskPanel.accept" alt="" coords="501,201,697,243"/>
<area shape="rect" id="node4" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906" title="BentShapeRebar._BentShape\lRebarTaskPanel.clicked" alt="" coords="755,5,951,47"/>
<area shape="rect" id="node5" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce" title="HelicalRebar._HelicalRebar\lTaskPanel.clicked" alt="" coords="762,71,945,112"/>
<area shape="rect" id="node6" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="758,136,949,177"/>
<area shape="rect" id="node7" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="745,201,961,243"/>
<area shape="rect" id="node8" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="745,267,961,294"/>
<area shape="rect" id="node9" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="757,319,950,360"/>
<area shape="rect" id="node10" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="755,384,952,425"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="aac46779d3e1905db5a3788917f6e2476"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def BentShapeRebar.makeBentShapeRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>f_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>b_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>l_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>r_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>t_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentLength</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>bentAngle</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rounding</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_check</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_value</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em> = <code>&quot;Bottom&#160;Left&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">makeBentShapeRebar(FrontCover, BottomCover, LeftCover, RightCover, Diameter, TopCover, BentLength, BentAngle, Rounding,
AmountSpacingCheck, AmountSpacingValue, Orientation, Structure, Facename): Adds the Bent-Shape reinforcement bar to the
selected structural object.
It takes four different orientations input i.e. 'Bottom', 'Top', 'Left', 'Right'.
</pre> 
<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00200">200</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00200"></a><span class="lineno"><a class="line" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">  200</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">makeBentShapeRebar</a>(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation = &quot;Bottom Left&quot;, structure = None, facename = None):</div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; makeBentShapeRebar(FrontCover, BottomCover, LeftCover, RightCover, Diameter, TopCover, BentLength, BentAngle, Rounding,</span></div><div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;<span class="stringliteral">    AmountSpacingCheck, AmountSpacingValue, Orientation, Structure, Facename): Adds the Bent-Shape reinforcement bar to the</span></div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;<span class="stringliteral">    selected structural object.</span></div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;<span class="stringliteral">    It takes four different orientations input i.e. &#39;Bottom&#39;, &#39;Top&#39;, &#39;Left&#39;, &#39;Right&#39;.</span></div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> structure <span class="keywordflow">and</span> <span class="keywordflow">not</span> facename:</div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;        selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;        structure = selected_obj.Object</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;        facename = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename)</div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> FacePRM:</div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;        FreeCAD.Console.PrintError(<span class="stringliteral">&quot;Cannot identified shape or from which base object sturctural element is derived\n&quot;</span>)</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;    <span class="comment"># Get points of L-Shape rebar</span></div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    points = <a class="code" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">getpointsOfBentShapeRebar</a>(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    <span class="keyword">import</span> Part</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    <span class="keyword">import</span> Arch</div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    sketch = FreeCAD.activeDocument().addObject(<span class="stringliteral">&#39;Sketcher::SketchObject&#39;</span>, <span class="stringliteral">&#39;Sketch&#39;</span>)</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    sketch.MapMode = <span class="stringliteral">&quot;FlatFace&quot;</span></div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;    sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    sketch.addGeometry(Part.LineSegment(points[0], points[1]), <span class="keyword">False</span>)</div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;    sketch.addGeometry(Part.LineSegment(points[1], points[2]), <span class="keyword">False</span>)</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;    sketch.addGeometry(Part.LineSegment(points[2], points[3]), <span class="keyword">False</span>)</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;    sketch.addGeometry(Part.LineSegment(points[3], points[4]), <span class="keyword">False</span>)</div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;    sketch.addGeometry(Part.LineSegment(points[4], points[5]), <span class="keyword">False</span>)</div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;    <span class="keyword">import</span> Sketcher</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;        rebar = Arch.makeRebar(structure, sketch, diameter, amount_spacing_value, f_cover)</div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;        rebar = Arch.makeRebar(structure, sketch, diameter, int((size - diameter) / amount_spacing_value), f_cover)</div><div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;    rebar.Rounding = rounding</div><div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;    <span class="comment"># Adds properties to the rebar object</span></div><div class="line"><a name="l00238"></a><span class="lineno">  238</span>&#160;    rebar.ViewObject.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;RebarShape&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).RebarShape = <span class="stringliteral">&quot;BentShapeRebar&quot;</span></div><div class="line"><a name="l00239"></a><span class="lineno">  239</span>&#160;    rebar.ViewObject.setEditorMode(<span class="stringliteral">&quot;RebarShape&quot;</span>, 2)</div><div class="line"><a name="l00240"></a><span class="lineno">  240</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;FrontCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Front cover of rebar&quot;</span>)).FrontCover = f_cover</div><div class="line"><a name="l00241"></a><span class="lineno">  241</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;FrontCover&quot;</span>, 2)</div><div class="line"><a name="l00242"></a><span class="lineno">  242</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;LeftCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Left Side cover of rebar&quot;</span>)).LeftCover = l_cover</div><div class="line"><a name="l00243"></a><span class="lineno">  243</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;LeftCover&quot;</span>, 2)</div><div class="line"><a name="l00244"></a><span class="lineno">  244</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;RightCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Right Side cover of rebar&quot;</span>)).RightCover = r_cover</div><div class="line"><a name="l00245"></a><span class="lineno">  245</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;RightCover&quot;</span>, 2)</div><div class="line"><a name="l00246"></a><span class="lineno">  246</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BottomCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bottom cover of rebar&quot;</span>)).BottomCover = b_cover</div><div class="line"><a name="l00247"></a><span class="lineno">  247</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BottomCover&quot;</span>, 2)</div><div class="line"><a name="l00248"></a><span class="lineno">  248</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyBool&quot;</span>, <span class="stringliteral">&quot;AmountCheck&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Amount radio button is checked&quot;</span>)).AmountCheck</div><div class="line"><a name="l00249"></a><span class="lineno">  249</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;AmountCheck&quot;</span>, 2)</div><div class="line"><a name="l00250"></a><span class="lineno">  250</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TopCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Top cover of rebar&quot;</span>)).TopCover = t_cover</div><div class="line"><a name="l00251"></a><span class="lineno">  251</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TopCover&quot;</span>, 2)</div><div class="line"><a name="l00252"></a><span class="lineno">  252</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TrueSpacing&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Spacing between of rebars&quot;</span>)).TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00253"></a><span class="lineno">  253</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;Orientation&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).Orientation = orientation</div><div class="line"><a name="l00254"></a><span class="lineno">  254</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;Orientation&quot;</span>, 2)</div><div class="line"><a name="l00255"></a><span class="lineno">  255</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TrueSpacing&quot;</span>, 2)</div><div class="line"><a name="l00256"></a><span class="lineno">  256</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BentLength&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;BentLength cover of rebar&quot;</span>)).BentLength = bentLength</div><div class="line"><a name="l00257"></a><span class="lineno">  257</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BentLength&quot;</span>, 2)</div><div class="line"><a name="l00258"></a><span class="lineno">  258</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;BentAngle&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Bent Angle of rebar&quot;</span>)).BentAngle = bentAngle</div><div class="line"><a name="l00259"></a><span class="lineno">  259</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;BentAngle&quot;</span>, 2)</div><div class="line"><a name="l00260"></a><span class="lineno">  260</span>&#160;</div><div class="line"><a name="l00261"></a><span class="lineno">  261</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00262"></a><span class="lineno">  262</span>&#160;        rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00263"></a><span class="lineno">  263</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00264"></a><span class="lineno">  264</span>&#160;        rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00265"></a><span class="lineno">  265</span>&#160;        rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00266"></a><span class="lineno">  266</span>&#160;    rebar.Label = <span class="stringliteral">&quot;BentShapeRebar&quot;</span></div><div class="line"><a name="l00267"></a><span class="lineno">  267</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00268"></a><span class="lineno">  268</span>&#160;    <span class="keywordflow">return</span> rebar</div><div class="line"><a name="l00269"></a><span class="lineno">  269</span>&#160;</div><div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_a33951a8ab21a73bae42af9f81d7c43c3"><div class="ttname"><a href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3">BentShapeRebar.getpointsOfBentShapeRebar</a></div><div class="ttdeci">def getpointsOfBentShapeRebar(FacePRM, l_cover, r_cover, b_cover, t_cover, bentLength, bentAngle, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00040">BentShapeRebar.py:40</a></div></div>
<div class="ttc" id="namespaceBentShapeRebar_html_aac46779d3e1905db5a3788917f6e2476"><div class="ttname"><a href="namespaceBentShapeRebar.html#aac46779d3e1905db5a3788917f6e2476">BentShapeRebar.makeBentShapeRebar</a></div><div class="ttdeci">def makeBentShapeRebar(f_cover, b_cover, l_cover, r_cover, diameter, t_cover, bentLength, bentAngle, rounding, amount_spacing_check, amount_spacing_value, orientation=&quot;Bottom Left&quot;, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="BentShapeRebar_8py_source.html#l00200">BentShapeRebar.py:200</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476_cgraph.png" border="0" usemap="#namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476_cgraph" alt=""/></div>
<map name="namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476_cgraph" id="namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="537,5,716,32"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="275,31,489,57"/>
<area shape="rect" id="node4" href="namespaceBentShapeRebar.html#a33951a8ab21a73bae42af9f81d7c43c3" title="BentShapeRebar.getpoints\lOfBentShapeRebar" alt="" coords="293,82,471,123"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476_icgraph.png" border="0" usemap="#namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476_icgraph" alt=""/></div>
<map name="namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476_icgraph" id="namespaceBentShapeRebar_aac46779d3e1905db5a3788917f6e2476_icgraph">
<area shape="rect" id="node2" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#afdcf71c6a16711a535971366558ea918" title="BentShapeRebar._BentShape\lRebarTaskPanel.accept" alt="" coords="275,201,471,243"/>
<area shape="rect" id="node3" href="classBentShapeRebar_1_1__BentShapeRebarTaskPanel.html#ae92dd6ab03c4b967b064fac00fa0d906" title="BentShapeRebar._BentShape\lRebarTaskPanel.clicked" alt="" coords="529,5,725,47"/>
<area shape="rect" id="node4" href="classHelicalRebar_1_1__HelicalRebarTaskPanel.html#ab0b70379d225d10e3585478005fc53ce" title="HelicalRebar._HelicalRebar\lTaskPanel.clicked" alt="" coords="535,71,718,112"/>
<area shape="rect" id="node5" href="classLShapeRebar_1_1__LShapeRebarTaskPanel.html#ac477e2a29da1e0ac71bf2d3aa1e50c4f" title="LShapeRebar._LShapeRebar\lTaskPanel.clicked" alt="" coords="531,136,722,177"/>
<area shape="rect" id="node6" href="classRebarDistribution_1_1__RebarDistributionDialog.html#aa96660ccded2b2b91a36a8099199842d" title="RebarDistribution.\l_RebarDistributionDialog.setupUi" alt="" coords="519,201,735,243"/>
<area shape="rect" id="node7" href="classStirrup_1_1__StirrupTaskPanel.html#aa1caeff48053cc3a43ed215e5c5c01c8" title="Stirrup._StirrupTaskPanel.clicked" alt="" coords="519,267,735,294"/>
<area shape="rect" id="node8" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="530,319,723,360"/>
<area shape="rect" id="node9" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="528,384,725,425"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="ad79a2dbf88601c24aae561033cb48d34"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string BentShapeRebar.__author__ = &quot;Amritpal Singh&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00025">25</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="a38b223debc1826fd2855773a02749bb4"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string BentShapeRebar.__title__ = &quot;BentShapeRebar&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00024">24</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="aec768ca6a259d1cc738ea11c79a124e2"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string BentShapeRebar.__url__ = &quot;https://www.freecadweb.org&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="BentShapeRebar_8py_source.html#l00026">26</a> of file <a class="el" href="BentShapeRebar_8py_source.html">BentShapeRebar.py</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Wed Dec 13 2017 22:36:42 for Rebar Addon for FreeCAD by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.11
</small></address>
</body>
</html>
