<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.11"/>
<title>Rebar Addon for FreeCAD: StraightRebar Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Rebar Addon for FreeCAD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="namespaces.html"><span>Namespace&#160;List</span></a></li>
      <li><a href="namespacemembers.html"><span>Namespace&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">StraightRebar Namespace Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classStraightRebar_1_1__StraightRebarTaskPanel.html">_StraightRebarTaskPanel</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a1873c6f7f59b355a64fdd966ad75f778"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778">getpointsOfStraightRebar</a> (FacePRM, rt_cover, lb_cover, coverAlong, orientation)</td></tr>
<tr class="separator:a1873c6f7f59b355a64fdd966ad75f778"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af6270367d7beae457813e33718d80faf"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStraightRebar.html#af6270367d7beae457813e33718d80faf">makeStraightRebar</a> (f_cover, coverAlong, rt_cover, lb_cover, diameter, amount_spacing_check, amount_spacing_value, orientation=&quot;Horizontal&quot;, structure=None, facename=None)</td></tr>
<tr class="separator:af6270367d7beae457813e33718d80faf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab4c578165b01dd7c7d121e5345de2d7b"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStraightRebar.html#ab4c578165b01dd7c7d121e5345de2d7b">editStraightRebar</a> (Rebar, f_cover, coverAlong, rt_cover, lb_cover, diameter, amount_spacing_check, amount_spacing_value, orientation, structure=None, facename=None)</td></tr>
<tr class="separator:ab4c578165b01dd7c7d121e5345de2d7b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad48f93922ce90bb63d051c7c3c794d35"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStraightRebar.html#ad48f93922ce90bb63d051c7c3c794d35">editDialog</a> (vobj)</td></tr>
<tr class="separator:ad48f93922ce90bb63d051c7c3c794d35"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30f7aada2e2f91cdfae8267da36fe277"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStraightRebar.html#a30f7aada2e2f91cdfae8267da36fe277">CommandStraightRebar</a> ()</td></tr>
<tr class="separator:a30f7aada2e2f91cdfae8267da36fe277"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:ab1d45eb17133c23d9d6a3e2a6f2abb8a"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStraightRebar.html#ab1d45eb17133c23d9d6a3e2a6f2abb8a">__title__</a> = &quot;StraightRebar&quot;</td></tr>
<tr class="separator:ab1d45eb17133c23d9d6a3e2a6f2abb8a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad355d40e3bea5e86c24b6fe813264413"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStraightRebar.html#ad355d40e3bea5e86c24b6fe813264413">__author__</a> = &quot;Amritpal Singh&quot;</td></tr>
<tr class="separator:ad355d40e3bea5e86c24b6fe813264413"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aebf23f453d8fabed3a611d14f5e7f057"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceStraightRebar.html#aebf23f453d8fabed3a611d14f5e7f057">__url__</a> = &quot;https://www.freecadweb.org&quot;</td></tr>
<tr class="separator:aebf23f453d8fabed3a611d14f5e7f057"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a class="anchor" id="a30f7aada2e2f91cdfae8267da36fe277"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def StraightRebar.CommandStraightRebar </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="StraightRebar_8py_source.html#l00320">320</a> of file <a class="el" href="StraightRebar_8py_source.html">StraightRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00320"></a><span class="lineno"><a class="line" href="namespaceStraightRebar.html#a30f7aada2e2f91cdfae8267da36fe277">  320</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceStraightRebar.html#a30f7aada2e2f91cdfae8267da36fe277">CommandStraightRebar</a>():</div><div class="line"><a name="l00321"></a><span class="lineno">  321</span>&#160;    selected_obj = <a class="code" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">check_selected_face</a>()</div><div class="line"><a name="l00322"></a><span class="lineno">  322</span>&#160;    <span class="keywordflow">if</span> selected_obj:</div><div class="line"><a name="l00323"></a><span class="lineno">  323</span>&#160;        FreeCADGui.Control.showDialog(<a class="code" href="classStraightRebar_1_1__StraightRebarTaskPanel.html">_StraightRebarTaskPanel</a>())</div><div class="line"><a name="l00324"></a><span class="lineno">  324</span>&#160;<div class="ttc" id="namespaceRebarfunc_html_adae2713855a7e1b4bda04081ae671542"><div class="ttname"><a href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542">Rebarfunc.check_selected_face</a></div><div class="ttdeci">def check_selected_face()</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00255">Rebarfunc.py:255</a></div></div>
<div class="ttc" id="classStraightRebar_1_1__StraightRebarTaskPanel_html"><div class="ttname"><a href="classStraightRebar_1_1__StraightRebarTaskPanel.html">StraightRebar._StraightRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00075">StraightRebar.py:75</a></div></div>
<div class="ttc" id="namespaceStraightRebar_html_a30f7aada2e2f91cdfae8267da36fe277"><div class="ttname"><a href="namespaceStraightRebar.html#a30f7aada2e2f91cdfae8267da36fe277">StraightRebar.CommandStraightRebar</a></div><div class="ttdeci">def CommandStraightRebar()</div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00320">StraightRebar.py:320</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277_cgraph.png" border="0" usemap="#namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277_cgraph" alt=""/></div>
<map name="namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277_cgraph" id="namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#adae2713855a7e1b4bda04081ae671542" title="Rebarfunc.check_selected_face" alt="" coords="264,13,473,39"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="521,13,687,39"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="735,13,871,39"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277_icgraph.png" border="0" usemap="#namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277_icgraph" alt=""/></div>
<map name="namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277_icgraph" id="namespaceStraightRebar_a30f7aada2e2f91cdfae8267da36fe277_icgraph">
<area shape="rect" id="node2" href="classRebarTools_1_1StraightRebarTool.html#aa297d606f70c0474a1014b5b8ea241bf" title="RebarTools.StraightRebar\lTool.Activated" alt="" coords="264,5,437,47"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="ad48f93922ce90bb63d051c7c3c794d35"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def StraightRebar.editDialog </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>vobj</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="StraightRebar_8py_source.html#l00299">299</a> of file <a class="el" href="StraightRebar_8py_source.html">StraightRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00299"></a><span class="lineno"><a class="line" href="namespaceStraightRebar.html#ad48f93922ce90bb63d051c7c3c794d35">  299</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceStraightRebar.html#ad48f93922ce90bb63d051c7c3c794d35">editDialog</a>(vobj):</div><div class="line"><a name="l00300"></a><span class="lineno">  300</span>&#160;    FreeCADGui.Control.closeDialog()</div><div class="line"><a name="l00301"></a><span class="lineno">  301</span>&#160;    obj = <a class="code" href="classStraightRebar_1_1__StraightRebarTaskPanel.html">_StraightRebarTaskPanel</a>(vobj.Object)</div><div class="line"><a name="l00302"></a><span class="lineno">  302</span>&#160;    obj.form.frontCover.setText(str(vobj.Object.FrontCover))</div><div class="line"><a name="l00303"></a><span class="lineno">  303</span>&#160;    obj.form.r_sideCover.setText(str(vobj.Object.RightTopCover))</div><div class="line"><a name="l00304"></a><span class="lineno">  304</span>&#160;    obj.form.l_sideCover.setText(str(vobj.Object.LeftBottomCover))</div><div class="line"><a name="l00305"></a><span class="lineno">  305</span>&#160;    obj.form.bottomCover.setText(str(vobj.Object.Cover))</div><div class="line"><a name="l00306"></a><span class="lineno">  306</span>&#160;    obj.form.diameter.setText(str(vobj.Object.Diameter))</div><div class="line"><a name="l00307"></a><span class="lineno">  307</span>&#160;    obj.form.orientation.setCurrentIndex(obj.form.orientation.findText(str(vobj.Object.Orientation)))</div><div class="line"><a name="l00308"></a><span class="lineno">  308</span>&#160;    obj.form.coverAlong.setCurrentIndex(obj.form.coverAlong.findText(str(vobj.Object.CoverAlong)))</div><div class="line"><a name="l00309"></a><span class="lineno">  309</span>&#160;    <span class="keywordflow">if</span> vobj.Object.AmountCheck:</div><div class="line"><a name="l00310"></a><span class="lineno">  310</span>&#160;        obj.form.amount.setValue(vobj.Object.Amount)</div><div class="line"><a name="l00311"></a><span class="lineno">  311</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00312"></a><span class="lineno">  312</span>&#160;        obj.form.amount_radio.setChecked(<span class="keyword">False</span>)</div><div class="line"><a name="l00313"></a><span class="lineno">  313</span>&#160;        obj.form.spacing_radio.setChecked(<span class="keyword">True</span>)</div><div class="line"><a name="l00314"></a><span class="lineno">  314</span>&#160;        obj.form.amount.setDisabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00315"></a><span class="lineno">  315</span>&#160;        obj.form.spacing.setEnabled(<span class="keyword">True</span>)</div><div class="line"><a name="l00316"></a><span class="lineno">  316</span>&#160;        obj.form.spacing.setText(str(vobj.Object.TrueSpacing))</div><div class="line"><a name="l00317"></a><span class="lineno">  317</span>&#160;    <span class="comment">#obj.form.PickSelectedFace.setVisible(False)</span></div><div class="line"><a name="l00318"></a><span class="lineno">  318</span>&#160;    FreeCADGui.Control.showDialog(obj)</div><div class="line"><a name="l00319"></a><span class="lineno">  319</span>&#160;</div><div class="ttc" id="classStraightRebar_1_1__StraightRebarTaskPanel_html"><div class="ttname"><a href="classStraightRebar_1_1__StraightRebarTaskPanel.html">StraightRebar._StraightRebarTaskPanel</a></div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00075">StraightRebar.py:75</a></div></div>
<div class="ttc" id="namespaceStraightRebar_html_ad48f93922ce90bb63d051c7c3c794d35"><div class="ttname"><a href="namespaceStraightRebar.html#ad48f93922ce90bb63d051c7c3c794d35">StraightRebar.editDialog</a></div><div class="ttdeci">def editDialog(vobj)</div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00299">StraightRebar.py:299</a></div></div>
</div><!-- fragment -->
</div>
</div>
<a class="anchor" id="ab4c578165b01dd7c7d121e5345de2d7b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def StraightRebar.editStraightRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>Rebar</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>f_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>coverAlong</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rt_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>lb_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_check</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_value</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="StraightRebar_8py_source.html#l00255">255</a> of file <a class="el" href="StraightRebar_8py_source.html">StraightRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00255"></a><span class="lineno"><a class="line" href="namespaceStraightRebar.html#ab4c578165b01dd7c7d121e5345de2d7b">  255</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceStraightRebar.html#ab4c578165b01dd7c7d121e5345de2d7b">editStraightRebar</a>(Rebar, f_cover, coverAlong, rt_cover, lb_cover, diameter, amount_spacing_check, amount_spacing_value, orientation, structure = None, facename = None):</div><div class="line"><a name="l00256"></a><span class="lineno">  256</span>&#160;    sketch = Rebar.Base</div><div class="line"><a name="l00257"></a><span class="lineno">  257</span>&#160;    <span class="keywordflow">if</span> structure <span class="keywordflow">and</span> facename:</div><div class="line"><a name="l00258"></a><span class="lineno">  258</span>&#160;        sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00259"></a><span class="lineno">  259</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00260"></a><span class="lineno">  260</span>&#160;    <span class="comment"># Check if sketch support is empty.</span></div><div class="line"><a name="l00261"></a><span class="lineno">  261</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> sketch.Support:</div><div class="line"><a name="l00262"></a><span class="lineno">  262</span>&#160;        <a class="code" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">showWarning</a>(<span class="stringliteral">&quot;You have checked remove external geometry of base sketchs when needed.\nTo unchecked Edit-&gt;Preferences-&gt;Arch.&quot;</span>)</div><div class="line"><a name="l00263"></a><span class="lineno">  263</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00264"></a><span class="lineno">  264</span>&#160;    <span class="comment"># Assigned values</span></div><div class="line"><a name="l00265"></a><span class="lineno">  265</span>&#160;    facename = sketch.Support[0][1][0]</div><div class="line"><a name="l00266"></a><span class="lineno">  266</span>&#160;    structure = sketch.Support[0][0]</div><div class="line"><a name="l00267"></a><span class="lineno">  267</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00268"></a><span class="lineno">  268</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00269"></a><span class="lineno">  269</span>&#160;    <span class="comment"># Get parameters of the face where sketch of rebar is drawn</span></div><div class="line"><a name="l00270"></a><span class="lineno">  270</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename)</div><div class="line"><a name="l00271"></a><span class="lineno">  271</span>&#160;    <span class="comment"># Get points of Striaght rebar</span></div><div class="line"><a name="l00272"></a><span class="lineno">  272</span>&#160;    points = <a class="code" href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778">getpointsOfStraightRebar</a>(FacePRM, rt_cover, lb_cover, coverAlong, orientation)</div><div class="line"><a name="l00273"></a><span class="lineno">  273</span>&#160;    sketch.movePoint(0, 1, points[0], 0)</div><div class="line"><a name="l00274"></a><span class="lineno">  274</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00275"></a><span class="lineno">  275</span>&#160;    sketch.movePoint(0, 2, points[1], 0)</div><div class="line"><a name="l00276"></a><span class="lineno">  276</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00277"></a><span class="lineno">  277</span>&#160;    Rebar.OffsetStart = f_cover</div><div class="line"><a name="l00278"></a><span class="lineno">  278</span>&#160;    Rebar.OffsetEnd = f_cover</div><div class="line"><a name="l00279"></a><span class="lineno">  279</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00280"></a><span class="lineno">  280</span>&#160;        Rebar.Amount = amount_spacing_value</div><div class="line"><a name="l00281"></a><span class="lineno">  281</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00282"></a><span class="lineno">  282</span>&#160;        Rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00283"></a><span class="lineno">  283</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00284"></a><span class="lineno">  284</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00285"></a><span class="lineno">  285</span>&#160;        Rebar.Amount = int((size - diameter) / amount_spacing_value)</div><div class="line"><a name="l00286"></a><span class="lineno">  286</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00287"></a><span class="lineno">  287</span>&#160;        Rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00288"></a><span class="lineno">  288</span>&#160;    Rebar.FrontCover = f_cover</div><div class="line"><a name="l00289"></a><span class="lineno">  289</span>&#160;    Rebar.RightTopCover = rt_cover</div><div class="line"><a name="l00290"></a><span class="lineno">  290</span>&#160;    Rebar.LeftBottomCover = lb_cover</div><div class="line"><a name="l00291"></a><span class="lineno">  291</span>&#160;    Rebar.CoverAlong = coverAlong[0]</div><div class="line"><a name="l00292"></a><span class="lineno">  292</span>&#160;    Rebar.Cover = coverAlong[1]</div><div class="line"><a name="l00293"></a><span class="lineno">  293</span>&#160;    Rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00294"></a><span class="lineno">  294</span>&#160;    Rebar.Diameter = diameter</div><div class="line"><a name="l00295"></a><span class="lineno">  295</span>&#160;    Rebar.Orientation = orientation</div><div class="line"><a name="l00296"></a><span class="lineno">  296</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00297"></a><span class="lineno">  297</span>&#160;    <span class="keywordflow">return</span> Rebar</div><div class="line"><a name="l00298"></a><span class="lineno">  298</span>&#160;</div><div class="ttc" id="namespaceStraightRebar_html_a1873c6f7f59b355a64fdd966ad75f778"><div class="ttname"><a href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778">StraightRebar.getpointsOfStraightRebar</a></div><div class="ttdeci">def getpointsOfStraightRebar(FacePRM, rt_cover, lb_cover, coverAlong, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00040">StraightRebar.py:40</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a2278a0602d46a62953af1fcf2e574a94"><div class="ttname"><a href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94">Rebarfunc.showWarning</a></div><div class="ttdeci">def showWarning(message)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00293">Rebarfunc.py:293</a></div></div>
<div class="ttc" id="namespaceStraightRebar_html_ab4c578165b01dd7c7d121e5345de2d7b"><div class="ttname"><a href="namespaceStraightRebar.html#ab4c578165b01dd7c7d121e5345de2d7b">StraightRebar.editStraightRebar</a></div><div class="ttdeci">def editStraightRebar(Rebar, f_cover, coverAlong, rt_cover, lb_cover, diameter, amount_spacing_check, amount_spacing_value, orientation, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00255">StraightRebar.py:255</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b_cgraph.png" border="0" usemap="#namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b_cgraph" alt=""/></div>
<map name="namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b_cgraph" id="namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a2278a0602d46a62953af1fcf2e574a94" title="Rebarfunc.showWarning" alt="" coords="250,5,415,32"/>
<area shape="rect" id="node4" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="488,81,667,108"/>
<area shape="rect" id="node5" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="225,107,440,133"/>
<area shape="rect" id="node6" href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778" title="StraightRebar.getpointsOf\lStraightRebar" alt="" coords="246,158,419,199"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a1467a55852e36c36c472e222855bb937" title="Rebarfunc.translate" alt="" coords="509,5,645,32"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b_icgraph.png" border="0" usemap="#namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b_icgraph" alt=""/></div>
<map name="namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b_icgraph" id="namespaceStraightRebar_ab4c578165b01dd7c7d121e5345de2d7b_icgraph">
<area shape="rect" id="node2" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#ad8a49d3d30ef3308b8386c9ebe1b67d8" title="StraightRebar._StraightRebar\lTaskPanel.accept" alt="" coords="225,39,419,80"/>
<area shape="rect" id="node3" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="469,5,662,47"/>
<area shape="rect" id="node4" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="467,71,664,112"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="a1873c6f7f59b355a64fdd966ad75f778"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def StraightRebar.getpointsOfStraightRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>FacePRM</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rt_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>lb_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>coverAlong</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">getpointsOfStraightRebar(FacePRM, RightTopcover, LeftBottomcover, CoverAlong, Orientation):
Return points of the Straight rebar in the form of array for sketch.

Case I: When Orientation is 'Horizontal':
    We have two option in CoverAlong i.e. 'Bottom Side' or 'Top Side'
Case II: When Orientation is 'Vertical':
    We have two option in CoverAlong i.e. 'Left Side' or 'Right Side'
</pre> 
<p>Definition at line <a class="el" href="StraightRebar_8py_source.html#l00040">40</a> of file <a class="el" href="StraightRebar_8py_source.html">StraightRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778">   40</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778">getpointsOfStraightRebar</a>(FacePRM, rt_cover, lb_cover, coverAlong, orientation):</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; getpointsOfStraightRebar(FacePRM, RightTopcover, LeftBottomcover, CoverAlong, Orientation):</span></div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="stringliteral">    Return points of the Straight rebar in the form of array for sketch.</span></div><div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;<span class="stringliteral"></span></div><div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="stringliteral">    Case I: When Orientation is &#39;Horizontal&#39;:</span></div><div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;<span class="stringliteral">        We have two option in CoverAlong i.e. &#39;Bottom Side&#39; or &#39;Top Side&#39;</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="stringliteral">    Case II: When Orientation is &#39;Vertical&#39;:</span></div><div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;<span class="stringliteral">        We have two option in CoverAlong i.e. &#39;Left Side&#39; or &#39;Right Side&#39;</span></div><div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div><div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;    <span class="keywordflow">if</span> orientation == <span class="stringliteral">&quot;Horizontal&quot;</span>:</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        <span class="keywordflow">if</span> coverAlong[0] == <span class="stringliteral">&quot;Bottom Side&quot;</span>:</div><div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;            x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + lb_cover</div><div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;            y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + coverAlong[1]</div><div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;            x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - rt_cover</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;            y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + coverAlong[1]</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;        <span class="keywordflow">elif</span> coverAlong[0] == <span class="stringliteral">&quot;Top Side&quot;</span>:</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;            cover = FacePRM[0][1] - coverAlong[1]</div><div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;            x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + lb_cover</div><div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;            y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + cover</div><div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;            x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + FacePRM[0][0] - rt_cover</div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;            y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + cover</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;    <span class="keywordflow">elif</span> orientation == <span class="stringliteral">&quot;Vertical&quot;</span>:</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;        <span class="keywordflow">if</span> coverAlong[0] == <span class="stringliteral">&quot;Left Side&quot;</span>:</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;            x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + coverAlong[1]</div><div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;            y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + lb_cover</div><div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;            x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + coverAlong[1]</div><div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;            y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + FacePRM[0][1] - rt_cover</div><div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;        <span class="keywordflow">elif</span> coverAlong[0] == <span class="stringliteral">&quot;Right Side&quot;</span>:</div><div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;            cover = FacePRM[0][0] - coverAlong[1]</div><div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;            x1 = FacePRM[1][0] - FacePRM[0][0] / 2 + cover</div><div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;            y1 = FacePRM[1][1] - FacePRM[0][1] / 2 + lb_cover</div><div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;            x2 = FacePRM[1][0] - FacePRM[0][0] / 2 + cover</div><div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;            y2 = FacePRM[1][1] - FacePRM[0][1] / 2 + FacePRM[0][1] - rt_cover</div><div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;    <span class="keywordflow">return</span> [FreeCAD.Vector(x1, y1, 0), FreeCAD.Vector(x2, y2, 0)]</div><div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;</div><div class="ttc" id="namespaceStraightRebar_html_a1873c6f7f59b355a64fdd966ad75f778"><div class="ttname"><a href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778">StraightRebar.getpointsOfStraightRebar</a></div><div class="ttdeci">def getpointsOfStraightRebar(FacePRM, rt_cover, lb_cover, coverAlong, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00040">StraightRebar.py:40</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStraightRebar_a1873c6f7f59b355a64fdd966ad75f778_icgraph.png" border="0" usemap="#namespaceStraightRebar_a1873c6f7f59b355a64fdd966ad75f778_icgraph" alt=""/></div>
<map name="namespaceStraightRebar_a1873c6f7f59b355a64fdd966ad75f778_icgraph" id="namespaceStraightRebar_a1873c6f7f59b355a64fdd966ad75f778_icgraph">
<area shape="rect" id="node2" href="namespaceStraightRebar.html#af6270367d7beae457813e33718d80faf" title="StraightRebar.makeStraight\lRebar" alt="" coords="227,5,409,47"/>
<area shape="rect" id="node6" href="namespaceStraightRebar.html#ab4c578165b01dd7c7d121e5345de2d7b" title="StraightRebar.editStraight\lRebar" alt="" coords="232,71,404,112"/>
<area shape="rect" id="node3" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#ad8a49d3d30ef3308b8386c9ebe1b67d8" title="StraightRebar._StraightRebar\lTaskPanel.accept" alt="" coords="457,39,651,80"/>
<area shape="rect" id="node4" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="701,5,894,47"/>
<area shape="rect" id="node5" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="699,71,896,112"/>
</map>
</div>
</p>

</div>
</div>
<a class="anchor" id="af6270367d7beae457813e33718d80faf"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def StraightRebar.makeStraightRebar </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>f_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>coverAlong</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>rt_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>lb_cover</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>diameter</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_check</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>amount_spacing_value</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>orientation</em> = <code>&quot;Horizontal&quot;</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>structure</em> = <code>None</code>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>facename</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<pre class="fragment">Adds the straight reinforcement bar to the selected structural object.

Case I: When orientation of straight rebar is 'Horizontal':
    makeStraightRebar(FrontCover, CoverAlong, RightCover, LeftCover, Diameter, AmountSpacingCheck, AmountSpacingValue, Orientation = "Horizontal",
    Structure, Facename)
    Note: Type of CoverAlong argument is a tuple. Syntax: (&lt;Along&gt;, &lt;Value&gt;). Here we have horizontal orientation so we can pass Top Side
    and Bottom Side to &lt;Along&gt; arguments.
    For eg. ("Top Side", 20) and ("Bottom Side", 20)

Case II: When orientation of straight rebar is 'Vertical':
    makeStraightRebar(FrontCover, CoverAlong, TopCover, BottomCover, Diameter, AmountSpacingCheck, AmountSpacingValue, Orientation = "Horizontal",
    Structure, Facename)
    Note: Type of CoverAlong argument is a tuple. Syntax: (&lt;Along&gt;, &lt;Value&gt;). Here we have vertical orientation so we can pass Left Side
    and Right Side to &lt;Along&gt; arguments.
    For eg. ("Left Side", 20) and ("Right Side", 20)
</pre> 
<p>Definition at line <a class="el" href="StraightRebar_8py_source.html#l00185">185</a> of file <a class="el" href="StraightRebar_8py_source.html">StraightRebar.py</a>.</p>
<div class="fragment"><div class="line"><a name="l00185"></a><span class="lineno"><a class="line" href="namespaceStraightRebar.html#af6270367d7beae457813e33718d80faf">  185</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespaceStraightRebar.html#af6270367d7beae457813e33718d80faf">makeStraightRebar</a>(f_cover, coverAlong, rt_cover, lb_cover, diameter, amount_spacing_check, amount_spacing_value, orientation = &quot;Horizontal&quot;, structure = None, facename = None):</div><div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    <span class="stringliteral">&quot;&quot;&quot; Adds the straight reinforcement bar to the selected structural object.</span></div><div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;<span class="stringliteral"></span></div><div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;<span class="stringliteral">    Case I: When orientation of straight rebar is &#39;Horizontal&#39;:</span></div><div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;<span class="stringliteral">        makeStraightRebar(FrontCover, CoverAlong, RightCover, LeftCover, Diameter, AmountSpacingCheck, AmountSpacingValue, Orientation = &quot;Horizontal&quot;,</span></div><div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;<span class="stringliteral">        Structure, Facename)</span></div><div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;<span class="stringliteral">        Note: Type of CoverAlong argument is a tuple. Syntax: (&lt;Along&gt;, &lt;Value&gt;). Here we have horizontal orientation so we can pass Top Side</span></div><div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;<span class="stringliteral">        and Bottom Side to &lt;Along&gt; arguments.</span></div><div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;<span class="stringliteral">        For eg. (&quot;Top Side&quot;, 20) and (&quot;Bottom Side&quot;, 20)</span></div><div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;<span class="stringliteral"></span></div><div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;<span class="stringliteral">    Case II: When orientation of straight rebar is &#39;Vertical&#39;:</span></div><div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;<span class="stringliteral">        makeStraightRebar(FrontCover, CoverAlong, TopCover, BottomCover, Diameter, AmountSpacingCheck, AmountSpacingValue, Orientation = &quot;Horizontal&quot;,</span></div><div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;<span class="stringliteral">        Structure, Facename)</span></div><div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;<span class="stringliteral">        Note: Type of CoverAlong argument is a tuple. Syntax: (&lt;Along&gt;, &lt;Value&gt;). Here we have vertical orientation so we can pass Left Side</span></div><div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;<span class="stringliteral">        and Right Side to &lt;Along&gt; arguments.</span></div><div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;<span class="stringliteral">        For eg. (&quot;Left Side&quot;, 20) and (&quot;Right Side&quot;, 20)</span></div><div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div><div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> structure <span class="keywordflow">and</span> <span class="keywordflow">not</span> facename:</div><div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;        selected_obj = FreeCADGui.Selection.getSelectionEx()[0]</div><div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;        structure = selected_obj.Object</div><div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;        facename = selected_obj.SubElementNames[0]</div><div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;    face = structure.Shape.Faces[<a class="code" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">getFaceNumber</a>(facename) - 1]</div><div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;    <span class="comment">#StructurePRM = getTrueParametersOfStructure(structure)</span></div><div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;    FacePRM = <a class="code" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">getParametersOfFace</a>(structure, facename)</div><div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;    <span class="keywordflow">if</span> <span class="keywordflow">not</span> FacePRM:</div><div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;        FreeCAD.Console.PrintError(<span class="stringliteral">&quot;Cannot identified shape or from which base object sturctural element is derived\n&quot;</span>)</div><div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;        <span class="keywordflow">return</span></div><div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    <span class="comment"># Get points of Striaght rebar</span></div><div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;    points = <a class="code" href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778">getpointsOfStraightRebar</a>(FacePRM, rt_cover, lb_cover, coverAlong, orientation)</div><div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;    <span class="keyword">import</span> Part</div><div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;    <span class="keyword">import</span> Arch</div><div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;    sketch = FreeCAD.activeDocument().addObject(<span class="stringliteral">&#39;Sketcher::SketchObject&#39;</span>, <span class="stringliteral">&#39;Sketch&#39;</span>)</div><div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    sketch.MapMode = <span class="stringliteral">&quot;FlatFace&quot;</span></div><div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    sketch.Support = [(structure, facename)]</div><div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    sketch.addGeometry(Part.LineSegment(points[0], points[1]), <span class="keyword">False</span>)</div><div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;        rebar = Arch.makeRebar(structure, sketch, diameter, amount_spacing_value, f_cover)</div><div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;        FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;        size = (ArchCommands.projectToVector(structure.Shape.copy(), face.normalAt(0, 0))).Length</div><div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;        rebar = Arch.makeRebar(structure, sketch, diameter, int((size - diameter) / amount_spacing_value), f_cover)</div><div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;    <span class="comment"># Adds properties to the rebar object</span></div><div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;    rebar.ViewObject.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;RebarShape&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).RebarShape = <span class="stringliteral">&quot;StraightRebar&quot;</span></div><div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;    rebar.ViewObject.setEditorMode(<span class="stringliteral">&quot;RebarShape&quot;</span>, 2)</div><div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;FrontCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Front cover of rebar&quot;</span>)).FrontCover = f_cover</div><div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;FrontCover&quot;</span>, 2)</div><div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;RightTopCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Right/Top Side cover of rebar&quot;</span>)).RightTopCover = rt_cover</div><div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;RightTopCover&quot;</span>, 2)</div><div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;LeftBottomCover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Left/Bottom Side cover of rebar&quot;</span>)).LeftBottomCover = lb_cover</div><div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;LeftBottomCover&quot;</span>, 2)</div><div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;CoverAlong&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Cover along&quot;</span>)).CoverAlong = coverAlong[0]</div><div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;CoverAlong&quot;</span>, 2)</div><div class="line"><a name="l00238"></a><span class="lineno">  238</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;Cover&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Cover of rebar along user selected side&quot;</span>)).Cover = coverAlong[1]</div><div class="line"><a name="l00239"></a><span class="lineno">  239</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;Cover&quot;</span>, 2)</div><div class="line"><a name="l00240"></a><span class="lineno">  240</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyBool&quot;</span>, <span class="stringliteral">&quot;AmountCheck&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Amount radio button is checked&quot;</span>)).AmountCheck</div><div class="line"><a name="l00241"></a><span class="lineno">  241</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;AmountCheck&quot;</span>, 2)</div><div class="line"><a name="l00242"></a><span class="lineno">  242</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyDistance&quot;</span>, <span class="stringliteral">&quot;TrueSpacing&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Spacing between of rebars&quot;</span>)).TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00243"></a><span class="lineno">  243</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;TrueSpacing&quot;</span>, 2)</div><div class="line"><a name="l00244"></a><span class="lineno">  244</span>&#160;    rebar.addProperty(<span class="stringliteral">&quot;App::PropertyString&quot;</span>, <span class="stringliteral">&quot;Orientation&quot;</span>, <span class="stringliteral">&quot;RebarDialog&quot;</span>, QT_TRANSLATE_NOOP(<span class="stringliteral">&quot;App::Property&quot;</span>, <span class="stringliteral">&quot;Shape of rebar&quot;</span>)).Orientation = orientation</div><div class="line"><a name="l00245"></a><span class="lineno">  245</span>&#160;    rebar.setEditorMode(<span class="stringliteral">&quot;Orientation&quot;</span>, 2)</div><div class="line"><a name="l00246"></a><span class="lineno">  246</span>&#160;    <span class="keywordflow">if</span> amount_spacing_check:</div><div class="line"><a name="l00247"></a><span class="lineno">  247</span>&#160;        rebar.AmountCheck = <span class="keyword">True</span></div><div class="line"><a name="l00248"></a><span class="lineno">  248</span>&#160;    <span class="keywordflow">else</span>:</div><div class="line"><a name="l00249"></a><span class="lineno">  249</span>&#160;        rebar.AmountCheck = <span class="keyword">False</span></div><div class="line"><a name="l00250"></a><span class="lineno">  250</span>&#160;        rebar.TrueSpacing = amount_spacing_value</div><div class="line"><a name="l00251"></a><span class="lineno">  251</span>&#160;    rebar.Label = <span class="stringliteral">&quot;StraightRebar&quot;</span></div><div class="line"><a name="l00252"></a><span class="lineno">  252</span>&#160;    FreeCAD.ActiveDocument.recompute()</div><div class="line"><a name="l00253"></a><span class="lineno">  253</span>&#160;    <span class="keywordflow">return</span> rebar</div><div class="line"><a name="l00254"></a><span class="lineno">  254</span>&#160;</div><div class="ttc" id="namespaceStraightRebar_html_a1873c6f7f59b355a64fdd966ad75f778"><div class="ttname"><a href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778">StraightRebar.getpointsOfStraightRebar</a></div><div class="ttdeci">def getpointsOfStraightRebar(FacePRM, rt_cover, lb_cover, coverAlong, orientation)</div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00040">StraightRebar.py:40</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a3885b3b63e3a41508ac79bc7550cf301"><div class="ttname"><a href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301">Rebarfunc.getFaceNumber</a></div><div class="ttdeci">def getFaceNumber(s)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00072">Rebarfunc.py:72</a></div></div>
<div class="ttc" id="namespaceRebarfunc_html_a92122b3d7cedd3d47bb63380a5ac4d08"><div class="ttname"><a href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08">Rebarfunc.getParametersOfFace</a></div><div class="ttdeci">def getParametersOfFace(structure, facename, sketch=True)</div><div class="ttdef"><b>Definition:</b> <a href="Rebarfunc_8py_source.html#l00126">Rebarfunc.py:126</a></div></div>
<div class="ttc" id="namespaceStraightRebar_html_af6270367d7beae457813e33718d80faf"><div class="ttname"><a href="namespaceStraightRebar.html#af6270367d7beae457813e33718d80faf">StraightRebar.makeStraightRebar</a></div><div class="ttdeci">def makeStraightRebar(f_cover, coverAlong, rt_cover, lb_cover, diameter, amount_spacing_check, amount_spacing_value, orientation=&quot;Horizontal&quot;, structure=None, facename=None)</div><div class="ttdef"><b>Definition:</b> <a href="StraightRebar_8py_source.html#l00185">StraightRebar.py:185</a></div></div>
</div><!-- fragment -->
<p><div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStraightRebar_af6270367d7beae457813e33718d80faf_cgraph.png" border="0" usemap="#namespaceStraightRebar_af6270367d7beae457813e33718d80faf_cgraph" alt=""/></div>
<map name="namespaceStraightRebar_af6270367d7beae457813e33718d80faf_cgraph" id="namespaceStraightRebar_af6270367d7beae457813e33718d80faf_cgraph">
<area shape="rect" id="node2" href="namespaceRebarfunc.html#a3885b3b63e3a41508ac79bc7550cf301" title="Rebarfunc.getFaceNumber" alt="" coords="499,5,677,32"/>
<area shape="rect" id="node3" href="namespaceRebarfunc.html#a92122b3d7cedd3d47bb63380a5ac4d08" title="Rebarfunc.getParametersOfFace" alt="" coords="236,31,451,57"/>
<area shape="rect" id="node4" href="namespaceStraightRebar.html#a1873c6f7f59b355a64fdd966ad75f778" title="StraightRebar.getpointsOf\lStraightRebar" alt="" coords="257,82,430,123"/>
</map>
</div>
</p>

<p><div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceStraightRebar_af6270367d7beae457813e33718d80faf_icgraph.png" border="0" usemap="#namespaceStraightRebar_af6270367d7beae457813e33718d80faf_icgraph" alt=""/></div>
<map name="namespaceStraightRebar_af6270367d7beae457813e33718d80faf_icgraph" id="namespaceStraightRebar_af6270367d7beae457813e33718d80faf_icgraph">
<area shape="rect" id="node2" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#ad8a49d3d30ef3308b8386c9ebe1b67d8" title="StraightRebar._StraightRebar\lTaskPanel.accept" alt="" coords="236,39,429,80"/>
<area shape="rect" id="node3" href="classStraightRebar_1_1__StraightRebarTaskPanel.html#a8190e8acf6121a5fe3b58d968ef17300" title="StraightRebar._StraightRebar\lTaskPanel.clicked" alt="" coords="479,5,673,47"/>
<area shape="rect" id="node4" href="classUShapeRebar_1_1__UShapeRebarTaskPanel.html#a1d59169cef16d01c4d09766255188fcb" title="UShapeRebar._UShapeRebar\lTaskPanel.clicked" alt="" coords="477,71,675,112"/>
</map>
</div>
</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a class="anchor" id="ad355d40e3bea5e86c24b6fe813264413"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string StraightRebar.__author__ = &quot;Amritpal Singh&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="StraightRebar_8py_source.html#l00025">25</a> of file <a class="el" href="StraightRebar_8py_source.html">StraightRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="ab1d45eb17133c23d9d6a3e2a6f2abb8a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string StraightRebar.__title__ = &quot;StraightRebar&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="StraightRebar_8py_source.html#l00024">24</a> of file <a class="el" href="StraightRebar_8py_source.html">StraightRebar.py</a>.</p>

</div>
</div>
<a class="anchor" id="aebf23f453d8fabed3a611d14f5e7f057"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">string StraightRebar.__url__ = &quot;https://www.freecadweb.org&quot;</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Definition at line <a class="el" href="StraightRebar_8py_source.html#l00026">26</a> of file <a class="el" href="StraightRebar_8py_source.html">StraightRebar.py</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Wed Dec 13 2017 22:36:42 for Rebar Addon for FreeCAD by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.11
</small></address>
</body>
</html>
